[[patch.notes.version.4.0]]
= Documentation Release Notes for {docversion}
include::ROOT:partial$entities.adoc[]
:revnumber: RC1
:revdate: May 15, 2019



== Latest Changes

{revnumber} {revdate}

== RC1 Changes

RC1 includes a massive number of changes to documents, additional material and a large number of qualitative updates.

There are far too many changes to include in the following list but these sufficiently cover the majority of content changes and additions.

.Changes During RC1
* Updated ISS section
* Updated troubleshooting
* Updated IBM Z section
* Updated to Unified Installer in Install Guide and Retail Guide
* Added Ubuntu Clients
* New live patching section for SLES 15
* New Content Staging feature/section
* Channel-Setup with Autoyast
* Update - Installing SUSE Manager Proxy Servers
* Creating Delta Images
* Update - smdba section
* Update - Cobbler section
* Update - Procedure for restoring from a manual backup
* Update - Formulas with forms
* The minion-action-cleanup task was added
* See extensions/xref-converter.rb for converting xrefs into paths within our PDF documents
* Reference - many xrefs have been updated (Systems and Users tabs remain)
* Missing images have been restored
* General editing and clean-up on many documents



=== Known Issues in {revnumber}

xref-converter.rb::
The converter still requires refactoring there are a few cross document links that are incorrectly transforming during PDF conversion.

xrefs::
Though all other xrefs in the Reference Manual have been updated the *Systems* and *User* tabs remain for *GMC*.
Books other than reference will be updated for *GMC*



== Beta 3 Changes

Our focus for SUSE Manager {productnumber} was to finish shifting the sources from our old IA (Information Architecture) into our new one. The Reference, Installation and Administration guides are now close to where we like them to be.

There are far too many changes to include in the following list but these sufficiently represent the larger changes.

=== Updated Items

* Content Lifecycle (REF)
* Added missing user menu content (REF)
* Added missing configuration menu content (REF)
* Added missing systems content (REF, autoinstallation coming soon.)
* Updated process configuration files (SUMA and Uyuni playbooks)
* Cleaned up our Makefile
* Added many missing images (REF, INSTALL and ADMIN)
* Added/updated missing Ubuntu content (CLIENT CONFIG)
* Fixed several build errors (INSTALLATION)
* Package lock notes (REF)
* Live Patching updates
* All future documentation will be based off the Master branch
* Fix req's discrepancy in install guide
* Unified Installer - Retail
* smdba sections need update
* *BZ#1131679* - Updated path for proxy config
* *BZ#1131977* Create Group; (RETAIL)
* *BZ#1131701* Bind formula procedure updated (retail)
* *BZ#1131691* - Best Practices bad link
* *BZ#1131398* - Client Registration
* *BZ#1131398* - Registering Salt clients
* *BZ#1131695* - Bad link in Retail book


=== Known Issues

==== Cross references

Cross references between docs are not currently working as expected, as a result of the conversion process.
During the *RC*, the correct references will be added and these will begin to work correctly.


==== Missing Content

You might notice some placeholder text or blank pages in some sections.
This is either content that we have not yet written, or content that has not yet been moved from its old home.
These will be corrected before *GM*.

==== Images

Some images might be missing, or might fail to load.
This is either because we need to take new screenshots, develop new graphics, or content that has not yet been moved from its old home.
These will be corrected before *GM*.


== Beta 2 Changes

=== Updated Documentation Structure

We have received an overwhelming amount of positive feedback about our documentation over the years, but we have also received some excellent ideas for improvement.
That is how we know that the content we have is great, but it was sometimes difficult to find.
In this release, we have reorganized our documentation and updated our tooling to make it clearer where information is, and make it easier for you to find the content you need, when you need it.

Please keep the feedback coming!
In this new layout, you can propose changes directly by clicking the btn:[Edit this Page] button.
Otherwise, you can always email us at TBD@suse.de
TODO:: check email address


[WARNING]
====
Do not use this documentation for production!
The documentation on this site is being offered as a preview of changes to come.
They are for testing purposes only.
====



=== Goals for this Release

* <<cleanup-ia>>
* <<search>>
* <<new-ui>>
* <<view-branches>>
* <<contribute>>
* <<pdf-output>>
* <<publishing>>



[[cleanup-ia]]
=== Content Cleanup

All {productname} books have been reworked into a new structure.



==== Old Naming Format

* Getting Started
* Best Practices
* Reference
* Advanced Topics



==== New Naming Format

* Installation Guide (Requirements, supported platforms, installation methods, etc)
* Client Configuration Guide (Configuring and connecting clients to {productname})
* Upgrade Guide (Migrate and update clients and {productname})
* Reference (Comprehensive guide to the {webui})
* Administration Guide (Maintenance and administration tasks in {susemgr})
* Salt Guide (A comprehensive guide to Salt for system administrators)
* Retail Guide (A guide to using {smr})
* Architecture Guide (Details on components, Salt and traditional architectures, and diagrams)



[[search]]
=== Real Time Search

We have added a prototype of real time search using Algolia.
We are still developing an alternative for offline reading.


[IMPORTANT]
====
Do not use this feature for production!
The search feature is currently a prototype and points to development and testing sources.
====



[[new-ui]]
=== Antora Static Site

All {susemgr} documentation is now written in AsciiDoc and built with Antora.
This makes it significantly easier for readers to become contributors by being able to edit the page directly in plain text (no more XML!).



[[view-branches]]
=== Documentation by Version

Beginning with {productname}{nbsp}4.0, you will be able to select which version of the documentation you want to view, by using the version switcher at the bottom of the navigation pane.



[[contribute]]
=== User Contributions

You may now contribute directly to any document you are currently viewing.

.Procedure: Contributing to documentation
. Select the btn:[Edit this page] link (Top right of the document)
. You will be directed to Github. Login, make your changes then submit a pull request.
. Your request will be reviewed by a technical writer and published.



[[pdf-output]]
=== PDF Output

Draft PDF documents are now available from the documentation index page.
Asciidoctor-pdf is currently used to produce PDF documents from our antora nav lists.
These documents are draft and should not be used in production.



[[publishing]]
=== Faster Publishing

Our new documentation site implements continuous integration with TravisCI.
As soon as as change is approved, TravisCI rebuilds the documentation and updates the published version within 3-5 minutes.
