[[patch.notes.version.4.0]]
= Documentation Release Notes for Version {docversion}
include::ROOT:partial$entities.adoc[]
:revnumber: V4.0
:revdate: February 27, 2019



== Latest Changes

{revnumber} {revdate}



=== Information Architecture Rework

We have received an overwhelming amount of positive feedback regarding our documentation. However we also received some excellent ideas for improvement from our engineers and customers alike. We have shifted our focus this release into providing you with a superior documentation experience by performing an information architecture rework.

[WARNING]
====
Do not use beta1 sources for production. These documents are for testing purposes only.
====

=== Goals for this Release

* <<cleanup-ia>>
* <<search>>
* <<new-ui>>
* <<view-branches>>
* <<contribute>>
* <<publishing>>



[[cleanup-ia]]
=== Content Cleanup

{productname} books have all been reworked. Topics have been placed into their correct homes.

==== Old Naming Format


* Getting Started
* Best Practices
* Reference
* Advanced Topics

==== New Naming Format

* Installation Guide (Requirements, supported platforms, installation methods, etc)
* Client Configuration Guide (Configuring and connecting clients to {productname})
* Upgrade Guide (Migrate and update both clients and {productname})
* Reference Manual (WebUI Reference)
* Administration Guide (Day two topics)
* Salt Guide (Beginner and Advanced Topics)
* Achitecture (Details on components, salt/traditional architectures and diagrams)




[[search]]
=== Realtime Search

A prototype of real-time search with Algolia was added during development, however we are looking into Apache Lucene and elastic search for customers with offline(disconnected setups) as an alternative.

We hope this provides a good example of what we are working towards. Test it out, by typing *salt*!

[IMPORTANT]
====
Search indexes point to development/testing sources. Do not use for production!
====

[[new-ui]]
=== Docs Based on Antora

Documentation is now built on Antora. This means contributors can write using text (no xml)


[[view-branches]]
=== Documentation by Branch

Beginning with {productname} Version 4.0, you will be able to view branches of documentation from our new WebUI.




[[contribute]]
=== User Contributions

You may now contribute to any document you are currently viewing.

.Procedure: Contributing to documentation
. Select the btn:[Edit this page] link (Top right of the document)
. You will be directed to Github. Login, make your changes then submit a pull request.
. Your request will be reviewed by a technical writer and published.




[[publishing]]
=== Publishing in Near Realtime

We have hooked up our documentation repository to travisci. When any pull request is accepted documents rebuild and are published. (Live within 3-5 minutes)



== Known Issues

=== PDF Outputs

PDF versions of the documentation will not be available for beta1. Expect these to arrive during beta2.

=== Cross references

Cross references between docs are being passed during our build process to prevent errors and therefore may not work as expected. Throughout documentation you will find the following syntax listed in place of our normal links:

====
pass:c[xref:FILENAME.adoc#SECTION-ID[]]
====

As we continue working the correct references will be added and the legacy ID's will be removed.

=== Missing Content

During the IA process we discovered several missing topics that you may find useful. These topics have either not been written or need to be moved from their old home. These will show up as empty with a title when selected. These will be addressed once current content has been properly placed within the new framework.

=== Images

Not all images have been moved to their correct locations. This will be resolved as we continue placing content.
