= SUSE Manager Documentation Repository
ifdef::env-github,backend-html5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:linkattrs:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Enterprise Linux
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:susemgr: SUSE Manager
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:saltversion: 2018.3.0
:webui: WebUI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
:ay: AutoYaST
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images


[suma.doc.intro]
== Introduction
This is the source for the official SUSE Manager documentation.

We welcome pull requests.
Please follow these instructions to create your pull request.

For more details on contributing to SUSE Manager documentation, visit the https://github.com/SUSE/doc-susemanager/wiki[SUSE Manager Documentation Wiki].  
The wiki contains information about word usage, markup conventions, our docs toolchain, building locally, and publishing documentation.



[suma.doc.contribution]
== Contributing

To contribute to SUSE Manager documentation:

. Clone the repository to your local machine:
+
----
git clone https://github.com/SUSE/doc-susemanager.git
----

. Check out the ``/master`` branch:
+
----
git checkout master
----

. Create a new working branch for your changes:
+
----
git checkout -b branchname
----

. Navigate to the [path]``adoc`` directory and make your changes using your preferred text editor.

. Ensure your changes build locally. This step requires that you have your local environment set up correctly.
 <!-- TODO: add environment setup instructions -->

. Add the updated files to your commit:
+
----
git add .
----

. Commit your changes:
+
----
git commit -m "Commit message here"
----

. Push your changes:
+
----
git push
----
+
If git prompts you to set an upstream in order to push, use this command:
+
----
git push --set-upstream origin <branchname>
----

. Create a pull request (PR) by navigating to https://github.com/SUSE/doc-susemanager and clicking on [btn]``Compare and Create Pull Request``.
Write an informative commit message detailing your changes, choose reviewers, and save your PR.


[NOTE]
====
Choose your reviewers carefully!
If you have made changes to the technical detail of the documentation, choose an appropriate subject matter expert (SME) to review those changes.
Additionally, every change requires at least one documentation team member to approve.
====


.Review Standards

These standards ensure that our documentation is accurate, that PRs are not left to age, and that the source code remains clean.
Ensure you follow these standards if you are participating in the SUSE Manager documentation repository.

* If you are still working on a PR, add ``[WIP]`` to the title of your PR.
This allows people to review the PR, but notifies reviewers that you have not completed work.
* Only the original author should merge PRs, do not merge other author's PRs unless you have express permission from them to do so.
* _Do not_ merge a PR until you have received the following approvals:
** For a technical change, approval from at least one SME
** For all changes, approval from at least one other member of the documentation team



[suma.docs.team]
== The SUSE Manager Documentation Team

* Joseph Cayouette @jcayouette
* Karl Eichwalder @keichwa
* Lana Brindley @Loquacity
