[[client-cfg-autoinstallation]]
== Starting an Autoinstallation

To start an autoinstallation the system must be known to SUSE Manager already.
You can use Bare-metal Provisioning (https://opensource.suse.com/doc-susemanager/suse-manager/reference/admin/bare-metal-systems.html)
to bring the system into SUSE Manager or you use the api system.createSystemRecord() or system.createSystemProfile().

```
$> spacecmd api -- --args '["systemname", {"hwAddress": "00:25:22:71:e7:c6", "hostname":"systemname"}]' system.createSystemProfile
```

Go to Systems => Overview => Select the system => Provisioning => Autoinstallation => Schedule
and select the autoyast profile you want to use to re-install the system.

(Advanced)

The "Create PXE installation configuration" can be used if the system should be installed for the first time.
A PXE boot configuration will be created and when you power on the machine and it is booting from the network
the correct profile will be selected.
 
If the system is already managed you can click on "Schedule Autoinstallation and Finish" button to start the installation.

