[[clients-ubuntu]]
= Ubuntu Clients




[[bp.expanded-support.ubuntu]]
== Managing {ubuntu} Clients
// ianew: clientconfig/ubuntu-clients.adoc
// iawho: lana 2019-03-01


Support for {ubuntu} Clients was added in {susemgr} 3.2.
Currently, Salt minions running {ubuntu} 16.04 LTS and 18.04 LTS are supported.

[NOTE]
====
{ubuntu} clients must be Salt minions.
Traditional clients are not supported.
====

Bootstrapping is supported for starting {ubuntu} clients and performing initial state runs such as setting repositories and performing profile updates.
However, the root user on {ubuntu} is disabled by default, so in order to use bootstrapping, you will require an existing user with [command]``sudo`` privileges for Python.

Other supported features:

* Synchronizing [systemitem]``.deb`` channels
* Assigning [systemitem]``.deb`` channels to minions
* GPG signing [systemitem]``.deb`` repositories
* Information displayed in System details pages
* Package install, update, and remove
* Package install using [systemitem]``Package States``
* Configuration and state channels

Some actions are not yet supported:

* Patch and errata support
* Bare metal installations, PXE booting, and virtual host provisioning
* Live patching
* CVE Audit
* If you use are using a repository from storage media (`server.susemanager.fromdir = ...` option in rhn.conf), Ubuntu Client Tools will not work.
// Reason: RMT and SMT cannot mirror Debian repositories (yet) and so cannot create it in that directory the correct files.
// We are waiting for SMT to release the feature/fix to mirror Debian repositories. When this has been done, this comment and the limitation above can be removed.


This section describes how to prepare {ubuntu} clients for registration to your {susemgr} Server.

// SUSE Manager specific instructions
//ifeval::[{suma-content} == true]

.Procedure: Setting up the software channels for {ubuntu} Client registration

Ensure you have the corresponding {ubuntu} product enabled and required channels have been fully synchronized:

.Ubuntu 18.04
* Product: {ubuntu} Client 18.04
* Mandatory channels: [systemitem]``ubuntu-18.04-pool-amd64``
+
.Ubuntu 16.04
* Product: {ubuntu} Client 16.04
* Mandatory channels: [systemitem]``ubuntu-16.04-pool-amd64``


After synchronization the following vendor channels will be created:

----
 ubuntu-18.04-pool for amd64
 |
 +- Ubuntu-18.04-SUSE-Manager-Tools for amd64
----

[NOTE]
====
The {ubuntu} vendor channels don't contain {ubuntu} upstream packages.
The repositories and channels for syncing upstream content must be configured manually.
====

Next create custom repositories to mirror the {ubuntu} packages (see <<manage-repositories.adoc>>):

For e.g. create repositories for the `main` and `main-updates` components:

* Repository Label: ubuntu-bionic-main
* Repository URL: http://ubuntumirror.example.com/ubuntu/dists/bionic/main/binary-amd64/
* Repository Type: deb

* Repository Label: ubuntu-bionic-main-updates
* Repository URL: http://ubuntumirror.example.com/ubuntu/dists/bionic-updates/main/binary-amd64/
* Repository Type: deb

Create custom channels under the `pool` channel and associate them with the repositories created in the previous step.

Suggested channels structure:

----
 ubuntu-18.04-pool for amd64 (vendor channel)
 |
 +- Ubuntu-18.04-SUSE-Manager-Tools for amd64 (vendor channel)
 |
 +- ubuntu-18.04-amd64-main (custom channel)
 |
 +- ubuntu-18.04-amd64-main-updates (custom channel)
----

Synchronize the custom channels (see <<s4-chnlmgmt-cdetails-repos>>).

You can check the progress of your synchronization from the command line using this command:
----
tail -f /var/log/rhn/reposync.log /var/log/rhn/reposync/*
----

.Procedure: Generate a bootstrap repository

To generate a bootstrap repository for {ubuntu}:

----
mgr-create-bootstrap-repo --with-custom-channels
----
//endif::[]

.Procedure: Preparing an {Ubuntu} Client for Registration

// Uyuni specific instructions
ifeval::[{suma-content} == false]
. On the client, open the [filename]``/etc/apt/sources.list.d/suma_client_tools.list`` file, and add this line:
+
----
deb https://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/debian/xUbuntu_16.04/ /
----
for Ubuntu 16.04 or
+
----
deb https://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/debian/xUbuntu_18.04/ /
----
for Ubuntu 18.04.
+
Make sure the `main` and `universe` upstream repositories are enabled.
+
endif::[]

. Edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line to the [filename]``sudoers`` file. Replace [systemitem]``<user>`` with the name of the user that will be used to bootsrap the client in the {webui}:
+
----
<user>   ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3
----
