[[clients-rh]]
= Registering {rhel} Clients

This section contains information about registering traditional and Salt clients running {rhel} operating systems.

[WARNING]
====
{rhel} Clients are completely based on {redhat} and unrelated to {sleses} Clients (also known as RES or {redhat} {slesa})
You are responsible for arranging access to {redhat} base media repositories and {rhela} installation media, as well as connecting {productname} Server to {redhat} Content Delivery Network
You must obtain support from either {redhat} all your {rhela} systems.
If you do not do this, you might be violating your terms with {redhat}.
====

== Server requirements

Ensure that your {productname} Server meets the requirements outlined at xref:installation:hardware-requirements.adoc[].

Taskomatic will use one CPU core, and requires at least 3072{nbsp}MB RAM.

To ensure that Taskomatic has access to enough memory, open the [path]``/etc/rhn/rhn.conf`` configuration file, add this line:

----
taskomatic.java.maxmemory=3072
----

Restart Taskomatic:
----
systemctl restart taskomatic
----

== Import {redhat} Entitlement and CA Certificate

During the next few paragraphs, you will learn how to import the {redhat} CA and entitlement certificate.

[WARNING]
====
Entitlement certificates have embedded expiration dates tied to the length of the support subscription. You must repeat this process with updated entitlement certificates as needed to avoid disruption in channel mirroring.
====

=== Entitlement Certificate

{redhat} Subscription Manager is a local service which tracks installed products and subscriptions on a local system to help manage subscription assignments. To obtain your certificates, you must register your system using this subscription manager tool supplied by {redhat}.

1. Register with the subscription manager tool from your {redhat} client. It will prompt you for your user name and password for authentication on the {redhat} Portal:

----
subscription-manager register
----

2. Navigate to the location of your entitlement certificate and key, and copy these files to where your Web browser connected to {productname} Server can open them:

----
cd /etc/pki/entitlement/
----

You will see two files with the data file format extension .pem (Program Editor macro). One is the certificate, and the other is the key and it has the word “key” in the file name.

=== {redhat} CA Certificate

The next step is to get the {redhat} CA Certificate file. It is located on this same {redhat} system in the file [path]``/etc/rhsm/ca/redhat-uep.pem``. Place this file in the same location where, in the previous section, you put the entitlement certificate.

=== Obtain Repository URL list

Use the subscription manager tool to obtain the URL’s of the repositories you want to mirror:

----
subscription-manager repos
----

=== Import

Now you are ready to import the {redhat} CA Certificate and Entitlement Certificate into {productname} Server for software repository mirroring. You must create three entries here: one each for the entitlement certificate, the entitlement key, and the {redhat} certificate.

* In the {productname} {webui}, navigate to menu:Systems[Autoinstallation > GPG and SSL Keys].

// Maybe we  should add a screenshot, as we have at the current guide: https://documentation.suse.com/sbp/all/html/SBP-sumaforrhel/index.html#sec-import

* Click **Create Stored Key/Cert** on the right. Another screen opens where you can fill in the required information.

// Another screenshot.

Enter the following values, and ensure you enter the date:

* **Description:** Entitlement-Cert-date
* **Type:** Ensure you select SSL
* **Select file to upload:** Browse to where you saved the Entitlement Certificate .pem file and select it.

Click the btn:[Create Key] at the bottom.

Repeat the above steps for the Entitlement Key and change the values to match the following:

* **Description:** Entitlement-key-date
* **Type:** SSL
* **Select file to upload:** Browse to the location where you saved the Entitlement key .pem file and select it.

Repeat the above steps for the {redhat} CA Certificate (redhat-uep) and change the values to match the following:

* **Description:** redhat-uep
* **Type:** SSL
* **Select file to upload:** Browse to the location where you saved the {redhat} CA Certificate and select it.

You now have imported the Entitlement certificate, the Entitlement key and the {redhat} CA into {productname} Server for use. Your outcome should look like the screen below:

== Create Software Repositories

[WARNING]
====
Use the output of repository URL’s obtained earlier from the subscription manager tool to create other repositories to which you are entitled. Mirror only the content which you need to manage your systems.
====

To mirror the software from the {redhat} CDN, you need to create custom channels and repositories in {productname} Server that are linked to the CDN with their respective URL. This will only work if you have entitlements to these products in your {redhat} Portal. To create these software repositories you need to perform the following actions.

On your {productname} Server {webui}, navigate to menu:Software[Manage > Repositories].

// Maybe a screenshot could help, as the original guide.

Click **Create Repository**. The following screen opens, where you can enter the required information to create the repository.

// Maybe a screenshot could help, as the original guide.

Fill in the fields with values, following the example below:

* **Repository Label:** rhel-7-server-rpms
* **Repository URL:** https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os/
* **Has Signed Metadata?:** Uncheck (Uncheck for all Red Hat Enterprise Repositories)
* **SSL CA Certificate:** redhat-uep
* **SSL Client Certificate:** Entitlement-Cert-date
* **SSL Client Key:** Entitlement-Key-date

Leave other filed with the default values.

These steps need to be repeated for the Products / Repository URLs you define for your environment.

== Create Software Channel Delivery

Next step is to create corresponding channels to which you assign these repositories.

On your {productname} Server {webui}, navigate to menu:Software[Manage > Channels].

=== Parent Channels Example

Click **Create Channel** and fill in the fields with at least the following values (change according to your {rhela} version):

* **Channel Name:** RHEL 7 x86_64
* **Channel Label:** rhel7-x86_64-server
* **Parent Channel:** None
* **Architecture:** x86_64
* **Repository Checksum Type:** sha1
* **Channel Summary:** RHEL 7 x86_64
* **Organization Sharing:** Public


After you have filled in the values, click again **Create Channel**.

Click the [guimenu]``Repositories`` tab, and mark the checkbox next to the appropriate repository, and then click btn:[Update repositories].

// Add a screenshot

Click the [guimenu]``Sync`` tab, and set your preferred recurring schedule for synchronization for this repository. Select btn:[Sync Now] to launch the synchronization immediately.

[WARNING]
====
{rhel} OS channels can grow to be very large. Thus it can take several hours to complete mirroring.
====

// add a screenshot

=== Child Channels example

Click **Create Channel** and fill in the fields with at least the following values (change according to your {rhela} version):

* **Channel Name:** RHEL 7 x86_64
* **Channel Label:** rhel7-x86_64-extras
* **Parent Channel:** rhel7-x86_64-server (from drop-down box)
* **Architecture:** x86_64
* **Repository Checksum Type:** sha1
* **Channel Summary:** RHEL 7 x86_64 Extras
* **Organization Sharing:** Public


After you have filled in the values, click again **Create Channel**.

Click the [guimenu]``Repositories`` tab, and mark the checkbox next to the appropriate repository, and then click btn:[Update repositories].

// Add a screenshot

Click the [guimenu]``Syn`` tab, and set your preferred recurring schedule for synchronization for this repository. You can also select btn:[Sync Now] to launch the synchronization immediately.

[WARNING]
====
Some of the {rhel} channels can grow to be very large. Thus it can take several hours to complete mirroring.
====

// add a screenshot

== Activation key

Now you can proceed to create the activation key in the {productname} Server {webui}, and assign appropriate channels to it.

== Registration

=== Add Client Tools channels

ifeval::[{suma-content} == true]
SUSE Manager subscriptions entitle everyone to the tools channels for {sleses} (also known as Red Hat Expanded Support or RES). Any Red Hat Enterprise Linux system should use these to create the proper bootstrap repository for either traditional or salt-minion connectivity.

1. Add the corresponding required {slesesa} channels and allow it to synchronize from SUSE Customer Center.

{slesesa} 6::
* "RHEL6 Base x86_64" and "SUSE Linux Enterprise Client Tools RES6 x86_64" at the WebUI, or [systemitem]``rhel-x86_64-server-6`` and [systemitem]``res6-suse-manager-tools-x86_64`` at CLI.

{slesesa} 7::
* "RHEL7 Base x86_64" and "SUSE Linux Enterprise Client Tools RES7 x86_64" at the WebUI, or [systemitem]``rhel-x86_64-server-7`` and [systemitem]``res7-suse-manager-tools-x86_64`` at CLI.

You can use [command]``mgr-sync`` to do it from CLI.

2. Add the new channels to the activation key you created previously.

endif::[]
ifeval::[{uyuni-content} == true]

// spacewalk-common-channels can't be used because centosX-uyuni-client requires centos7 channel as well, which a RHEL user would not need.

1. On your {productname} Server {webui}, navigate to menu:Software[Manage > Repositories].

Click **Create Repository**. The following screen opens, where you can enter the required information to create the repository.

Fill in the fields with values, following the example below:

* **Repository Label:** centos7-uyuni-client
* **Repository URL:** https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/
* **Has Signed Metadata?:** Uncheck

Leave other filed with the default values.

2. Click **Create Channel** and fill in the fields with at least the following values (change according to your {rhela} version and architecture):

* **Channel Name:** Uyuni Client Tools for CentOS 7 (x86_64)
* **Channel Label:** centos7-uyuni-client-x86_64
* **Parent Channel:** rhel7-x86_64-server
* **Architecture:** x86_64
* **Repository Checksum Type:** sha1
* **Channel Summary:** Uyuni Client Tools for CentOS 7 (x86_64)
* **Organization Sharing:** Public

After you have filled in the values, click again btn:[Create Channel].

Click the [guimenu]``Repositories`` tab, and mark the checkbox for ``centos7-uyuni-client``, and then click btn:[Update repositories].

Click the [guimenu]``Sync``tab, and set your preferred recurring schedule for synchronization for this repository. Select btn:[Sync Now] to launch the synchronization immediately.

3. Add the new channel to the activation key you created previously
endif::[]

=== Bootstrap Repository Creation

Create a bootstrap repository for your Red Hat Enterprise Linux clients with

----
mgr-create-bootstrap-repo --with-custom-channels
----

Ensure that it completes without error.

== Register {rhela} Clients

When you are ready to register your {rhel} client, follow the instructions in xref:client-configuration:registration-overview.adoc[].
