[[clients-rh]]
= Registering {rhel} Clients

This section contains information about registering traditional and Salt clients running {rhel} operating systems.

[IMPORTANT]
====
{rhel} clients are based on {redhat} and are unrelated to {sleses}, RES, {redhat}, or {slesa}.
You are responsible for arranging access to {redhat} base media repositories and {rhela} installation media, as well as connecting {productname} Server to the {redhat} content delivery network.
You must obtain support from {redhat} for all your {rhela} systems.
If you do not do this, you might be violating your terms with {redhat}.
====



== Server Requirements

Before you begin, check that your {productname} Server meets the requirements at xref:installation:hardware-requirements.adoc[].

Taskomatic uses one CPU core, and requires at least 3072{nbsp}MB of RAM.
To ensure that taskomatic has access to enough memory, open the [path]``/etc/rhn/rhn.conf`` configuration file, and add this line:

----
taskomatic.java.maxmemory=3072
----

Restart Taskomatic:
----
systemctl restart taskomatic
----

== Import Entitlements and CA Certificate

{redhat} clients require a {redhat} certificate authority (CA) and entitlement certificate.

Entitlement certificates are embedded with expiration dates, which match the length of the support subscription.
To avoid disruption, you will need to repeat this process at the end of every support subscription period.

{redhat} supply a subscription manager tool to manage subscription assignments.
It runs locally to track installed products and subscriptions.
Clients must be registered with the subscription manager to obtain certificates.

.Procedure: Registering Clients to Subscription Manager

. On the client system, at the command prompt, register with the subscription manager tool:
+
----
subscription-manager register
----
+
Enter your {redhat} Portal username and password when prompted.
. Copy your entitlement certificate and key from the client system, to a location that the {productname} Server can access:
+
----
cp /etc/pki/entitlement/ /<example>/entitlement/
----
+
[NOTE]
====
Your entitlement certificate and key will both have a file extension of [path]``.pem``.
The key will also have [path]``key`` in the filename.
====
+
. Copy the {redhat} CA Certificate file from the client system, to the same web location as the entitlement certificate and key:
+
----
cp /etc/rhsm/ca/redhat-uep.pem /example/entitlement
----


To manage repositories on your {redhat} client, you need to import the CA and entitlement certificates to the {productname} Server.
This requires three entries: one each for the entitlement certificate, the entitlement key, and the {redhat} certificate.



.Procedure: Importing Certificates to the Server

. On the {productname} Server {webui}, navigate to menu:Systems[Autoinstallation > GPG and SSL Keys].
+
// Maybe we  should add a screenshot, as we have at the current guide: https://documentation.suse.com/sbp/all/html/SBP-sumaforrhel/index.html#sec-import
// Not necessary, it's pretty simple to navigate to a page. LKB

. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement certificate:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-Cert-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement certificate, and select the [path]``.pem`` certificate file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the entitlement key:
* In the [guimenu]``Description`` field, type [systemitem]``Entitlement-key-date``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the entitlement key, and select the [path]``.pem`` key file.
. Click btn:[Create Key].
. Click btn:[Create Stored Key/Cert] and set these parameters for the {redhat} certificate:
* In the [guimenu]``Description`` field, type [systemitem]``redhat-uep``.
* In the [guimenu]``Type`` field, select [systemitem]``SSL``
* In the [guimenu]``Select file to upload`` field, browse to the location where you saved the {redhat} certificate, and select the certificate file.
. Click btn:[Create Key].

// put the screenshot here as a result. LKB


// Lana, you're up to here! 2019-09-27

== Repository Management



You can use the subscription manager tool to get the URLs of the repositories you want to mirror:

----
subscription-manager repos
----


== Create Software Repositories

[WARNING]
====
Use the output of repository URL’s obtained earlier from the subscription manager tool to create other repositories to which you are entitled. Mirror only the content which you need to manage your systems.
====

To mirror the software from the {redhat} CDN, you need to create custom channels and repositories in {productname} Server that are linked to the CDN with their respective URL. This will only work if you have entitlements to these products in your {redhat} Portal. To create these software repositories you need to perform the following actions.

On your {productname} Server {webui}, navigate to menu:Software[Manage > Repositories].

// Maybe a screenshot could help, as the original guide.

Click **Create Repository**. The following screen opens, where you can enter the required information to create the repository.

// Maybe a screenshot could help, as the original guide.

Fill in the fields with values, following the example below:

* **Repository Label:** rhel-7-server-rpms
* **Repository URL:** https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os/
* **Has Signed Metadata?:** Uncheck (Uncheck for all Red Hat Enterprise Repositories)
* **SSL CA Certificate:** redhat-uep
* **SSL Client Certificate:** Entitlement-Cert-date
* **SSL Client Key:** Entitlement-Key-date

Leave other filed with the default values.

These steps need to be repeated for the Products / Repository URLs you define for your environment.

== Create Software Channel Delivery

Next step is to create corresponding channels to which you assign these repositories.

On your {productname} Server {webui}, navigate to menu:Software[Manage > Channels].

=== Parent Channels Example

Click **Create Channel** and fill in the fields with at least the following values (change according to your {rhela} version):

* **Channel Name:** RHEL 7 x86_64
* **Channel Label:** rhel7-x86_64-server
* **Parent Channel:** None
* **Architecture:** x86_64
* **Repository Checksum Type:** sha1
* **Channel Summary:** RHEL 7 x86_64
* **Organization Sharing:** Public


After you have filled in the values, click again **Create Channel**.

Click the [guimenu]``Repositories`` tab, and mark the checkbox next to the appropriate repository, and then click btn:[Update repositories].

// Add a screenshot

Click the [guimenu]``Sync`` tab, and set your preferred recurring schedule for synchronization for this repository. Select btn:[Sync Now] to launch the synchronization immediately.

[WARNING]
====
{rhel} OS channels can grow to be very large. Thus it can take several hours to complete mirroring.
====

// add a screenshot

=== Child Channels example

Click **Create Channel** and fill in the fields with at least the following values (change according to your {rhela} version):

* **Channel Name:** RHEL 7 x86_64
* **Channel Label:** rhel7-x86_64-extras
* **Parent Channel:** rhel7-x86_64-server (from drop-down box)
* **Architecture:** x86_64
* **Repository Checksum Type:** sha1
* **Channel Summary:** RHEL 7 x86_64 Extras
* **Organization Sharing:** Public


After you have filled in the values, click again **Create Channel**.

Click the [guimenu]``Repositories`` tab, and mark the checkbox next to the appropriate repository, and then click btn:[Update repositories].

// Add a screenshot

Click the [guimenu]``Syn`` tab, and set your preferred recurring schedule for synchronization for this repository. You can also select btn:[Sync Now] to launch the synchronization immediately.

[WARNING]
====
Some of the {rhel} channels can grow to be very large. Thus it can take several hours to complete mirroring.
====

// add a screenshot

== Activation key

Now you can proceed to create the activation key in the {productname} Server {webui}, and assign appropriate channels to it.

== Registration

=== Add Client Tools channels

ifeval::[{suma-content} == true]
SUSE Manager subscriptions entitle everyone to the tools channels for {sleses} (also known as Red Hat Expanded Support or RES). Any Red Hat Enterprise Linux system should use these to create the proper bootstrap repository for either traditional or salt-minion connectivity.

1. Add the corresponding required {slesesa} channels and allow it to synchronize from SUSE Customer Center.

{slesesa} 6::
* "RHEL6 Base x86_64" and "SUSE Linux Enterprise Client Tools RES6 x86_64" at the WebUI, or [systemitem]``rhel-x86_64-server-6`` and [systemitem]``res6-suse-manager-tools-x86_64`` at CLI.

{slesesa} 7::
* "RHEL7 Base x86_64" and "SUSE Linux Enterprise Client Tools RES7 x86_64" at the WebUI, or [systemitem]``rhel-x86_64-server-7`` and [systemitem]``res7-suse-manager-tools-x86_64`` at CLI.

You can use [command]``mgr-sync`` to do it from CLI.

2. Add the new channels to the activation key you created previously.

endif::[]
ifeval::[{uyuni-content} == true]

// spacewalk-common-channels can't be used because centosX-uyuni-client requires centos7 channel as well, which a RHEL user would not need.

1. On your {productname} Server {webui}, navigate to menu:Software[Manage > Repositories].

Click **Create Repository**. The following screen opens, where you can enter the required information to create the repository.

Fill in the fields with values, following the example below:

* **Repository Label:** centos7-uyuni-client
* **Repository URL:** https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/
* **Has Signed Metadata?:** Uncheck

Leave other filed with the default values.

2. Click **Create Channel** and fill in the fields with at least the following values (change according to your {rhela} version and architecture):

* **Channel Name:** Uyuni Client Tools for CentOS 7 (x86_64)
* **Channel Label:** centos7-uyuni-client-x86_64
* **Parent Channel:** rhel7-x86_64-server
* **Architecture:** x86_64
* **Repository Checksum Type:** sha1
* **Channel Summary:** Uyuni Client Tools for CentOS 7 (x86_64)
* **Organization Sharing:** Public

After you have filled in the values, click again btn:[Create Channel].

Click the [guimenu]``Repositories`` tab, and mark the checkbox for ``centos7-uyuni-client``, and then click btn:[Update repositories].

Click the [guimenu]``Sync``tab, and set your preferred recurring schedule for synchronization for this repository. Select btn:[Sync Now] to launch the synchronization immediately.

3. Add the new channel to the activation key you created previously
endif::[]

=== Bootstrap Repository Creation

Create a bootstrap repository for your Red Hat Enterprise Linux clients with

----
mgr-create-bootstrap-repo --with-custom-channels
----

Ensure that it completes without error.

== Register {rhela} Clients

When you are ready to register your {rhel} client, follow the instructions in xref:client-configuration:registration-overview.adoc[].
