[[clients-ubuntu]]
= Registering {ubuntu} Clients

This section contains information about registering Salt clients running {ubuntu} operating systems.

{susemgr} supports {ubuntu} 16.04 LTS and 18.04 LTS Clients using Salt.
Traditional clients are not supported.

Supported features:

* Bootstrapping
* Synchronizing [systemitem]``.deb`` channels
* Assigning [systemitem]``.deb`` channels to clients
* GPG signing [systemitem]``.deb`` repositories
* Information displayed in System details pages
* Package install, update, and remove
* Package install using [systemitem]``Package States``
* Configuration and state channels

Bootstrapping is supported for starting {ubuntu} clients and performing initial state runs such as setting repositories and performing profile updates.

However, the root user on {ubuntu} is disabled by default, so in order to use bootstrapping, you will require an existing user with [command]``sudo`` privileges for Python.

Some actions are not yet supported:

* Patch and errata support
* Bare metal installations, PXE booting, and virtual host provisioning
* Live patching
* CVE Audit
* If you use are using a repository from storage media (`server.susemanager.fromdir = ...` option in rhn.conf), Ubuntu Client Tools will not work.
// Reason: RMT and SMT cannot mirror Debian repositories (yet) and so cannot create it in that directory the correct files.
// We are waiting for SMT to release the feature/fix to mirror Debian repositories. When this has been done, this comment and the limitation above can be removed.

[NOTE]
====
Canonical does not endorse or support {susemgr}.
====

== Prepare to Register {ubuntu} Clients

Some preparation is required before you can register {ubuntu} clients to the {productname} Server.

// ifndef works for displaying content when building uyuni
// ifdef does not show the content for uyuni
// ifeval works for displaying content

.Procedure: Adding the {ubuntu} Channels

// SUSE Manager content
ifeval::[{suma-content} == true]
Before you begin, ensure you have the {ubuntu} product enabled, and have synchronized the {ubuntu} channels for {scc}:

{ubuntu} 16.04::
* "Ubuntu 16.04" and "SUSE Linux Enterprise Client Tools Ubuntu 1604 amd64" at the {webui}, or [systemitem]``ubuntu-16.04-pool-amd64`` and [systemitem]``ubuntu-16.04-suse-manager-tools-amd64`` at CLI.

{ubuntu} 18.04::
* "Ubuntu 18.04" and "SUSE Linux Enterprise Client Tools Ubuntu 1804 amd64" at the {webui}, or [systemitem]``ubuntu-18.04-pool-amd64`` and [systemitem]``ubuntu-18.04-suse-manager-tools-amd64`` at CLI.

[WARNING]
====
The mandatory channels do not contain {ubuntu} upstream packages.
The repositories and channels for synchronizing upstream content must be configured manually.
====

. Ensure that you have the appropriate software channels available on your system.

In the {productname} {webui}, navigate to menu:Software[Channel List > All].
You should see a base channel and a child channel for your architecture, for example:
+
----
 ubuntu-18.04-pool for amd64
 |
 +- Ubuntu-18.04-SUSE-Manager-Tools for amd64
----
. Create custom repositories to mirror the {ubuntu} packages.
For example:
+
For `main`:

* Repository Label: ubuntu-bionic-main
* Repository URL: http://ubuntumirror.example.com/ubuntu/dists/bionic/main/binary-amd64/
* Repository Type: deb
+
For `main-updates`:

* Repository Label: ubuntu-bionic-main-updates
* Repository URL: http://ubuntumirror.example.com/ubuntu/dists/bionic-updates/main/binary-amd64/
* Repository Type: deb

. Create custom channels under the `pool` channel, mirroring the vendor channels.

Ensure the custom channels you create have `AMD64 Debian` architecture.
Create this structure:
+
----
 ubuntu-18.04-pool for amd64 (vendor channel)
 |
 +- Ubuntu-18.04-SUSE-Manager-Tools for amd64 (vendor channel)
 |
 +- ubuntu-18.04-amd64-main (custom channel)
 |
 +- ubuntu-18.04-amd64-main-updates (custom channel)
----

. Associate the custom channels with the appropriate custom repositories.
endif::[]
// End of SUSE Manager content
// Uyuni specific instructions, in fact this works at SUSE Manager as well, but spacewalk-common-channels script is NOT supported
ifeval::[{uyuni-content} == true]
Install the spacewalk-utils package:
----
sudo zypper in spacewalk-utils
----

At the command prompt on the {productname} Server, as root, add the Ubuntu channels (change the version of the channel names to match your Ubuntu version):

----
sudo spacewalk-common-channels ubuntu-1804-pool-amd64-uyuni ubuntu-1804-amd64-main-uyuni \
ubuntu-1804-amd64-main-update-uyuni ubuntu-1804-amd64-main-security-uyuni \
ubuntu-1804-amd64-universe-uyuni ubuntu-1804-amd64-uyuni-client
----
endif::[]

. Synchronize the new custom channels.

You can should also consider creating a regular synchronization schedule.

You can check the progress of your synchronization from the command line with this command:
+
----
tail -f /var/log/rhn/reposync.log /var/log/rhn/reposync/*
----

[WARNING]
====
{ubuntu} OS channels can grow to be very large. Thus it can take several hours to complete mirroring.
====

.Procedure: Creating the bootstrap repository

. To use bootstrap with {ubuntu}, you will need to create a bootstrap repository.
You can do this from the command line with [command]``mgr-create-bootstrap-repo``:
+
----
mgr-create-bootstrap-repo --with-custom-channels
----

For more information on creating custom repositories, see xref:administration:channel-management.adoc[].

.Procedure: Granting Root User Access

The root user on {ubuntu} is disabled by default.
You can enable it by editing the [filename]``sudoers`` file.

. On the client, edit the [filename]``sudoers`` file:
+
----
sudo visudo
----
+
Grant [command]``sudo`` access to the user by adding this line to the [filename]``sudoers`` file. Replace [systemitem]``<user>`` with the name of the user that will be used to bootstrap the client in the {webui}:
+
----
<user>   ALL=NOPASSWD: /usr/bin/python, /usr/bin/python2, /usr/bin/python3
----
