[[content-lifecycle]]
= Content Lifecycle Management
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]



Content Lifecycle Management is used to manage software channels through environments.
It allows you to select a custom set of software channels as sources, and create a series of environments that your software channels can move through on their lifecycle.

TODO:: Use case??

With the first version you are able to create content projects, select a custom set of software channels as sources and create a lifecycle made of environments.

Once you have selected some sources you can build the selected set which will populate the first environment. After the the first environment is built you can promote it through the environment lifecycle to the next environment in the loop.

The result of the build (therefore the content of every environment) is a channel tree (made of cloned software channels of the sources selection) and you can assign systems to it.

.Procedure: Creating a Content Lifecycle Project

. In the {productname} {webui}, navigate to menu:Content Lifecycle Management[Content Lifecycle Projects], and click btn:[Create Project]
. In the [guimenu]``label`` field, enter a label for your project.
The [guimenu]``label`` field only accepts lowercase letters, numbers, periods (``.``), hyphens (``-``) and underscores (``_``).
. In the [guimenu]``name`` field, enter a descriptive name for your project.
. Click the btn:[Create] button to create your project and return to the project page.
. Click btn:[Add new Source].
. In the [guimenu]``Sources`` dialog, select the source type, and select a base channel for your project.
The available child channels for the selected base channel will be displayed, including information on whether the channel is mandatory or recommended.
. Check the child channels you require, and click btn:[Save] to return to the project page.
The software channels you selected should now be showing.
. Click btn:[Add new Environment].
. In the [guimenu]``Environment Lifecycle`` dialog, give the first environment a name and a description, and click btn:[Save].
The [guimenu]``name`` field only accepts lowercase letters, numbers, periods (``.``), hyphens (``-``) and underscores (``_``).
. Continue creating environments until you have all the  environments for your lifecycle completed.
You can select the order of the environments in the lifecycle by selecting an environment in the [guimenu]``Insert before`` field when you create it.


.Procedure: Using a Content Lifecycle Project

. TBD ...
