[[content-lifecycle]]
= Content Lifecycle Management
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]



Content Lifecycle Management is used to manage software channels through environments.
It allows you to select a custom set of software channels as sources, and create a series of environments that your software channels can move through on their lifecycle.

TODO:: Use case??

With the first version you are able to create content projects, select a custom set of software channels as sources and create a lifecycle made of environments.

Once you have selected some sources you can build the selected set which will populate the first environment. After the the first environment is built you can promote it through the environment lifecycle to the next environment in the loop.

The result of the build (therefore the content of every environment) is a channel tree (made of cloned software channels of the sources selection) and you can assign systems to it.

.Procedure: Creating a Content Lifecycle Project

. In the {productname} {webui}, navigate to menu:Content Lifecycle Management[Content Lifecycle Projects], and click on btn:[Create Project]
. TBD ...
