[[virt-vhm]]
= Virtual Host Managers

Virtual Host Managers (VHMs) are used to gather information from a range of client types.

VHMs can be used to collect public cloud instances and organize them into virtualization groups.
With your virtualized clients organized this way, Taskomatic collects data on the clients for display in the {productname}{ {webui}.
VHMs also allow you to use subscription matching on your virtualized clients.

You can create a VHM on your {productname} Server, and use it to inventory available public cloud instances.
You can also use a VHM to manage clusters created with {k8s} and {caasp}.

For more information on using a VHM with Microsoft Azure, see xref:client-configuration:vhm-azure.adoc[].
For more information on using a VHM with Amazon Web Services, see xref:client-configuration:vhm-aws.adoc[].
For more information on using a VHM with Google Compute Engine, see xref:client-configuration:vhm-gce.adoc[].
For more information on using a VHM with {k8s}, see xref:client-configuration:vhm-kubernetes.adoc[].
//For more information on using a VHM with {caasp}, see xref:client-configuration:vhm-caasp.adoc[].



== VHM Setup


The Virtual Host Manager (VHM) runs on the {productname} Server.

To run a VHM, your {productname} Server will need to have port 443 open, in order to access the clients.


.Procedure: Creating a VHM

. In the {productname} {webui}, navigate to menu:Systems[Virtual Host Managers].
. Click btn:[Create] and select the appropriate VHM type from the drop-down menu.
. In the [guimenu]``Add a Virtual Host Manager`` section, complete the parameters as required for your environment.
. Click btn:[Create] to save your changes and create the VHM.
. On the [guimenu]``Virtual Host Managers`` page select the new VHM.
. On the [guimenu]``Properties`` page, click btn:[Refresh Data] to inventory the new VHM.

To see which objects and resources have been inventoried, navigate to menu:Systems[System List > Virtual Systems].
