[[virt-vhm]]
= Virtual Host Managers

Virtual Host Managers (VHMs) are used to something something

To begin, you will need to set up a VHM on your {productname} Server, and inventory the available VM hosts.
Taskomatic can then begin data collection using the VMs API.



== VHM Setup


The Virtal Host Manager (VHM) runs on the {productname} Server.

To run a VHM, your {productname} Server will need to have port 443 open, in order to access the VMWare API.

VMWare hosts use access roles and permissions to control access to hosts and guests.
Ensure that any VMWare objects or resources that you want to be inventoried by the VHM have at least [parameter]``read-only`` permissions.
If you want to exclude any objects or resources, mark them with [parameter]``no-access``.

When you are adding new hosts to {productname}, you will need to consider if the roles and permissions that have been assigned to users and objects need to be inventoried by {productname}.

For more on users, roles, and permissions, see the VMWare vSphere documentation: https://docs.vmware.com/en/VMware-vSphere/index.html


.Procedure: Creating a VMWare VHM

. In the {productname} {webui}, navigate to menu:Systems[Virtual Host Managers].
. Click btn:[Create] and select [guimenu]``VMWare-based``.
. In the [guimenu]``Add a VMWare-based Virtual Host Manager`` section, use these parameters:
* In the [guimenu]``Label`` field, type a custom name for your VHM.
* In the [guimenu]``Hostname`` field, type the fully-qualified domain name (FQDN) or host IP address.
* In the [guimenu]``Port`` field, type the ESXi API port to use (for example, [parameter]``443``).
* In the [guimenu]``Username`` field, type the username associated with the VM host.
* In the [guimenu]``Password`` field, type the password associated with the VM host user.
. Click btn:[Create] to save your changes and create the VHM.
. On the [guimenu]``Virtual Host Managers`` page select the new VHM.
. On the [guimenu]``Properties`` page, click btn:[Refresh Data] to inventory the new VHM.

To see which objects and resources have been inventoried, navigate to menu:Systems[System List > Virtual Systems].