[[installation-general-requirements.adoc]]
= Prerequisites for Installation

Before you begin your installation, ensure you have fulfilled these prerequisites:

* Current {scc} organization credentials
* Access to installation media for your chosen operating system
* Your environment meets the hardware and networking requirements
* You understand the supported client operating systems


This section contains more information on each of these prerequisites.

[NOTE]
====
{productname} {productnumber} is based on {slsa} {sles-version} {sp-version} as the host operating system.
====


[[quickstart.sect.prereq.scc]]
== Obtaining your SUSE Customer Center Credentials

You will need to create an account with {scc} before you install {sls} and {productname}.
To obtain your {scc} credentials:

[[creating.scc.account.mgr]]
.Procedure: Obtaining Your SCC Organization Credentials
. Open a browser and direct it to https://scc.suse.com/login.
. If you have not done so, create an account now.
. Log in to your new SCC account.
. Under the btn:[Management tools] widget select btn:[Manage Users].
. Click the btn:[Organization Credentials] tab.
. Record your login information for use during {productname} setup.



[[quickstart.sect.prereq.installmedia]]
== Obtaining Installation Media

This book describes installation methods for both {jeos} and {sls}.
The {jeos} image provides the quickest installation and setup, and is suitable for a test or proof of concept installation.
Alternatively, {sls} provides a more robust installation, which requires a larger initial download.
Choose your preferred operating system based on the type of environment you want to install, and the amount of bandwidth and time you have available.

You can find installation images for {jeos} and {slsa} in your {scc} account.
Log in, then navigate to the URL for your chosen operating system:

* https://www.suse.com/products/server/jeos/[JeOS - Media Download]
* https://www.suse.com/products/server/download/[SUSE Linux Enterprise Server - Media Download]



[[installation-general-supportedbrowsers]]

== Supported Browsers for the {susemgr} {webui}

In order to use the {webui} to manage your {susemgr} environment, you will need to ensure you are running an up to date web browser.
{susemgr} is supported on the latest Windows or {sle} web browsers.
