= Preparation and Requirements
include::_partials/entities.adoc[]

[#prepare-two-nodes]
== Prepare the Two Nodes

Begin by configuring *two* servers on KVM with the following software installed:

* *SUSE® Linux Enterprise Server 12 SP3* _(with all available online updates)_

* *SUSE Linux Enterprise High Availability Extension 12 SP3* _(with all available online updates)_

During the {sle} {sp-version} installation select *{sleha}* to be installed. 

[#node-server-requirements]
.KVM Node Server Disk and RAM Requirements
|===
| Requirements | Additional Info

| Disk Space | 100{nbsp}GB _(Btrfs)_
| RAM | 4096{nbsp}GB
| *Time Synchronization* - 
During the {sle} installation setup NTP. Cluster nodes must synchronize to an NTP server outside the cluster. | For more information, see the Administration Guide for SUSE Linux Enterprise Server 12 SP3:  

http://www.suse.com/documentation/sles-12/book_sle_admin/data/cha_netz_xntp.html[Time Synchronization with NTP]
|===

[IMPORTANT]
.Calculating RAM and Storage Requirements
====
In a production setting your storage needs and memory requirements will be much higher. These numbers depend entirely on your environment. See the {productname} documentation for recommendations on storage, memory and number of CPUs.
====

[#prepare-the-shared-storage-node]
== Prepare the iSCSI Storage Node

Continue by configuring a single storage server on KVM with the following software installed:

* *SUSE® Linux Enterprise Server 12 SP3* _(with all available online updates)_

* *SUSE Linux Enterprise High Availability Extension 12 SP3* _(with all available online updates)_

During the {sle} {sp-version} installation select {sleha} to be installed. 

[#shared-server-requirements]
.KVM Storage Server Disk Requirements
|===
| Requirements | Additional Info

| Disk Space | 500{nbsp}GB _(Btrfs)_
 | RAM       | 4096{nbsp}GB
 | *Time Synchronization* - During the {sle} installation setup NTP. Cluster nodes must synchronize to an NTP server outside the cluster. | For more information, see the Administration Guide for SUSE Linux Enterprise Server 12 SP3: 
 
http://www.suse.com/documentation/sles-12/book_sle_admin/data/cha_netz_xntp.html[Time Synchronization with NTP]