[[salt.formulas]]
= Formulas


Formulas are collections of Salt States that have been pre-written by other Salt users and contain generic parameter fields.
Formulas allow for reliable reproduction of a specific configuration.
Formulas can be installed from RPM packages or an external git repository.

Formulas work best for large, non-trivial, configurations.
For trivial tasks, use a state rather than a formula.

Formula data can be managed using the XMLRPC API.

Formulas and states both act as a kind of configuration documentation.
When you have written and stored the configuration, they provide a snapshot of your infrastructure.

You can use pre-written formulas as a starting point for your own custom formulas.
Pre-written formulas are available from https://github.com/saltstack-formulas.

You can use the {productname} {webui} to apply pre-existing {productname} formulas.
For more information on the standard formulas available, see xref:salt:salt-formulas-standard.adoc[].

Alternatively, you can write your own custom formulas.
For more information on custom formulas, see xref:salt:salt-formulas-custom.adoc[].
