== Big Scale Deployment (1000 Clients or More)

{productname} can be installed and used in large and small installations. For installations with more than 1000 clients per {productname} Server, adequate hardware sizing and parameter tuning must be performed.

[NOTE]
.Maximum number of clients
====
There is no hard maximum number of supported systems. Any number of factors can greatly affect how many clients can reasonably be used in a particular installation, including which features are used, how the systems are configured and the hardware configuration.
====

=== Hardware and infrastructure

Appropriate hardware is an absolute necessity for big scale deployments, but be aware that not all problems can be solved with better hardware.

The minimum requirements for the {productname} Server are:

* 8 recent {x86} cores. Note that only x86-64-based {productname} deployments are currently supported for large installations this stage
* 32 GiB of RAM. 64 GiB or more for installations with thousands of clients
* fast I/O storage devices, such as locally-attached SSDs. Locally-attached RAID-0 SSDs for PostgreSQL data directories are recommended
* if the SUSE Manager Server is virtualized, the `elevator=noop` kernel option should always be set for optimal I/O performance

{productname} Proxy instances are also required:

* use one {productname} Proxy per 500-1000 clients
** the exact number of clients should be chosen taking network bandwidth considerations into account (see below)
* {productname} Proxy instances require at least 2 recent {x86} cores, 16 GiB of RAM and sufficient storage for caching
* clients should never be directly attached to the {productname} Server (except possibly a small number for testing purposes)

[WARNING]
====
Large installations require regular Salt minions, suggestions in this chapter assume no traditional clients or Salt SSH minions are employed.
====

[TIP]
.Number of clients per {productname} Proxy
====
{productname} Proxy's main functionality is to implement a local cache for content served to clients from the Server, thus, employing {productname} Proxies can substantially reduce download time for clients and Server egress bandwidth usage.

The choice of the number of clients per {productname} Proxy affects the download time and should be done taking into account the network structure and available bandwidth.

It is recommended to size the count of clients per Proxy by estimating the download time of typical content, eg. package upgrades for a quarter, if quarterly patching of clients is the expected use case.

Here is a rough example calculation of the total time needed to transfer 400MB worth of upgrades through a physical link speed of 1 GB/s to 3000 clients:

----
400 MB  * 3000 / 119 MB/s / 60 = 169 min
----

Formula is:

----
Size of updates * Number of clients / Theoretical download speed / 60
----
====


=== Operation Recommendations

==== Salt Client Onboarding Rate


The rate at which SUSE Manager can onboard clients (accept Salt keys) is limited and depends on hardware resources.
Onboarding clients at a faster rate than SUSE Manager is configured for will build up a backlog of unprocessed keys slowing the process and potentially exhausting resources.
It is recommended to limit the acceptance key rate programmatically.
A safe starting point would be to onboard a client every 15 seconds, which can be implemented via the following command:

----
for k in $(salt-key -l un|grep -v Unaccepted); do salt-key -y -a $k; sleep 15; done
----

[[bp.chap.salt.minion.scaleability.unaccepted]]
==== Clients Running with Unaccepted Salt Keys


Clients which have not been onboarded, (clients running with unaccepted Salt keys) consume resources, in particular inbound network bandwidth for ~2.5 Kb/s per client.
1000 idle clients will consume around ~2.5 Mb/s, and this number will drop to almost 0 once onboarding has been completed.
Limit non-onboarded systems for optimal performance.

== Disabling the Salt Mine

In older versions, {productname} used a tool called Salt mine to check client availability.
The Salt mine would cause clients to contact the server every hour, which created significant load.
With the introduction of a more efficient mechanism in {productname}{nbsp}3.2, the Salt mine is no longer required.
Instead, the {productname} server uses Taskomatic to ping only the clients that appear to have been offline for twelve hours or more, with all clients being contacted at least once in every twenty four hour period by default.
You can adjust this by changing the [systemitem]``web.system_checkin_threshold`` parameter in [path]``rhn.conf``.
The value is expressed in days, and the default value is [literal]``1``.

Newly registered Salt clients will have the Salt mine disabled by default.
If the Salt mine is running on your system, you can reduce load by disabling it.
This is especially effective if you have a large number of clients.

Disable the Salt mine by running this command on the server:

----
salt '*' state.sls util.mgr_mine_config_clean_up
----

This will restart the clients and generate some Salt events to be processed by the server.
If you have a large number of clients, handling these events could create excessive load.
To avoid this, you can execute the command in batch mode with this command:

----
salt --batch-size 50 '*' state.sls util.mgr_mine_config_clean_up
----

You will need to wait for this command to finish executing.
Do not end the process with kbd:[Ctrl+C].
