== Big Scale Deployment (1000 Clients or More)

{productname} can be installed and used in large and small installations. For installations with more than 1000 clients per {productname} Server, adequate hardware sizing and parameter tuning must be performed.

[NOTE]
.Maximum number of clients
====
There is no hard maximum number of supported systems. Any number of factors can greatly affect how many clients can reasonably be used in a particular installation, including which features are used, how the systems are configured and the hardware configuration.
====

=== Hardware and infrastructure

Appropriate hardware is an absolute necessity for big scale deployments, but be aware that not all problems can be solved with better hardware.

The minimum requirements for the {productname} Server are:

* 8 recent {x86} cores. Note that only x86-64-based {productname} deployments are currently supported for large installations this stage
* 32 GiB of RAM. 64 GiB or more for installations with thousands of clients
* fast I/O storage devices, such as locally-attached SSDs. Locally-attached RAID-0 SSDs for PostgreSQL data directories are recommended
* if the SUSE Manager Server is virtualized, the `elevator=noop` kernel option should always be set for optimal I/O performance

{productname} Proxy instances are also required:

* use one {productname} Proxy per 500-1000 clients
** the exact number of clients should be chosen taking network bandwidth considerations into account (see below)
* {productname} Proxy instances require at least 2 recent {x86} cores, 16 GiB of RAM and sufficient storage for caching
* clients should never be directly attached to the {productname} Server (except possibly a small number for testing purposes)

[WARNING]
====
Large installations require regular Salt minions, suggestions in this chapter assume no traditional clients or Salt SSH minions are employed.
====

[TIP]
.Number of clients per {productname} Proxy
====
{productname} Proxy's main functionality is to implement a local cache for content served to clients from the Server, thus, employing {productname} Proxies can substantially reduce download time for clients and Server egress bandwidth usage.

The choice of the number of clients per {productname} Proxy affects the download time and should be done taking into account the network structure and available bandwidth.

It is recommended to size the count of clients per Proxy by estimating the download time of typical content, eg. package upgrades for a quarter, if quarterly patching of clients is the expected use case.

Here is a rough example calculation of the total time needed to transfer 400MB worth of upgrades through a physical link speed of 1 GB/s to 3000 clients:

----
400 MB  * 3000 / 119 MB/s / 60 = 169 min
----

Formula is:

----
Size of updates * Number of clients / Theoretical download speed / 60
----
====
