[[salt.rate.limiting]]
= Rate Limiting

Salt is able to run commands in parallel on a large number of minions.
This can potentially create large amounts of load on your infrastructure.
You can use these rate-limiting parameters to control the load in your environment.

These parameters are all configured in the [filename]``/etc/rhn/rhn.conf`` configuration file.

[NOTE]
====
Salt commands that are executed from the command line are not subject to these parameters.
====



== Batch Size

This parameter sets the maximum number of clients that can execute a single action at the same time.

Choosing a lower number will reduce system load and parallelism, but might reduce overall performance for processing actions.

Adjust the [systemitem]``java.salt_batch_size`` parameter.
Defaults to 100.



== Batch Delay

This parameter sets the amount of time, in seconds, to wait after an action is processed before beginning to process the action on the next minion.
To begin, actions are processed on the number of minions determined in the batch size parameter.
As each minion completes, the action begins on a new minion after the specified delay period.

Increasing the delay increases the chance that multiple minions will have completed before the next action is issued, resulting in fewer overall commands, and reducing load.

Adjust the [systemitem]``java.salt_batch_delay`` parameter.
Defaults to 1.0 seconds.



== Ping Timeout

Salt batch calls begin with the Salt master performing a presence ping on the minions.
This parameter changes the timeout setting for the presence ping, in seconds.

Adjust the [systemitem]``java.salt_presence_ping_timeout`` parameter.
Defaults to 4 seconds.



== Ping Gather Job Timeout

During Salt batch calls, a job runs on the Salt clients to handle the presence ping from the master.
This parameter changes the timeout setting for gathering the presence ping, in seconds.

If a minion does not reply to a ping within the allocated time, it will be marked as [systemitem]``not available``, and will be excluded from the command.
The {webui} will show a [systemitem]``minion is down`` message in this case.

For more information on minion timeouts, see xref:scale-minions.adoc[].

Adjust the [systemitem]``java.salt_presence_ping_gather_job_timeout`` parameter.
Defaults to 1 second.
