[[scale-salt-clients]]
= Scaling Salt Clients




== Salt Client Onboarding Rate


The rate at which SUSE Manager can on-board clients (accept Salt keys) is limited and depends on hardware resources.
On-boarding clients at a faster rate than SUSE Manager is configured for will build up a backlog of unprocessed keys slowing the process and potentially exhausting resources.
It is recommended to limit the acceptance key rate pro-grammatically.
A safe starting point would be to on-board a client every 15 seconds, which can be implemented via the following command:

----
for k in $(salt-key -l un|grep -v Unaccepted); do salt-key -y -a $k; sleep 15; done
----

[[bp.chap.salt.minion.scaleability.unaccepted]]
== Clients Running with Unaccepted Salt Keys


Clients which have not been on-boarded, (clients running with unaccepted Salt keys) consume resources, in particular inbound network bandwidth for ~2.5 Kb/s per client.
1000 idle clients will consume around ~2.5 Mb/s, and this number will drop to almost 0 once on-boarding has been completed.
Limit non-onboarded systems for optimal performance.
