[[channel-management]]
= Channel Management
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]
// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]

Channels are a method of grouping software packages.

In {productname}, channels are grouped into base and child channels, with base channels grouped by operating system type, version, and architecture, and child channels being compatible with their related base channel.
When a system has been assigned to a base channel, it is only possible for that system to install the related child channels.
Organizing channels in this way ensures that only compatible packages are installed on each system.

While {productname}  provides all required channels, you might find it useful to create custom channels specific to your environment.
{productname} Administrators and Channel Administrators have channel management authority, which gives them the ability to create and manage their own custom channels.

This section gives more detail on how to create, administer, and delete custom channels.

== Create Custom Channels

If you have custom software packages that you need to install on your {productname} systems, you can create a custom child channel to manage them.
You will need to create the channel in the {productname} {webui} and create a repository for the packages, before assigning the channel to your systems.

Note that if you include a package with [systemitem]``-release`` at the end of the package name in your channel, it will be automatically installed when the channel is installed.

[IMPORTANT]
====
Do not create child channels containing packages that are not compatible with the client system.
====

.Procedure: Create a custom channel

. In the {productname} {webui}, navigate to menu:Software[Manage Software Channels], and click btn:[Create Channel].
. On the [guimenu]``Create Software Channel`` page, give your channel a name (for example, [systemitem]``My Tools SLES 12 SP3 x86_64``) and a label (for example, [systemitem]``my-tools-sles12sp3-x86_64``).
. In the [guimenu]``Parent Channel`` drop down, choose the relevant base channel (for example [systemitem]``SLES12-SP3-Pool for x86_64``).
Ensure that you choose the compatible parent channel for your packages.
. In the [guimenu]``Architecture`` drop down, choose the appropriate hardware architecture (for example, [systemitem]``x86_64``).
. Provide any additional information in the contact details, channel access control, and GPG fields, as required for your environment.
. Click btn:[Create Channel]

.Procedure: Create a software repository

. In the {productname} {webui}, navigate to menu:Software[Manage Software Channels > Manage Repositories], and click btn:[Create Repository].
. On the [guimenu]``Create Repository`` page, give your repository a label (for example, [systemitem]``my-tools-sles12sp3-x86_64-repo``).
. In the [guimenu]``Repository URL`` field, provide the path to the folder that contains the [path]``repodata`` file (for example, [systemitem]``file:///opt/mytools/``).
You can use any valid addressing protocol in this field.
. Uncheck the [guimenu]``Has Signed Metadata?`` check box.
. Provide any additional information in the SSL fields, as required for your environment.
. Click btn:[Create Repository]
. Synchronize your new repository with your custom channel by navigating to menu:Software[Manage Software Channels > Overview], clicking on the name of your newly created custom channel, and navigating to the [guimenu]``Repositories`` tab.
. Ensure the repository you want to synchronize is checked, and click btn:[Update Repositories].
. Navigate to the [guimenu]``Sync`` tab and click btn:[Sync Now] to synchronize immediately.
You can also set an automated synchronization schedule on this tab.

.Procedure: Add cusatom channels to an activcation key

. In the {productname} {webui}, navigate to menu:Systems[Activation Keys], and select the key you want to add the custom channel to.
. On the [guiemnu]``Details`` tab, in the [guimenu]``Child Channels`` field, select the channel to associate.
You can hold the btn:[Ctrl] key to select multiple channels, if you need to.
. Click btn:[Update Activation Key].



== Delete Custom Channels

TODO:: write this

Note that when channels are deleted, the packages that are part of the deleted channel are not automatically removed.
If you try to update packages that have had their channel deleted, it can cause errors.
In this case, you will need to manually remove the packages.
Packages can be manually removed in the {productname} {webui} by going to menu:Systems[Systems > All] and selecting the system, navigating to the menu:States[Packages] tab, and setting the package state to [guimenu]``Removed``.
Note that removing the package using a command line package manager or the [guimenu]``Software`` menu will not permanently remove the package.
