[[channel-management]]
= Channel Management

Channels are a method of grouping software packages.

In {productname}, channels are grouped into base and child channels, with base channels grouped by operating system type, version, and architecture, and child channels being compatible with their related base channel.
When a system has been assigned to a base channel, it is only possible for that system to install the related child channels.
Organizing channels in this way ensures that only compatible packages are installed on each system.

While {productname} provides all required channels, you might find it useful to create custom channels specific to your environment.
{productname} Administrators and Channel Administrators have channel management authority, which gives them the ability to create and manage their own custom channels.

[NOTE]
====
When you subscribe to a vendor channel with a traditional client, the product package will automatically be installed.
On Salt clients, the packages will be added to the package state, and you will need to apply the highstate to push the changes to your systems.
====
