[[content-lifecycle]]
= Content Lifecycle Management Examples

This section contains some common examples of how you can use content lifecycle management.
Use these examples to build your own personalised implementation.



[#create-proj-for-patch-cycle]
== Creating a Project for a Monthly Patch Cycle



* Creating a filter for a project
* Adding a filter to a project
* Applying the filter to a new build environment
* Excluding a patch from a project
* Including a patch in a project



[#create-a-filter]
=== Create a Filter for the Project

The ``By Date`` filter excludes all patches released after a specified date.
This filter is useful for your CLM projects that follow a monthly patch cycle.


.Procedure: Creating the ``By Date`` Filter
. In the {productname} {webui}, navigate to menu:Content Lifecycle[Filters] and click btn:[Create Filter].

. In the [guimenu]``Filter Name`` field, type a name for your filter.
For example, [systemitem]``Exclude patches by date``.
. In the [guimenu]``Filter Type`` field, select [guimenu]``Patch (issued after)``.

. Select the date and time.
. Click btn:[Save].




[#add-filter-to-proj]
=== Adding the Filter to the Project

.Procedure: Adding a Filter to a Project
. In the {productname} {webui}, navigate to menu:Content Lifecycle[Projects] and select a project from the list.

. Click btn:[Attach/Detach Filters] link to see all available filters

. Select the new [guimenu]``Exclude patches by date`` filter.

. Click btn:[Save].



[#apply-filter-to-env]
=== Applying the Filter to the Environment

The new filter is added to your filter list, but it still needs to be applied to the project.
To apply the filter you need to build the first environment.

.Procedure: Using the Filter
Click btn:[Build] to build the first environment.

. OPTIONAL: Add a message.
You can use messages to help track the build history.

. Check that the filter has worked correctly by using the new channels on a test server.

. Click btn:[Promote] to move the content to the next environment.
The build will take longer if you have a large number of filters, or they are very complex.

[NOTE]
====
When you promote content from one environment to the next, a copy of the metadata is created.
Filters determine which metadata will be used to define your channels, as well the packages within those channels.
====



[#exclude-a-patch]
=== Excluding a Patch from the Project

Tests may help you discover issues.
Once an issue is found, exclude the problem patch released before the **by date** filter.

.Procedure: Excluding a Patch

. In the {productname} {webui}, navigate to menu:Content Lifecycle[Filters] and click btn:[Create Filter].

. In the [guimenu]``Filter Name`` field, enter a name for the filter.
For example, [systemitem]``Exclude openjdk patch``.
. In the [guimenu]``Filter Type`` field, select [guimenu]``Patch (matches Advisory Name)``.

. In the [guimenu]``Advisory Name`` field, type a name for the advisory.
For example, [systemitem]``SUSE-15-2019-1807``
. Click btn:[Save].

. Navigate to menu:Content Lifecycle[Projects] and select your project.

. Click on btn:[Attach/Detach Filters] link, select also **Exclude openjdk patch: ...**
from list and click on btn:[Save].

Rebuilding a previous environment with the btn:[Build] button includes the new exclude filter with the former **by date** filter.



[#include-a-patch]
=== Including a Patch in the Project

You receive a call from your Security Team.
They inform you that an important security patch was released several days after __August 1st__.
The name of the new patch is **SUSE-15-2019-2071**. You need to include this new patch into your next patch cycle.

[IMPORTANT]
====
Use the btn:[Allow] Filters rule to select patches from a full source and add them to a previous environment.
The btn:[Allow] filters rule overrides the exclude function of the btn:[Deny] filter rule.
====

.Procedure: Including a Patch in a Project
. Go to menu:Main Menu:[Content Lifecycle > Filters] and click on btn:[Create Filter].

. Enter a __Filter Name__ such as **Include kernel security fix**.

. Select **Patch (Advisory Name)** as the __Filter Type__.

. Select *equals* or *matches* as the __Matcher__.

. Enter **SUSE-15-2019-2071** as Advisory name, click on the btn:[Allow] radio button.

. Click btn:[Save] to store the Filter.

. Go to menu:Main Menu[Content Lifecycle > Projects] and select your Project from the list.

. Click on btn:[Attach/Detach Filters] link then select also **Include kernel security patch: ...** from the dropdown list.

. Click on btn:[Save].

. Rebuild the environment by clicking the btn:[Build] button.
The required patch is now included in your patch cycle.



[#update-a-patch-cycle]
== Update an Existing Monthly Patch Cycle

When a monthly patch cycle is over you can update the patch cycle for the new month.

.Procedure: Update a Monthly Patch Cycle
. Change the date of the **by date** filter to __September 1st__.
Alternatively, create a new filter and change the assignment to the project.

. Check if the exclude filter for **SUSE-15-2019-1807** can be detached from the project.
There may be a new patch available for fixing this issue.

. Detach the **include** filter. The filter is included by default.

. Complete updating your filters then rebuild the project to create a new environment with
patches for September 1st.



[#enhance-project-with-livepatching]
== Enhance a Project with Livepatching

This section will help you setup filters to aid you in creating proper environments for livepatching.

[IMPORTANT]
====

There are some important things to keep in mind when opting to use the livepatching feature:

* Use only **one** kernel version on your systems. The livepatching packages are installed with a specific kernel.

* Livepatching updates are shipped together in one patch.

* Each kernel patch that begins a new series of live patching kernels will display the **required reboot**
flag. These kernel patches come with livepatching tools. After installation you must reboot the system once before the following year.

* Install livepatches that **only match** the installed kernel version.

* Live patches comes as standalone patches. You must **exclude all** normal kernel patches
which contain a higher kernel version than the one you have installed on your systems.
====



[#exclude-higher-kernel-version]
=== Exclude Packages with a Higher Kernel Version

In this example you will update your systems with patch *SUSE-15-2019-1244* which contains *kernel-default-4.12.14-150.17.1-x86_64*.

You need to exclude all patches which contain a higher version of kernel-default.

Procedure: Exclude Packages with a Higher Kernel Version

. Go to menu:Main Menu[Content Lifecycle > Filters] and click on btn:[Create Filter].

. Enter a Filter Name such as **Exclude kernel greater than 4.12.14-150.17.1**

. Select **Patch contains package with version greater than** from the Filter Type dropdown.

. Enter the following values in the available fields:

* Package Name: `kernel-default`
* Epoch: `<empty>`
* Version: `4.12.14`
* Release: `150.17.1`

. Click on btn:[Save] to store the Filter.

. Go to menu:Main Menu[Content Lifecycle > Projects] and select your Project from the list.

. Click on btn:[Attach/Detach Filters] link.

. Select **Exclude kernel greater than 4.12.14-150.17.1: ...** from the list and click on btn:[Save].


Once you click the btn:[Build] button a new environment will be created that contains all kernel patches up to the version you have installed.

NOTE: All kernel patches with higher kernel versions are removed. Live patching kernels
will stay available as long as they are not the first in a series.



[#update-project-for-next-patch-month]
== Update the Project for Next Patch Month

// WIP Joseph
To update the project to the next patch month you operate similar to the case before.
Important is, that you do not change the "Exclude kernel greater than 4.12.14-150.17.1: ..."
Filter. With it you keep normal kernel-updates away, but take the latest live patches
up to the selected month.



[#switch-kernel-version-for-live-patching]
== Switch to a New Kernel Version for Live Patching

Live Patching for a specific kernel version is only available for one year. After one year
you must update the kernel on your systems. The following changes of the environment
should be executed:

.Procedure: Switch to a New Kernel Version
. Decide which kernel version you will upgrade to. For example: `4.12.14-150.32.1`
. Create a new kernel version Filter.
. Detach the previous filter **Exclude kernel greater than 4.12.14-150.17.1** and attach the new filter.

Click btn:[Build] to rebuild the environment.
The new environment contains all kernel patches up to the new kernel version you selected.
Systems using these channels will have the kernel update available for installation.
You will need to reboot systems after they have performed the upgrade.
The new kernel will remain valid for one year.
All packages installed during the year will match the current live patching kernel filter.
