[[content-lifecycle]]
= Content Lifecycle Management

Content Lifecycle Management allows you to customize and test packages before updating production systems.
This is especially useful if you need to apply updates during a limited maintenance window.

Content Lifecycle Management allows you to select software channels as sources, adjust them as required for your environment, and thoroughly test them before installing onto your production systems.

While you cannot directly modify vendor channels, you can clone them and then modify the clones by adding or removing packages and custom patches.
You can then assign these cloned channels to test systems to ensure they work as expected and, once all tests pass, apply them to production servers.

This is achieved through a series of environments that your software channels can move through on their lifecycle.
Most environment lifecycles include at least test and production environments, but you can have as many environments as you require.

[WARNING]
====
This feature is not yet complete!
The documentation for this feature is being offered as a preview of changes to come.
====

== Managing Content Lifecycle Projects

.Procedure: Creating a Content Lifecycle Project

. In the {productname} {webui}, navigate to menu:Content Lifecycle Management[Content Lifecycle Projects], and click btn:[Create Project]
. In the [guimenu]``label`` field, enter a label for your project.
The [guimenu]``label`` field only accepts lowercase letters, numbers, periods (``.``), hyphens (``-``) and underscores (``_``).
. In the [guimenu]``name`` field, enter a descriptive name for your project.
. Click the btn:[Create] button to create your project and return to the project page.
. Click btn:[Attach/Detach Sources].
. In the [guimenu]``Sources`` dialog, select the source type, and select a base channel for your project.
The available child channels for the selected base channel will be displayed, including information on whether the channel is mandatory or recommended.
. Check the child channels you require, and click btn:[Save] to return to the project page.
The software channels you selected should now be showing.
. Click btn:[Attach/Detach Filters].
. In the [guimenu]``Filters`` dialog, select the filters you want to attach to the project. For creating a filter, click the btn:[Create new Filter] in the same dialog.
. Click btn:[Add new Environment].
. In the [guimenu]``Environment Lifecycle`` dialog, give the first environment a name and a description, and click btn:[Save].
The [guimenu]``name`` field only accepts lowercase letters, numbers, periods (``.``), hyphens (``-``) and underscores (``_``).
. Continue creating environments until you have all the  environments for your lifecycle completed.
You can select the order of the environments in the lifecycle by selecting an environment in the [guimenu]``Insert before`` field when you create it.

.Procedure: Using a Content Lifecycle Project

. TBD ...
