[[custom-ssl]]
= Custom SSL Certificates

You can use custom certificates with {productname} and {productname} Proxy.

This section covers how to use a third party SSL certificate authority with a new {productname} installation, replacing existing third party certificates, and replacing a self-signed certificate with a third party certificate.

Before you begin, ensure you have:

* A certificate authority (CA) SSL public certificate
* An SSL private key
* An SSL public certificate

Your key and certificate files must be in PEM format.

The host name of the SSL keys and certificates must match the host name of the machine you deploy them on.

If you want to use intermediate certificates, you need to merge the intermediate and root CA certificates into one file.
Ensure that the intermediate certificate comes first in the combined file.


== Custom Certificates for New Installations

By default, {productname} uses a self-signed certificate.
After you have completed the initial setup, you can replace the default certificate with a custom certificate.

.Procedure: Installing Custom Certificates on a New {productname} Server

. Install the {productname} Server according to the instructions in xref:installation:install-intro.adoc[].
. Complete the initial setup according to xref:installation:server-setup.adoc[].
. At the command prompt, point the SSL environment variables to the custom certificate file locations:
+
----
export CA_CERT=`path_to_CA_certificate_file`
export SERVER_KEY=`path_to_web_server_key`
export SERVER_CERT=`path_to_web_server_certificate`
----
. Complete {productname} setup:
+
----
yast2 susemanagersetup
----
+
When you are prompted for certificate details during setup, fill in random values.
The values will be overridden by the values you specified at the command prompt.

[NOTE]
====
Execute the [command]``yast2 susemanagersetup`` command from the same shell you exported the environment variables from.
====


== Custom Certificates for New Proxy Installations

By default, {productname} Proxy uses a self-signed certificate.
After you have completed the initial setup, you can replace the default certificate with a custom certificate.

.Procedure: Installing Custom Certificates on a New {productname} Proxy

. Install the {productname} Proxy according to the instructions in xref:installation:install-intro.adoc[].
. Complete the initial setup according to xref:installation:proxy-setup.adoc[].
. At the command prompt, run:
+
----
configure-proxy.sh
----
. At the ``Do you want to import existing certificates?`` prompt, type kbd:[y]
. Follow the prompts to complete setup.



== Replace Existing Custom Certificates

If your existing custom certificates have become corrupted or stopped working for any reason, you can generate a new certificate from the existing CA.

.Procedure: Replacing an Existing Custom Certificate

. On the {productname} Server, at the command prompt, regenerate the certificate:
+
----
rhn-ssl-tool --gen-server --dir="/root/ssl-build" --set-country="COUNTRY" \
--set-state="STATE" --set-city="CITY" --set-org="ORGANIZATION" \
--set-org-unit="ORGANIZATION UNIT" --set-email="name@example.com" \
--set-hostname="susemanager.example.top" --set-cname="example.com"
----
Ensure that the [systemitem]``set-cname`` parameter is the fully-qualified domain name of your {productname} Server.
You can use the the [systemitem]``set-cname`` parameter multiple times if you require multiple aliases.
. Install the RPM that contains the newly generated certificate:
+
----
rpm -Uhv /root/ssl-build/lnx0259a/rhn-org-httpd-ssl-key-pair-lnx0259a-1.0-2.noarch.rpm
----
. Restart services to pick up the changes:
+
----
spacewalk-service restart
----



== Replace Self-Signed Certificates with Custom Certificates

TBD
