[[custom-ssl]]
= Custom SSL Certificates

You can use custom certificates with {productname} and {productname} Proxy.

This section covers how to use a third party SSL certificate authority with a new {productname} installation, replacing a self-signed certificate with a third party certificate, and how to replace existing third party certificates.

Before you begin, ensure you have:

* A certificate authority (CA) SSL public certificate
* An SSL private key
* An SSL public certificate

Your key and certificate files must be in PEM format.

The host name of the SSL keys and certificates must match the host name of the machine you deploy them on.

If you want to use intermediate certificates, you need to merge the intermediate and root CA certificates into one file.
Ensure that the intermediate certificate comes first in the combined file.


== Custom Certificates for New Installations

By default, {productname} uses a self-signed certificate.
After you have completed the initial setup, you can replace the default certificate with a custom certificate.

.Procedure: Installing Custom Certificates on a New {productname} Server

. Install the {productname} Server according to the instructions in xref:installation:install-intro.adoc[].
. Complete the initial setup according to xref:installation:server-setup.adoc[].
. At the command prompt, point the SSL environment variables to the custom certificate file locations:
+
----
export CA_CERT=`path_to_CA_certificate_file`
export SERVER_KEY=`path_to_web_server_key`
export SERVER_CERT=`path_to_web_server_certificate`
----
. Complete {productname} setup:
+
----
yast2 susemanagersetup
----
+
When you are prompted for certificate details during setup, fill in random values.
The values will be overridden by the values you specified at the command prompt.

[NOTE]
====
Execute the [command]``yast2 susemanagersetup`` command from the same shell you exported the environment variables from.
====


== Custom Certificates for New Proxy Installations

By default, {productname} Proxy uses a self-signed certificate.
After you have completed the initial setup, you can replace the default certificate with a custom certificate.

.Procedure: Installing Custom Certificates on a New {productname} Proxy

. Install the {productname} Proxy according to the instructions in xref:installation:install-intro.adoc[].
. Complete the initial setup according to xref:installation:proxy-setup.adoc[].
. At the command prompt, run:
+
----
configure-proxy.sh
----
. At the ``Do you want to import existing certificates?`` prompt, type kbd:[y]
. Follow the prompts to complete setup.



== Replace Self-Signed Certificates with Custom Certificates

TBD



== Replace Existing Custom Certificates.

TBD
