[[iss]]
= Inter-Server Synchronization

If you have more than one {productname} installation, you will probably want to ensure that they stay aligned on content and permissions.
Inter-Server Synchronization (ISS) allows you to connect two or more {productname} Servers and keep them up-to-date.

To set up ISS, you need to define one {productname} Server as a master, with the other as a slave.
This is so that, where conflicting configurations exist, the system will know which configuration to prioritize.

.Procedure: Setting up an ISS Master

. In the {productname} {webui}, navigate to menu:Admin[ISS Configuration > Slave Setup], and click btn:[Add new master].
. In the [guimenu]``Details for new Master`` dialog, provide these details for the Server to use as the ISS Master:

* In the [guimenu]``Master Fully-Qualified Domain Name`` field, enter the FQDN of the ISS Master (for example: [systemitem]``http://server1.example.com``).
* In the [guimenu]``Filename of this Master's CA Certificate`` field, enter the absolute  path to the CA certificate on the ISS Master (for example: [systemitem]``/etc/pki/trust/anchors-org-ssl``)
. Click btn:[Add new master] to add the ISS master.

.Procedure: Setting up an ISS Slave

. In the {productname} {webui}, navigate to menu:Admin[ISS Configuration > Master Setup], and click btn:[Add new slave].
. In the [guimenu]``Edit Slave Details`` dialog, provide these details for the Server to use as the ISS Slave:

* In the [guimenu]``Slave Fully-Qualified Domain Name`` field, enter the FQDN of the ISS Slave (for example: [systemitem]``http://server2.example.com``).
* Check the [guimenu]``Allow Slave to Sync?`` checkbox to enable the Slave to synchronize with the Master.
* Check the [guimenu]``Sync All Orgs to Slave?`` checkbox to synchronize all organizations to this Slave.
. Click btn:[Create] to add the ISS Slave.
. In the [guimenu]``Allow Export of the Selected Organizations`` section, check the organizations you want to allow this Slave to export to the Master, and click btn:[Allow Orgs].

When you have the Master and Slaves set up, you can perform a synchronization from the command line on the Master, with this command:

----
mgr-inter-sync
----
