[[maintenance-window]]
= Maintenance Window Checklist

If you work on a {productname} Server with scheduled maintenance windows, you might find it difficult to remember all the things that you need to during that critical downtime.

This section contains a checklist for your maintenance window, with links to further information on performing each of the steps, if you need it.


. Stop services.
You will need to stop the spacewalk, SAP, and database services, along with any others you have running.
. Check if the configuration is still correct.
. On Salt systems, apply the highstate.
. Apply the latest updates.
See xref:upgrade:server-upgrade.adoc[].
. Update to the latest service pack, if required.
See xref:upgrade:migrate-4x-4x.adoc[].
. Reboot the server.
. Check if the configuration is still correct.
. On Salt systems, apply the highstate.
. Start any stopped services.



== Keep the Server Patched

As with any {sle} system, you are encouraged to install package updates on the {susemgr} Server when they arrive.
You can install these update with {yast} online update (see SLE Administration Guide, Chapter Common Tasks, https://www.suse.com/documentation/sles-15/book_sle_admin/data/cha_onlineupdate_you.html) or with ``zypper up`` or ``zypper patch`` (see SLE Administration Guide, Chapter Common Tasks, Section Managing Software with Command Line Tools, https://www.suse.com/documentation/sles-15/book_sle_admin/data/sec_zypper.html).
Preferable, you will run such a tool within a maintenance window; for more information, see xref:administration:maintenance-window.adoc#maintenance-window[].

//// complete procedure, also see above:
1. Log in as root user to the SUSE Manager server.
2. Stop the Spacewalk service:
   spacewalk-service stop
3. Apply the patch using either zypper patch or YaST Online Update.
4. Upgrade the database schema:
    spacewalk-schema-upgrade
5. Start the Spacewalk service:
    spacewalk-service start
////

By default, several update channels are configured and enabled for the {susemgr} Server.
Thus improved packages will become available automatically.
Check whether the update channels are actually available:

----
zypper lr
----

Shortened output:

----
Name                                                   | Enabled | GPG Check | Refresh
-------------------------------------------------------+---------+-----------+--------
SLE-Module-Basesystem15-SP1-Pool                       | Yes     | (r ) Yes  | No     
SLE-Module-Basesystem15-SP1-Updates                    | Yes     | (r ) Yes  | Yes    
SLE-Module-Python2-15-SP1-Pool                         | Yes     | (r ) Yes  | No     
SLE-Module-Python2-15-SP1-Updates                      | Yes     | (r ) Yes  | Yes    
SLE-Product-SUSE-Manager-Server-4.0-Pool               | Yes     | (r ) Yes  | No     
SLE-Product-SUSE-Manager-Server-4.0-Updates            | Yes     | (r ) Yes  | Yes    
SLE-Module-SUSE-Manager-Server-4.0-Pool                | Yes     | (r ) Yes  | No     
SLE-Module-SUSE-Manager-Server-4.0-Updates             | Yes     | (r ) Yes  | Yes    
SLE-Module-Server-Applications15-SP1-Pool              | Yes     | (r ) Yes  | No     
SLE-Module-Server-Applications15-SP1-Updates           | Yes     | (r ) Yes  | Yes    
SLE-Module-Web-Scripting15-SP1-Pool                    | Yes     | (r ) Yes  | No     
SLE-Module-Web-Scripting15-SP1-Updates                 | Yes     | (r ) Yes  | Yes    
----

Additionally, from time to time all the package updates are bundled and released as a maintenance update.
If you want to  install such a MU, the version number of the {susemgr} product will get increased from 4.0.1 to 4.0.2, for example.
You can verify the version number at the botton of the navigation bar.
You can also fetch the version number with the [literal]``api.getVersion()`` XMLRPC API call.

With [command]``zypper migration`` you will update the product from version 4.0.x to 4.1.x, for example:

----
zypper migration
----

This procedure is also known as a Service Pack (SP) migration.

To keep {susemgr} {productnumber} patched, you either connect it directly to {scc} (SCC) or use {rmtool} (RMT) as a local installation source.

