[[public-cloud-azure]]
= SUSE Manager Server in Azure



== Resource Requirements



=== Image and VM (Virtual Machine)

Image Resource::
``SUSE Manager Server 4 BYOS``
+

The image is a pre-built image created by {suse}.
It is based on JeoS, and SUSE Manager is pre-installed but not configured. Configuring SUSE Manager has to be done manually with {yast}.

VM (Virtual Machine)::
Recommended VM size is `B2ms`. This contains:
+

. 2 vCPUs
. 8 GB RAM
. Up to 4 data disks
. Max IOPS 2400
. Temporary storage disk of 16Gb.
Data on this disk will be destroyed after the guest has been switched off.



=== Disk Partitoning

The OS disk is 30 GiB and for storage account type select `Standard HDD`.

Add 3 additional data disks:

Data Disk 0::
Size 64 GiB on Premium SSD. This will [path]``/var/lib/pgsql``

Data Disk 1::
Size 512 GiB on Standard SSD. This will be mounted at [path]``/var/spacewalk``

Data Disk 2::
Size 128 GiB on Standard SSD. This will be mounted at [path]``/var/cache``



// I guess you do this in your Azure instance
=== Network Configuration

Created a separate private network.
The IP range is `10.0.0.0/24`.
// Where do you configure this?
The {productname} Server will have the internal IP Address `10.0.0.4` and will be reachable from the outside with IP `10.89.171.101`.
The firewall has been configured to only allow inbound for port `22`, `80`, and `443` to IP Address `10.0.0.4`.
So if other servers are added in this network they cannot be reached from outside the network.
Outbound is open from the private network.
// Was does this mean?
This should be restricted for other server in this private network.



== Configuring SUSE Manager Server



=== Before You Begin



==== Network

. DHCP must not set the host name.
Check [path]``/etc/sysconfig/network/dhcp`` if `DHCLIENT_SET_HOSTNAME` is set to [literal]``no``.
Change it if needed:
+

----
DHCLIENT_SET_HOSTNAME="no"
----
. Create the needed DNS Zones in Azure first.
For more information, see the documentation from Microsoft Azure.

. On the command line, add the system to the [path]``/etc/hosts`` file; replace [literal]``<ip_address>`` with the IP address of the server:
+

// hostname -i?
----
echo "<ip_address> $(hostname -f) $(hostname)" >> /etc/hosts
----



==== Disks

For this configuration three extra data disks have been added.
For Azure it is recommended not to use LVM.
If more disk space is needed a disk can be extended in the Azure portal, and then the filesystem can be expanded with [command]``xfs_growfs``.

. Disk [path]``/dev/sda`` is partitioned in 4 partitions containing the OS.
. Disk [path]``/dev/sdb`` is the temporary storage disk and should not be used.
. Disk [path]``/dev/sdc`` will contain [path]``/var/lib/pgsql``
. Disk [path]``/dev/sdd`` will contain [path]``/var/spacewalk``
. Disk [path]``/dev/sde`` will contain [path]``/var/cache``

To create the need data disks use use this command sequence on the command line:

----
for d in sdc sdd sde; do
  parted --script /dev/$d mklabel gpt mkpart primary xfs 0% 100%
  mkfs.xfs /dev/${d}1
done
mkdir /cachetmp
mount /dev/sde1 /cachetmp
cp -a /var/cache/* /cachetmp/
umount /cachetmp
echo "$(blkid /dev/sdc1|awk -F " " '{ print $2 }') /var/lib/pgsql xfs defaults,noatime 0 0" >> /etc/fstab
echo "$(blkid /dev/sdd1|awk -F " " '{ print $2 }') /var/spacewalk xfs defaults,noatime 0 0" >> /etc/fstab
echo "$(blkid /dev/sde1|awk -F " " '{ print $2 }') /var/cache     xfs defaults,noatime 0 0" >> /etc/fstab
mkdir -p /var/spacewalk
mount /var/spacewalk
chown -R wwwrun:root /var/spacewalk
mount /var/lib/pgsql
chown -R postgres:postgres /var/lib/pgsql
mv /var/cache /var/cache.old
mkdir /var/cache
mount /var/cache
rm -r /var/cache.old
----



=== Registration

To be able to install updates, register {productname} against {scc} (SCC).
On the command line, enter (replace [literal]``<mail-address>`` and [literal]``<registration code>`` with your data:

----
SUSEConnect -e <mail-address> -r <registration code>
----



=== Install Additional Packages

With [command]``zypper``, install the following packages:

----
zypper -n in spacecmd mlocate sysstat
----



=== Update the Server with the Latest Patches and Reboot

Apply the latest updates and reboot the server:

----
zypper -n up -l
reboot
----



