[[troubleshooting-local-cert]]
= Troubleshooting Local Issuer Certificates

Cause: Some older bootstrap scripts will will create a link to the local certificate in the wrong place, cause problems with zypper returning an ``Unrecognized error`` about the local issuer certificate.
Consequence:  cause problems with zypper returning an ``Unrecognized error`` about the local issuer certificate.
Fix: ensure that the link to the local issuer certificate has been created in [path]``/etc/ssl/certs/``, and consider updating your bootstrap scripts.
Result: The link to the local certificate is now in the correct location, and zypper operates as expected.




Some older bootstrap scripts will will create a link to the local certificate in the wrong place, which can cause problems with zypper returning an ``Unrecognized error`` about the local issuer certificate.
In this case, ensure that the link to the local issuer certificate has been created in [path]``/etc/ssl/certs/``, and consider updating your bootstrap scripts.
