[[troubleshooting-register-clones]]
= Troubleshooting Registering Cloned Minions






This chapter provides guidance on registering cloned systems with SUSE Manager.
This includes both Salt and Traditional clients.
For more information, see https://www.novell.com/support/kb/doc.php?id=7012170.

[[bp.chapt.suma3.troubleshooting.registering.cloned.salt.systems]]
== Registering Cloned Salt Minions

.Procedure: Registering a Cloned Salt Minion with SUSE Manager
. Clone your system (for example using the existing cloning mechanism of your favorite Hypervisor)
+
.Quick Tips
NOTE: Each step in this section is performed on the cloned system, this procedure does not manipulate the original system, which will still be registered to SUSE Manager.
The cloned virtual machine should have a different UUID from the original (this UUID is generated by your hypervisor) or SUSE Manager will overwrite the original system data with the new one.
+

. Make sure your machines have different hostnames and IP addresses, also check that /etc/hosts contains the changes you made and the correct host entries.

The next step you take will depend on the Operating System of the clone.

The following scenario can occur after on-boarding cloned Salt minions.
If after accepting all cloned minion keys from the onboarding page and you see only one minion on the System Overview page, this is likely due to these machines being clones of the original and using a duplicate machine-id.
Perform the following steps to resolve this conflict based on OS.

.Procedure: SLES 12 Registering Salt Clones
. SLES 12: If your machines have the same machine ids then delete the file on each minion and recreate it:
+

----
# rm /etc/machine-id
# rm /var/lib/dbus/machine-id
# dbus-uuidgen --ensure
# systemd-machine-id-setup
----


.Procedure: SLES 11 Registering Salt Clones
. SLES 11: As there is no systemd machine id, generate one from dbus:
+

----
# rm /var/lib/dbus/machine-id
# dbus-uuidgen --ensure
----


If your machines still have the same minion id then delete the minion_id file on each minion (FQDN will be used when it is regenerated on minion restart):

----
# rm /etc/salt/minion_id
----


Finally delete accepted keys from Onboarding page and system profile from SUSE Manager, and restart the minion with:

----
# systemctl restart salt-minion
----


You should be able to re-register them again, but each minion will use a different '/etc/machine-id' and should now be correctly displayed on the System Overview page.

[[bp.chapt.suma3.troubleshooting.registering.cloned.traditional.systems]]
== Registering Cloned Traditional Systems


This section provides guidance on troubleshooting cloned traditional systems registered via bootstrap.

.Procedure: Registering a Cloned System with SUSE Manager (Traditional Systems)
. Clone your system (using your favorite hypervisor.)
+
.Quick Tips
NOTE: Each step in this section is performed on the cloned system, this procedure does not manipulate the original system, which will still be registered to SUSE Manager.
The cloned virtual machine should have a different UUID from the original (this UUID is generated by your hypervisor) or SUSE Manager will overwrite the original system data with the new one.
+

. Change the Hostname and IP addresses, also make sure /etc/hosts contains the changes you made and the correct host entries.
. Stop rhnsd daemon with:
+

----
# /etc/init.d/rhnsd stop
----
+
or alternatively:
+

----
# rcrhnsd stop
----
. Stop osad with:
+

----
# /etc/init.d/osad stop
----
+
or alternatively:
+

----
# rcosad stop
----
. Remove the osad authentication configuration file and the systemid with:
+

----
# rm -f /etc/sysconfig/rhn/{osad-auth.conf,systemid}
----


The next step you take will depend on the Operating System of the clone.

.Procedure: SLES 12 Registering A Cloned Traditional System
. {empty}
+
If your machines have the same machine IDs then delete the file on each client and recreate it:
+

----
# rm /etc/machine-id
# rm /var/lib/dbus/machine-id
# dbus-uuidgen --ensure
# systemd-machine-id-setup
----
. Remove the following credential files:
+

----
# rm  -f /etc/zypp/credentials.d/{SCCcredentials,NCCcredentials}
----
. Re-run the bootstrap script. You should now see the cloned system in SUSE Manager without overwriting the system it was cloned from.


.Procedure: SLES 11 Registering A Cloned Traditional System
. Continued from section 1 step 5:
+

----
# suse_register -E
----
+
(--erase-local-regdata, Erase all local files created from a previous executed registration.
This option make the system look like never registered)
. Re-run the bootstrap script. You should now see the cloned system in SUSE Manager without overwriting the system it was cloned from.


.Procedure: SLES 10 Registering A Cloned Traditional System
. Continued from section 1 step 5:
+

----
# rm -rf /etc/{zmd,zypp}
----
. {empty}
+

----
# ¡¡¡¡¡ everthing in /var/lib/zypp/ except /var/lib/zypp/db/products/ !!!!!
# check whether this command works for you
# rm -rf /var/lib/zypp/!(db)
----
. {empty}
+

----
# rm -rf /var/lib/zmd/
----
. Re-run the bootstrap script. You should now see the cloned system in SUSE Manager without overwriting the system it was cloned from.


.Procedure: RHEL 5,6 and 7
. Continued from section 1 step 5:
+

----
# rm  -f /etc/NCCcredentials
----
. Re-run the bootstrap script. You should now see the cloned system in SUSE Manager without overwriting the system it was cloned from.
