[[troubleshooting-corrupt-repos]]
= Troubleshooting Corrupt Repositories

Cause:  the information in [path]``/var/cache/rhn/repodata/sles{sles-version}-{sp-version-l}-updates-x86_64`` becomes out of date
Consequence: cause problems with updating the server.
Fix: . Remove all files from [path]``/var/cache/rhn/repodata/sles{sles-version}-{sp-version-l}-updates-x86_64``
. Regenerate the file with `spacecmd softwarechannel_regenerateyumcache sles{sles-version}-{sp-version-l}-updates-x86_64`
Result: Updates the cache file  and allows the server to be updated.



If the information in [path]``/var/cache/rhn/repodata/sles{sles-version}-{sp-version-l}-updates-x86_64`` becomes out of date, it will cause problems with updating the server.
The repository data file can be regenerated using the [command]``spacemd`` command:


.Procedure: Rebuild repodata file
. Remove all files from [path]``/var/cache/rhn/repodata/sles{sles-version}-{sp-version-l}-updates-x86_64``
. Regenerate the file with `spacecmd softwarechannel_regenerateyumcache sles{sles-version}-{sp-version-l}-updates-x86_64`
