[[troubleshooting-taskomatic]]
= Troubleshooting Taskomatic
////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

If Taskomatic crashes or has failed to terminate a process, repository metadata regeneration can be prevented from happening regularly.
When this occurs, package updates will be available in the {webui}, but will not appear on the client, and attempts to update the client will fail.
To correct this, determine if any processes are running, or if a crash could have occurred.
When you have located the problematic process, the metadata can be regenerated and synchronization occurs as expected.

.Procedure: Resolving Taskomatic Problems

. On the server, check the [path]``/var/log/rhn/rhn_taskomatic_daemon.log`` file to determine if any processes are still running or a crash occurred.
. Restart taskomatic:
+
----
service taskomatic restart
----
+
