[[tuning-changelogs]]
= Tuning Changelogs

Some packages have a long list of changelog entries.
This data is downloaded by default, but it is not always useful information to keep.
In order to limit the amount of changelog metadata which is downloaded and to save disk space, you can put a limit on how many entries to keep on disk.

This configuration option is in the [filename]``/etc/rhn/rhn.conf`` configuration file.
The parameter defaults to [systemitem]``0``, which means unlimited.

----
java.max_changelog_entries = 0
----

If you set this parameter (remember you need to restart the services with `spacewalk-services restart), it will come into effect only for new packages when they are synchronized.

You might like to delete the cached data to remove older data.

[IMPORTANT]
====
Deleting cached data can take a long time.
Depending on the number of channels you have and the amount of data to be deleted, it can potentially take several hours.
The task is run in the background by Taskomatic, so you can continue to use {productname} while the operation completes, however you should expect some performance loss.
====

You can delete cached data from the command line, using the SQL interface:

----
# spacewalk-sql -i
yourdatabase=# DELETE FROM rhnPackageRepodata;
yourdatabase=#  INSERT INTO rhnRepoRegenQueue (id, CHANNEL_LABEL, REASON, FORCE)
(SELECT sequence_nextval('rhn_repo_regen_queue_id_seq'),
        C.label,
        'package summary modification',
        'Y'
   FROM rhnChannel C);
yourdatabase=#  \q
----
