[[tuning-changelogs]]
= Tuning Client Discovery

By default, {productname} expects you to register individual clients, either manually or through automation.
However, it is possible to configure {productname} to discover clients according to certain criteria.



== PXE Boot Discovery

You can use Cobbler to discover any client that boots using PXE.
When a client PXE boots, Cobbler would serve them an operating system image.
The client would then be recorded in the database with an inventory of their hardware, until they are ready to be installed.



=== Network Range Discovery

You can use the Salt scanning roster function, and the ``salt-ssh`` command to find all clients that connect from within a given IP range.
This will identify all clients within the IP range that have an open SSH port, and can be accessed with known SSH credentials.

For more information about the Salt scanning roster feature, see link:https://docs.saltstack.com/en/latest/ref/roster/all/salt.roster.scan.html[].



== Virtual Host Discovery

In virtualized environments that use a virtual host manager, the VHM can be configured to discover running virtual machines.
Discovered clients are than matched to existing system profiles.
This method can also be used to detect sclients that have not been onboarded.
