= Uyuni 4.0 Documentation
include::ROOT:partial$entities.adoc[]

== What is {productname}?

{productname} is a solution for organizations that require absolute control over maintenance and package deployment on their servers.
{productname} enables you to manage large sets of Linux systems and keep them up to date, with automated software management, asset management, and system provisioning.
{productname} allows you to maintain a high level of security while effectively managing system life-cycle requirements.

{productname} uses _Salt_ to provide event-driven configuration and management control.
The Salt-master orchestrates thousands of Salt-minions ({productname} Clients) using remote execution.

{productname} offers seamless management of {sle}, {rhel}, Ubuntu, CentOS, and Scientific Linux client systems and is fully compatible with Red Hat Satellite Server.

== Available Documentation

The following documentation is available for {productname} version {productnumber}.

[cols=2*, options="header"]
|===
| Available Documentation |

| xref:installation:install-intro.adoc[Installation Guide]    | xref:client-configuration:client-cfg-overview.adoc[Client Configuration Guide]
| xref:upgrade:upgrade-migration-overview.adoc[Upgrade Guide] | xref:reference:intro.adoc[Reference Guide]
| xref:administration:intro.adoc[Administration Guide]        | xref:salt:intro.adoc[Salt Guide]
|xref:architecture:arch-salt-overview.adoc[Architecture] |
|===


