[[installation-general-requirements]]
= General Requirements


Before you begin your installation, check that your environment meets these requirements:

* Current {scc} organization credentials
* Access to installation media
* Your environment meets the hardware and networking requirements
* You understand the supported client operating systems


This section contains more information on each of these requirements.

[NOTE]
====
{productname} {productnumber} is based on {slsa} {sles-version} {sp-version} as the host operating system.
{productname} comes with a dedicated support period.
Long Term Service Pack Support (LTSS) for {sles-version} cannot be added to {productname}.
It is also not possible to use {slsa} for SAP as a base for {productname} for a longer lifecycle.
====



[[install.scc-register]]
== Obtain Your SUSE Customer Center Credentials

You will need to create an account with {scc} before you install {sls} and {productname}.
To obtain your {scc} credentials:

[[creating.scc.account.mgr]]
.Procedure: Obtaining Your SCC Organization Credentials
. Navigate to https://scc.suse.com/login in your Web browser.
. Log in to your SCC account, or follow the prompts to create a new account.
. If you have not yet done so, click [guimenu]``Connect to an organization`` and type or search for your organization.
. Click [guimenu]``Manage my organizations`` and select your organization from the list by clicking on the organization name.
. Click the [guimenu]``Organization`` tab, and then select the [guimenu]``Organization Credentials`` tab.
. Record your login information for use during {productname} setup.

Depending on your organization's setup, you might also need to activate your subscription, using the [guimenu]``Activate subscriptions`` menu.



[[install.media]]
== Obtain the Unified Installer

From {slsa}{nbsp}15{nbsp}SP1, {susemgr} {productnumber} Server and Proxy is available as a base product, and can be installed with the {slsa} Unified Installer.

ifeval::[{suma-content} == true]
Therefore you do not require a separate registration code for {slsa}, only for {susemgr} Server or Proxy.
endif::[]

If not already done, download the {slsa} Unified Installer (version {nbsp}15{nbsp}SP1 or higher) from https://www.suse.com/products/server/download/[SUSE Linux Enterprise Server - Media Download].
With the Unified Installer you can install many SLE-based base products such as {slsa}, {sled}, {slsa} for SAP Applications, or {susemgr}.

//TODO: What about Uyuni?



[[installation-general-supportedbrowsers]]
== Supported Browsers for the {susemgr} {webui}

In order to use the {webui} to manage your {susemgr} environment, you will need to ensure you are running an up to date web browser.

{susemgr} is supported on:

* Latest Firefox browser shipped with {slsa}
* Latest Chrome browser on all operating systems
* Latest Edge browser shipped with Windows

Windows Internet Explorer is not supported.
The {productname} {webui} will not render correctly under Windows Internet Explorer.
