[[installation-intro]]
= Introduction
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]


{productname} provides absolute control over your Linux environment.
System administrators often have tens, hundreds, or even thousands of client machines they need to look after, all of which require ongoing maintenance, updates, and lifecycle management.
{productname} allows you to manage all your Linux clients in one place, with one easy-to-understand dashboard.

{productname} can be integrated with your network infrastructure in multiple ways, and most tasks can be automated, with reports issued so you always know the status of your client machines.
Because {productname} allows you to manage large numbers of systems and automatically keep them up to date, it helps to improve overall security, and provides extensive asset management and provisioning capability.

{productname} is fully compatible with Red Hat Satellite Server and offers seamless management of both {sle} and {rhel} client systems.
