[[install-vm]]
= Installing the virtual machine environment
// Antora entities
ifndef::backend-pdf[]
include::ROOT:partial$entities.adoc[]
endif::[]

// PDF entities
ifdef::backend-pdf[]
include::_partials/entities.adoc[]
endif::[]


// This chapter needs a complete overhaul --LKB 2019-04-02

[[quickstart.sect.kvm.settings]]
== Virtual Machine Manager (virt-manager) Settings

This chapter provides the required (KVM) settings for installation of {sle} Just Enough Operating System (JeOS) 12 as the base for {productname}.
A kernel virtual machine (KVM) combined with Virtual Machine Manager (_virt-manager_) will be used as a sandbox for your first installation.

.{suse}Virtualization Guide
[TIP]
====
For more information on virtualization, see: https://www.suse.com/documentation/sles-12/singlehtml/book_virt/book_virt.html[SUSE Linux Enterprise Virtualization Guide]
====

You will require a new virtual machine, which you can create using [systemitem]``virt-manager``.
When you create your new virtual machine, ensure it meets the hardware requirements at xref:hardware-requirements.adoc[].


.{suse} Virtualization Guide
[TIP]
====
For more information on virtualization, see: https://www.suse.com/documentation/sles-12/singlehtml/book_virt/book_virt.html[SUSE Linux Enterprise Virtualization Guide]
====

[[jeos.kvm.settings]]
== JeOS KVM Settings

Create three additional virtual disks required for the {productname} storage partitions.

.Procedure: Creating the Required Partitions with KVM
. Create a new virtual machine using the downloaded JeOS KVM image and select menu:Import existing disk image[] .
. Configure RAM and number of CPUs, according to xref:hardware-requirements.adoc[].
. Name your KVM machine and select the menu:Customize configuration before install[] check box.
. Select the btn:[Add Hardware] button and create three new virtual disks with the following specifications.
These disks will be partitioned and mounted in <<proc.jeos.susemgr.prep>>.
+

[cols="1,1,1", options="header"]
|===
| VirtIO Storage Disks | Name
| VirtIO Disk 2        | spacewalk
| VirtIO Disk 3        | pgsql
| VirtIO Disk 4        | swap
|===

. Click menu:Begin Installation[] and your new VM will boot from the JeOS image.

Proceed through the basic JeOS installation prompts until you reach the command line.

.Root Password
[TIP]
====
During the basic installation prompts you are asked to enter the root password.
Select a strong password and then in the next message box btn:[Confirm root Password].
====

[[jeos.susemgr.prep]]
== Preparing JeOS for {productname}

[[proc.jeos.susemgr.prep]]
.Procedure: Preparing JeOS for {productname} Installation
. Register with SCC:
+

----
SUSEConnect -e<EMAIL_ADDRESS> -r<SUSE_MANAGER_CODE>
----
. Add {productname} repositories:
+

----
SUSEConnect -p SUSE-Manager-Server/<productnumber>/x86_64 -r<SUSE_MANAGER_CODE>
----
. Install [package]#yast2-storage# with all required dependencies (approx. 40 packages, 30 MB when installed).
This basic administration package is required for preparing storage partitions:
+

----
zypper in -t package yast2-storage
----
. Partition and mount the virtual disks at the following locations using {yast} Partitioner ([command]``yast2 disk``).
+

[cols="1,1,1,1", options="header"]
|===
| VirtIO Storage Disks | Name                     | File System Type
| VirtIO Disk 2        | [path]``/var/spacewalk`` | XFS
| VirtIO Disk 3        | [path]``/var/lib/pgsql`` | XFS
| VirtIO Disk 4        | [path]``swap``           | swap
|===

. If you are using a version older than {susemgr}{nbsp}3.2 check [path]``/etc/fstab`` for correctness as follows:
Remove or comment out this mount point entry for [path]``/var/lib/pgsql/`` in the [path]``/etc/fstab`` file:
+

----
/var/lib/pgsql btrfs subvol=@/var/lib/pgsql 0 0
----
+

[WARNING]
.Remove [path]``pgsql`` from the fstab Configuration File
====
If you do not remove the [path]``/var/lib/pgsql/`` line from fstab the first time you shut down the server you will lose your database because of duplicated entries in the fstab file.
====
+

. Exit the partitioner and install the {productname} pattern:
+

----
zypper in -t pattern suma_server
----

For proceeding with {productname} setup, see xref:quickstart3_chap_sumasetup_with_yast.adoc#suma.setup.with.yast[SUSE Manager Setup].
