[[installation-network-requirements]]
= Network Requirements

This section details the networking and port requirements for {productname}.

Fully Qualified Domain Name (FQDN)::
The {productname} server must resolve its FQDN correctly.
If the FQDN cannot be resolved, it can cause serious problems in a number of different components.
+
For more information about configuring the hostname and DNS, see https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-network.html#sec-network-yast-change-host.

Hostname and IP Address::
To ensure that the {productname} domain name can be resolved by its clients, both server and client machines must be connected to a working DNS server.
You also need to ensure that reverse lookups are correctly configured.
+
For more information about setting up a DNS server, see https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-dns.html.

Using a Proxy When Installing from {sle} Media::
If you are on an internal network and do not have access to {scc}, you can set up and use a proxy during installation.
+
For more information about configuring a proxy for access to {scc} during a {sle} installation, see https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-boot-parameters.html#sec-boot-parameters-advanced-proxy.


.Naming Your Server
[IMPORTANT]
====
The hostname of {productname} must not contain uppercase letters as this may cause _jabberd_ to fail.
Choose the hostname of your {productname} server carefully.
Although changing the server name is possible, it is a complex process and unsupported.
====


In a production environment, {productname} server and its clients should always use a firewall.
This table gives an overview of required ports, to be used when you are setting up your firewall rules.


[[tab.install.ports.server1]]
.Required Server Ports
[cols="1,1,1", options="header"]
|===
| Port | Protocol | Description
| 22   | TCP      | SSH
| 67   | UDP      | DHCP
| 69   | UDP      | TFTP, used to support PXE services
| 80   | TCP      | HTTP, used in some bootstrap cases
| 123  | UDP      | NTP time service
| 443  | TCP      | HTTPS, used for {webui}, client, Proxy server, and API traffic
| 4505 | TCP      | Salt, used by the Salt-master to accept communication requests from clients
| 4506 | TCP      | Salt, used by the Salt-master to accept communication requests from clients
| 5222 | TCP      | XMPP client, used for communications with the [systemitem]``osad`` daemon on traditional client systems
| 5269 | TCP      | XMPP server, used for pushing actions to {susemgrproxy}
|===

For more information on disconnected setup and port configuration, see:

* xref:administration:disconnected-setup.adoc#client-cfg-reg-with-bootstrap-disconnected[]

* xref:installation:ports.adoc[]
