[[installation-network-requirements]]
= Network Requirements

This section details the networking and port requirements for {productname}.

Fully Qualified Domain Name (FQDN)::
The {productname} server must resolve its FQDN correctly or cookies will not work properly on the WebUI.
+
For more information about configuring the hostname and DNS, see link:https://www.suse.com/documentation/sles-15/book_sle_admin/data/sec_network_yast.html#sec_network_yast_change_host

Hostname and IP Address::
To ensure that the {productname} domain name can be resolved by its clients, both server and client machines must be connected to a working DNS server. Also reverse lookups need to be correctly configured.
+
For more information about setting up a DNS server, see link:https://www.suse.com/documentation/sles-15/book_sle_admin/data/cha_dns.html

Using a Proxy When Installing from {sle} Media::
If you are on an internal network and do not have access to {scc}, you can set up and use a proxy during installation.
+
For more information about configuring a proxy for access to {scc} during a {sle} installation, see link:https://www.suse.com/documentation/sles-15/book_sle_deployment/data/sec_boot_parameters_advanced.html#sec_boot_parameters_advanced_proxy


.Naming Your Server
[IMPORTANT]
====
The hostname of {productname} must not contain uppercase letters as this may cause _jabberd_ to fail.
Choose the hostname of your {productname} server carefully.
Although changing the server name is possible, it is a complex process and unsupported.
====


In a production environment, {productname} server and its clients should always use a firewall.
This table gives an overview of required ports, to be used when you are setting up your firewall rules.


[[tab.install.ports.server1]]
.Required Server Ports
[cols="1,1,1", options="header"]
|===
| Port | Protocol | Description
| 22   | TCP      | SSH
| 67   | UDP      | DHCP
| 69   | UDP      | TFTP, used to support PXE services
| 80   | TCP      | HTTP, used in some bootstrap cases
| 123  | UDP      | NTP time service
| 443  | TCP      | HTTPS, used for {webui}, client, Proxy server, and API traffic
| 4505 | TCP      | Salt, used by the Salt-master to accept communication requests from clients
| 4506 | TCP      | Salt, used by the Salt-master to accept communication requests from clients
| 5222 | TCP      | XMPP client, used for communications with the [systemitem]``osad`` daemon on traditional client systems
| 5269 | TCP      | XMPP server, used for pushing actions to {susemgrproxy}
|===

For more information on disconnected setup and port configuration, see:

* xref:client-configuration:disconnected-setup.adoc#client-cfg-reg-with-bootstrap-disconnected[]

* xref:installation:ports.adoc[]
