[[public-cloud-setup]]

Because {productname} is preinstalled in Public Cloud images, there is no installation step required.
However, {productname} Server needs to be registered with {scc} to receive updates.

To register your system, you have two options:

** Run [command]``yast2 scc`` and enter your {scc} credentials.
** Run [command]``SUSEConnect -e your_email -r your_registration_code`` as user `root` in a shell.

Registering {productname} Server will also enable all required {sle} Modules, with the exception of the Public Cloud Module. {productname} Server instances in the Public Cloud require packages from the Public Cloud Module and it is recommended to enable the module to keep Public Cloud specific packages up to date. In the YaST2 `Software Repositores` management module select `Add` then select `Extensions and Modules from Registration Server...` and from the list of available extensions select `Public Cloud Module` from the list of extensions. Alternatively, you can add the module via the command line using [command]``SUSEConnect -p sle-module-public-cloud/15.1/x86_64``. The Public Cloud Module can only be registered after the initial registration is completed.

When the installation procedure has finished, you can check that you have all the required modules by using the [command]``SUSEConnect --status-text`` command at a command prompt.
For {susemgr} Server, the expected modules are:

* {sls} Basesystem Module
* Python 2 Module
* Server Applications Module
* Web and Scripting Module
* SUSE Manager Server Module
* Public Cloud Module

= Public Cloud Setup

{productname} Proxy does not have administration access to the {webui}.
It can be managed through its parent {productname} Server.

[NOTE]
.Admin Account in Public Clouds
====
In public clouds, the setup procedure will automatically create an administrator account. See <<pubclouds-credentials>>.
====

=== Public Clouds Account Credentials

The user name automatically created for the administrator in public clouds is `admin`.

[cols="1,1,1", options="header"]
|===
|
          Amazon EC2

|
          Google Compute Engine

|
          Microsoft Azure


|

[replaceable]``Instance-ID``
|

[replaceable]``Instance-ID``
|

[replaceable]``Instance-Name``**-suma**
|===

The current value for the [replaceable]``Instance-ID`` or [replaceable]``Instance-Name`` in case of the Azure Cloud, can be obtained from the public cloud Web console or from within a terminal session as follows:

** Obtain instance id from within Amazon EC2 instance
+

----
$ ec2metadata --instance-id
----
** Obtain instance id from within Google Compute Engine instance
+

----
$ gcemetadata --query instance --id
----
** Obtain instance name from within Microsoft Azure instance
+

----
$ azuremetadata --instance-name
----

After logging in through the {productname} Server {webui}, *change* the default password.