[[public-cloud-registration]]
= Registration in the Public Clouds

Since {productname} is preinstalled in Public Cloud images, there is no installation step required. However, {productname} Server needs to be registered with {scc} in order to receive updates.

To register your system, you have two options:

** Run [command]``yast2 scc`` and enter your {scc} credentials.
** Run [command]``SUSEConnect -e your_email -r your_registration_code`` as user `root` in a shell.

Registering {productname} Server will also enable all required {sle} Modules, with the exception of the Public Cloud Module. {productname} Server instances in the Public Cloud require packages from the Public Cloud Module and it is recommended to enable the module to keep Public Cloud specific packages up to date. In the YaST2 `Software Repositores` management module select `Add` then select `Extensions and Modules from Registration Server...` and from the list of available extensions select `Public Cloud Module` from the list of extensions. Alternatively, you can add the module via the command line using [command]``SUSEConnect -p sle-module-public-cloud/15.1/x86_64``. The Public Cloud Module can only be registered after the initial registration is completed.

When the installation procedure has finished, you can check that you have all the required modules by using the [command]``SUSEConnect --status-text`` command at a command prompt.
For {susemgr} Server, the expected modules are:

* {sls} Basesystem Module
* Python 2 Module
* Server Applications Module
* Web and Scripting Module
* SUSE Manager Server Module
* Public Cloud Module
