= Filters

.Procedure: Add a new Filter to a Content Lifecycle Project

. In the {productname} {webui}, navigate to menu:Content Lifecycle Management[Filters], and click btn:[Create Filter]
. In the [guimenu]``name`` field, enter a descriptive name for your filter.
. In the [guimenu]``filter type`` field, choose the desired entity to target with the filter criteria.
. In the [guimenu]``name criteria`` field, enter the entire or a slice of the name of the target entity to filter.
. In the [guimenu]``deny`` checkbox mark the flag to apply a ``deny`` criteria, unmark it to apply an ``allow`` criteria instead.
. Click the btn:[Create] button to create your filter and return to the filter list.
. In the {productname} {webui}, navigate to menu:Content Lifecycle Management[Projects].
. Click btn:[Attach/Detach Filters].
. In the [guimenu]``Filters`` dialog, mark the checkbox of the filter to be applied in the project.
. Click the btn:[Save] button.
. Continue creating filters and attach them to projects as desired.
You can create a new filter from within a project by the btn:[Create new Filter] in the [guimenu]``Filters`` dialog of a project as well.
