[[retail-formulas]]
= Introduction to Retail Formulas


Formulas are pre-written Salt states, that are used to configure your {smr} installation.

You can use the {productname} {webui} to apply common {productname} formulas.
For the most commonly used formulas, see xref:salt:formulas-intro.adoc[].

All formulas must be accurately configured for your {smr} installation to function correctly.
If you are unsure of the correct formula configuration details, run the [command]``retail_branch_init`` command before you begin to create the recommended formula configuration.
You can then manually edit the formulas as required.

== {smr} Branch Server Formulas

Branch servers are configured using formulas. Formulas can be configured using {susemgr} {webui}, and {susemgr} XMLRPC API.
To fully configure {smr} environment, following formulas need to be enabled and configured for branch server:

* Branch Network Formula, see xref:salt:formula-branchnetwork.adoc[]
* Dhcpd Formula, see xref:salt:formula-bind.adoc[]
* Bind Formula, see xref:salt:formula-dhcpd.adoc[]
* PXE Formula, see xref:salt:formula-pxe.adoc[]
* TFTP Formula, see xref:salt:formula-tftpd.adoc[]
* Vsftp Formula, see xref:salt:formula-vsftpd.adoc[]

Optionally [systemitem]``Image Synchronization Formula`` can be enabled and configured as well, see xref:salt:formula-imagesync.adoc[].

[IMPORTANT]
====
It is very easy to misconfigure formulas that may result in branch not working properly.
Due to the generic nature of formulas it is difficult to do overall validation.
When in doubt, configure branch server by {smr} provided command line utilities and then fine tune individual formulas, see xref:retail:retail-install-setup.adoc[].
====

.State and Formula Name Collisions
[WARNING]
====
If a formula uses the same name as an existing Salt state, the two names will collide, and could result in the formula being used instead of the state.
Always check the names of states and formulas to avoid name collisions.
====

When you have made changes to your formula, ensure you apply the highstate.
The highstate propagates your changes to the appropriate services.
