[[_art.suma.install.zsystems]]
= {susemgr} on IBM {zsystems}
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

== Introduction


This best practice guide is intended for z/VM administrators responsible for operating the IBM {zseries}
Mainframe.
The goal of this guide is to lead an z/VM administrator trained on normal {zseries}
operating protocols through the installation of {susemgr}
onto an existing mainframe system.
The intent of this article is not to cover the variety of hardware configuration profiles available on {zseries}
but instead to provide a foundational overview of the procedure and requirements necessary for a successful {susemgr}
server deployment. 

== Base System Requirements


The z/VM administrator should acquire and prepare the following resources for a successful {susemgr}
installation. {susemgr}{productnumber}
is delivered as an extension.
These sections will provide you with the minimum and recommended system requirements for {susemgr}
.
The base system for {susemgr}
 {productnumber}
is SLES {sles-version}{sp-version}
. 

[cols="1,1", options="header"]
|===
| 
       
        Hardware
       
      
| 
       
        Recommended Hardware
       
      


|

IBM Systems 
|

* IBM zEnterprise System z196 _(z196)_
* IBM zEnterprise System z114 _(z114)_
* IBM zEnterprise EC12 _(zEC12)_
* IBM zEnterprise EC12 _(zEC12)_
* IBM zEnterprise BC12 _(zBC12)_
* IBM z13 _(z13)_
* LinuxOne Rockhopper 
* LinuxOne Emperor 


|

RAM 
|

_Split memory requirements across available RAM, VDISK and
        swap to suit your environment. On a production system the ratio of
        physical memory to VDISK will need to be re-evaluated based on the
        number of clients which will be supported._

Minimum 5{nbsp}
 GB+ for test server _(3 GB RAM + 2 GB VDISK
        Swap)_

Minimum 16{nbsp}
GB+ for base installation 

Minimum 32{nbsp}
GB+ for a production server 

|

Free Disk Space 
|

Minimum 100{nbsp}
GB for root partition 

Minimum 50{nbsp}
GB for [replaceable]``/var/lib/pgsql``

Minimum 50{nbsp}
GB per {suse}
product + 100 GB per Red Hat product [replaceable]``/var/spacewalk``

|

Network Connection 
|

* OSA Express Ethernet _(including Fast and Gigabit Ethernet) _
* HiperSockets or Guest LAN 
* 10 GBE, VSWITCH 
* RoCE _(RDMA over Converged Ethernet)_

The following interfaces are still included but no longer supported: 

* CTC _(or virtual CTC)_
* IP network interface for IUCV 

|===

.Media Requirements
* {sle} {sles-version}{sp-version} Installation Media for IBM {zsystems} : 
+ 
https://www.suse.com/products/server/download/


== Additional Requirements


There are a few additional resource requirements you will need to prepare before installing the {susemgr}
extension on your system.
This section overviews these requirements. 

The guest z/VM should be provided with a static IP address and hostname as these cannot be easily changed after initial setup.
The hostname should contain less than 8 characters. 

For more information on {susemgr}
additional requirements, see https://www.suse.com/documentation/suse-manager-3/book_suma_best_practices/data/mgr_conceptual_overview.html. 

You are required to calculate sufficient disk storage for {susemgr}
before running: 

----
yast2 susemanager_setup
----


The following information will help fulfill these requirements. 

.{susemgr}Default Volume Groups and Disk Space
[WARNING]
====
By default the file system of {susemgr}
including the embedded database and patch directories will reside within the root volume.
While adjustments are possible once installation has completed it becomes the administrators responsibility to specify and monitor these adjustments. 

If your {susemgr}
runs out of disk space, this can have a severe impact on its database and file structure.
Preparing storage requirements in accordance with this section will aid in preventing these harmful effects. 

_{suse}
 technical services will not be able to provide support for
    systems suffering from low disk space conditions as this can have an effect
    on an entire system and therefore becomes unresolvable. A full recovery is
    only possible with a previous backup or a new {susemgr}

    installation._
====

.Required Storage Devices
* An additional disk is required for database storage. This should be an [systemitem]``zFCP`` or [systemitem]``DASD`` device as these are preferred for use with [systemitem]``HYPERPAV`` . This disk should fulfill the following requirements 
+ 
At least 50 GB for 
+

----
/var/lib/pgsql
----
+
Minimum 50{nbsp}
GB per SUSE product + 100 GB per Red Hat product 
+

----
/var/spacewalk
----


== SLES {sles-version}{sp-version} Installation and the {susemgr} Extension


This section covers the installation of {susemgr}{productnumber}
as an extension to SLES {sles-version}{sp-version}
. 

For more information on deploying SLES {sles-version}{sp-version}
on your hardware, see https://www.suse.com/documentation/sles-12/book_sle_deployment/data/cha_zseries.html. 

During installation of SLES {sles-version}{sp-version}
select {susemgr}
as an extension. 

After rebooting you will need to set up the additional storage required for [path]``/var/spacewalk``
 and [path]``/var/lib/pgsql``
 and swap space using the yast partitioner tool.
This step is _required_ before running [command]``yast2
   susemanager_setup``. 

After configuring the storage requirements, having executed a {yast}
online update and completed a full system reboot, run {susemgr}
setup to finalize the {susemgr}
installation on your {zsystems}
mainframe: 

----
{prompt.root}
yast2 susemanager_setup
----


This completes the installation of {susemgr}
on your {zseries}
.
For more information on beginning management with {susemgr}
, see <<_suma.setup.with.yast.sumasetup>>. 