:sectnums!:

[appendix]
[[_advanced.topics.app.ay.example_simple]]
= Minimalist {ay} Profile for Automated Installations and Useful Enhancements


The following {ay}
profile will install a {sls}
system with all default installation options including a default network configuration with DHCP.
After the installation is completed, a bootstrap script located on the {susemgr}
server will be executed in order to register the freshly installed system with {susemgr}
.
You need to adjust the IP address of the {susemgr}
server, the name of the bootstrap script and the {rootuser}
password according to your needs in the following lines: 

----
<user>
 ...
 <username>root</username>
 <user_password>`linux`
</user_password>
</user>

<location>http://`192.168.1.1`
/pub/bootstrap/`my_bootstrap.sh`
</location>
----


The complete {ay}
file: 

----
<?xml version="1.0"?>
<!DOCTYPE profile>
<profile xmlns="http://www.suse.com/1.0/yast2ns"
         xmlns:config="http://www.suse.com/1.0/configns">
 <general>
  <mode>
   <confirm config:type="boolean">false</confirm>
  </mode>
 </general>
 <networking>
  <keep_install_network config:type="boolean">true</keep_install_network>
 </networking>
 <software>
  <install_recommended config:type="boolean">true</install_recommended>
   <patterns config:type="list">
    <pattern>base</pattern>
   </patterns>
 </software> 
 <users config:type="list">
  <user>
   <encrypted config:type="boolean">false</encrypted>
   <fullname>root</fullname>
   <gid>0</gid>
   <home>/root</home>
   <password_settings>
    <expire></expire>
    <flag></flag>
    <inact></inact>
    <max></max>
    <min></min>
    <warn></warn>
   </password_settings>
   <shell>/bin/bash</shell>
   <uid>0</uid>
   <username>root</username>
   <user_password>linux</user_password>
  </user>
 </users>
 <scripts>
  <init-scripts config:type="list">
   <script>
    <interpreter>shell</interpreter>
    <location>http://192.168.1.1/pub/bootstrap/my_bootstrap.sh</location>
   </script>
  </init-scripts>
 </scripts>
</profile>
----


Use the following enhancement fragment to add child channels: 

----
<add-on>
 <add_on_products config:type="list">
  <listentry>
   <ask_on_error config:type="boolean">true</ask_on_error>
   <media_url>http://$c_server/ks/dist/child/`channel-label`
/`distribution-label`
</media_url>
   <name>$c_name</name>
   <product>$c_product</product>
   <product_dir>/</product_dir>
  </listentry>
...
 </add_on_products>
</add-on>
----


Replace [replaceable]``channel-label`` and [replaceable]``distribution-label`` with actual labels such as `sles11-sp1-updates-x86_64` and `sles11-sp2-x86_64` (the distribution label must correspond to the Autoinstallable Distribution!), and set the variables (``$c_server``, etc.) according to your environment.
For information about variables, see <<_s4_sm_system_kick_dist_variables>>. 

.Add the Updates Channel
[IMPORTANT]
====
It is required to add the updates tools channel to the <add-on> AutoYaST snippet section.
This ensures your systems are provided with an up-to-date version of libzypp.
Without the inclusion of an updates channel you will encounter 400 errors.
See the following example where the (DISTRIBUTION_NAME) is replaced with the name of the autoinstallation distribution created previously in menu:Systems[Autoinstallation > Distributions]

----
<listentry>
     <ask_on_error config:type="boolean">true</ask_on_error>
     <media_url>http://$redhat_management_server/ks/dist/child/sles12-sp2-updates-x86_64/(DISTRIBUTION_NAME)</media_url>
     <name>sles12 sp2 updates</name>
     <product>SLES12</product>
     <product_dir>/</product_dir>
  </listentry>
----
====

:sectnums: