[[_advanced.topics.cobbler]]
= Cobbler
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

(((Cobbler)))

(((cobbler)))

(((Koan)))

(((koan)))

{susemgr}
features the Cobbler server that allows administrators to centralize their system installation and provisioning infrastructure.
Cobbler is an installation server that provides various methods of performing unattended system installations, whether it be server, workstation, or guest systems in a full or para-virtualized setup. 

Cobbler offers several tools to assist in pre-installation guidance, automated installation file management, installation environment management, and more.
This section explains supported features of Cobbler, which include: 

* installation environment analysis using the [command]``cobbler check`` command, 
* multi-site installation server configuration with [command]``cobbler replicate``, 
+
ifdef::showremarks[]
#emap: RH dropped replicate. Keep or not?#
endif::showremarks[]
* virtual machine guest installation automation with the [command]``koan`` client-side tool, 
* building installation ISOs with PXE-like menus using the [command]``cobbler buildiso`` command for {susemgr} systems with x86_64 architecture. 
+
ifdef::showremarks[]
#emap: added in RH docs. Valid for SUSE as well? There's also a new section on
     building ISOs with Cobbler at the end.#
endif::showremarks[]


For more detailed upstream documentation on Cobbler, see http://cobbler.github.io/manuals/. 

.Supported Cobbler Functions
[IMPORTANT]
====
{suse}
only support those Cobbler functions that are either listed within our formal documentation or available via the Web Interface and API. 
====

[[_advanced.topics.cobbler.reqs]]
== Cobbler Requirements


To use Cobbler as a PXE boot server, follow these guidelines: 

* For system installation with PXE, you must have a TFTP server installed and configured. By default, {susemgr} installs such a TFTP server. 
* To PXE boot systems for installation, you must either set up a DHCP server for Cobbler PXE booting or have access to your network's DHCP server. Edit [path]``/etc/dhcp.conf`` to change [option]``next-server`` to the hostname or IP address of your Cobbler server. 


.Correct Hostname Configuration
[IMPORTANT]
====
When onboarding bare metal systems using the pxe-default-image, it's important to ensure all systems to be on-board have unique hostnames.
Otherwise, if you later assign a provisioning profile to it, the new configuration file will overwrite the configuration settings for any system with the duplicate hostname.
Cobbler uses hostnames as a unique key for each system. 
====

[[_advanced.topics.cobbler.reqs.settings]]
=== Configuring Cobbler with /etc/cobbler/settings


Cobbler configuration is mainly done in the [path]``/etc/cobbler/settings``
 file.
With the default settings unchanged, Cobbler runs as intended.
All configurable settings are explained in detail in the [path]``/etc/cobbler/settings``
 file with regard to how they affect functionality of Cobbler and whether it is recommended for users to adjust values to their environment. 

.Supported Languages
[NOTE]
====
If {susemgr}
complains about language '``en``' was not found within the list of supported languages available at [path]``/usr/share/YaST2/data/languages``
, remove the lang in [path]``/etc/cobbler/settings``
 or add a proper value such as ``en_US``. 

For background info, see https://www.suse.com/support/kb/doc?id=7018334. 
====

[[_advanced.topics.cobbler.req.dhcp]]
=== Cobbler and DHCP


Cobbler supports bare-metal automated installation of systems configured to perform network boots using a PXE boot server.
To properly implement a Cobbler installation server, administrators need to either have administrative access to the network's DHCP server or set up DHCP on the Cobbler server itself. 

[[_advanced.topics.cobbler.reqs.dhcp.notmanaged]]
==== Configuring an Existing DHCP Server


If you have a DHCP server deployed on another system in the network, you will need administrative access to the DHCP server to edit the DHCP configuration file so that it points to the Cobbler server and PXE boot image. 

As {rootuser}
on the DHCP server, edit the [path]``/etc/dhcpd.conf``
 file and append a new class with options for performing PXE boot installation.
For example: 

----
allow booting;
allow bootp; <1>
class "PXE" <2>
{
match if substring(option vendor-class-identifier, 0, 9) = "PXEClient"; <3>
next-server 192.168.2.1; <4>
filename "pxelinux.0"; <5>
}
----


Step by step explanation: 
<1>
       Enable network booting with the [systemitem]``bootp``
 protocol.
      
<2>
       Create a class called ``
PXE``
.
      
<3>
       A system configured to have PXE first in its boot priority identifies
       itself as ``PXEClient``
.
      
<4>
       As a result, the DHCP server directs the system to the Cobbler server at
       ``192.168.2.1``
.
      
<5>
       The DHCP server retrieves the [path]``pxelinux.0``
 bootloader
       file.
      

[[_advanced.topics.cobbler.reqs.dhcp.kvm]]
==== Setting up PXE Boot in KVM


Not necessarily for production, but for lab or demo environments you can alternativly set up PXE boot in KVM.
Such a configuration can replace the `next-server` setting on a DHCP server explained in <<_advanced.topics.cobbler.reqs.dhcp.notmanaged>>.
To edit the network XML description with [command]``virsh``, proceed as follow: 


. Produce an XML dump of the current description: 
+

----
{prompt.root}
virsh net-dumpxml --inactive network > network.xml
----
. Open the XML dump file (here [path]``network.xml`` ) with a text editor and add a `bootp` statement within the `<dhcp>` element: 
+

----
<bootp file='/pxelinux.0' server='192.168.100.153'/>
----
. Install the edited description: 
+

----
{prompt.root}
virsh net-define network.xml
----


Or try the `net-edit` subcommand that does some error checking. 

[[_at.cobbler.bootp.kvm]]
.Minimal Network XML Description for KVM
====
----
<network>
  <name>default</name>
  <uuid>1da84185-31b5-4c8b-9ee2-a7f5ba39a7ee</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:29:59:18'/>
  <domain name='default'/>
  <ip address='192.168.100.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.100.128' end='192.168.100.254'/>
      <bootp file='/pxelinux.0' server='192.168.100.153'/> <6>
</dhcp>
  </ip>
</network>
----
<6>
        `bootp`
 statement that directs to the PXE server.
       
====

[[_advanced.topics.cobbler.reqs.tftp]]
=== Xinetd and TFTP

{susemgr}
uses the [daemon]``atftpd``
 daemon, but it can also operate with Xinetd/TFTP.
The [daemon]``atftpd``
 is installed by default as the recommended method for providing PXE services.
Usually, you do not have to change its configuration, but if you have to, use the {yast}
 Sysconfig Editor. 

Xinetd is a daemon that manages a suite of services, including TFTP, the FTP server used for transferring the boot image to a PXE client. 

To configure TFTP, you must first enable the service via Xinetd.
To do this, edit the [path]``/etc/xinetd.d/tftp``
 file as {rootuser}
 and change the [option]``disable = yes`` line to ``disable =
    no``. 

Before TFTP can serve the [path]``pxelinux.0``
 boot image, you must start the Xinetd service.
Start {yast}
 and use menu:System[Services Manager]
 to configure the [daemon]``Xinetd``
 daemon. 

[[_advanced.topics.cobbler.reqs.sync.tftp]]
=== Syncing TFTP Contents to SUSE Manager Proxies


It is possible to sync cobbler generated TFTP contents to {susemgr}
Proxies to perform PXE booting via these proxies. 

==== Installation


On the {susemgr}
Server, install the package [systemitem]``susemanager-tftpsync``
: 

----
{prompt.root}
zypper install susemanager-tftpsync
----


On the {susemgrproxy}
systems, install the package [systemitem]``susemanager-tftpsync-recv``
: 

----
{prompt.root}
zypper install susemanager-tftpsync-recv
----

==== Configuring {susemgrproxy}


Execute [path]``configure-tftpsync.sh``
 on the {susemgrproxy}
 systems. 

This setup script asks for hostnames and IP addresses of the {susemgr}
server and the proxy.
Additionally, it asks for the `tftpboot` directory on the proxy.
For more information, see the output of [command]``configure-tftpsync.sh --help``. 

==== Configuring {susemgr} Server


Execute [path]``configure-tftpsync.sh``
 on {susemgr}
 Server: 

----
{prompt.root}
configure-tftpsync.sh proxy1.example.com proxy2.example.com
----


Execute [command]``cobbler sync`` to initially push the files to the proxy systems.
This will succeed if all listed proxies are properly configured. 

.Changing the List of Proxy Systems
[NOTE]
====
You can call [command]``configure-tftpsync.sh`` to change the list of proxy systems.
You must always provide the full list of proxy systems. 
====

.Reinstalling a Configured Proxy
[NOTE]
====
In case you reinstall an already configured proxy and want to push all files again you must remove the cache file [path]``/var/lib/cobbler/pxe_cache.json``
 before you can call [command]``cobbler sync`` again. 
====

==== Requirements


The {susemgr}
Server must be able to access the {susemgrproxy}
systems directly.
Push via proxies is not possible. 

[[_advanced.topics.cobbler.reqs.service]]
=== Syncing and Starting the Cobbler Service


Before starting the cobbler service, run a check on the cobbler service to make sure that all the prerequisites are configured according to the organization's needs with the command: [command]``cobbler check``. 

If content, start the {susemgr}
server with the following command: 

----
{prompt.root}
/usr/sbin/spacewalk-service start
----

[WARNING]
====
Do not start or stop the [command]``cobblerd`` service independent of the {susemgr}
 service.
Doing so may cause errors and other issues. 

Always use [command]``/usr/sbin/spacewalk-service`` to start or stop {susemgr}
. 
====

[[_advanced.topics.cobbler.adddistro]]
== Adding a Distribution to Cobbler


If all Cobbler prerequisites have been met and Cobbler is running, you can use the Cobbler server as an installation source for a distribution: Make installation files such as the kernel image and the initrd image available on the Cobbler server.
Then add a distribution to Cobbler, using either the Web interface or the command line tools. 

For information about creating and configuring {ay}
or Kickstart distributions from the {susemgr}
interface, refer to <<_ref.webui.systems.autoinst.distribution>>. 

To create a distribution from the command line, use [command]``cobbler`` as follows: 

----
{prompt.root}
cobbler distro add --name=`string`
--kernel=`path`
--initrd=`path`
----


The [option]``--name=``[replaceable]``string`` option is a label used to differentiate one distribution choice from another (for example, ``sles12server``). 

The [option]``--kernel=``[replaceable]``path`` option specifies the path to the kernel image file. 

The [option]``--initrd=``[replaceable]``path`` option specifies the path to the initial ram disk (initrd) image file. 

[[_advanced.topics.cobbler.addprofile]]
== Adding a Profile to Cobbler


Once you have added a distribution to Cobbler, you can add profiles. 

Cobbler profiles associate a distribution with additional options like {ay}
or Kickstart files.
Profiles are the core unit of provisioning and there must be at least one Cobbler profile for every distribution added.
For example, two profiles might be created for a Web server and a desktop configuration.
While both profiles use the same distribution, the profiles are for different installation types. 

For information about creating and configuring Kickstart and {ay}
profiles in the {susemgr}
interface, refer to <<_ref.webui.systems.autoinst.profiles>>. 

Use [command]``cobbler`` to create profiles on the command line: 

----
{prompt.root}
cobbler profile add --name=string --distro=string [--kickstart=url] \
  [--virt-file-size=gigabytes] [--virt-ram=megabytes]
----


The [option]``--name=``[replaceable]``string`` is the unique label for the profile, such as `sles12webserver` or ``sles12workstation``. 

The [option]``--distro=``[replaceable]``string`` option specifies the distribution that will be used for this particular profile.
For adding distributions, see <<_advanced.topics.cobbler.adddistro>>. 

The [option]``--kickstart=``[replaceable]``url`` option specifies the location of the Kickstart file (if available). 

The [option]``--virt-file-size=``[replaceable]``gigabytes`` option allows you to set the size of the virtual guest file image.
The default is 5 GB. 

The [option]``--virt-ram=``[replaceable]``megabytes`` option specifies how many MB of physical RAM a virtual guest can consume.
The default is 512 MB. 

[[_advanced.topics.cobbler.addsystem]]
== Adding a System to Cobbler


Once the distributions and profiles for Cobbler have been created, add systems to Cobbler.
System records map a piece of hardware on a client with the cobbler profile assigned to run on it. 

[NOTE]
====
If you are provisioning via [command]``koan`` and PXE menus alone, it is not required to create system records.
They are useful when system-specific Kickstart templating is required or to establish that a specific system should always get specific content installed.
If a client is intended for a certain role, system records should be created for it. 
====


For information about creating and configuring automated installation from the {susemgr}
interface, refer to <<_s4_sm_system_details_kick>>. 

The following command adds a system to the Cobbler configuration: 

----
{prompt.root}
cobbler system add --name=string --profile=string \
  --mac-address=AA:BB:CC:DD:EE:FF
----


The [option]``--name=``[replaceable]``string`` is the unique label for the system, such as `engineering_server` or ``frontoffice_workstation``. 

The [option]``--profile=``[replaceable]``string`` specifies the name of one of the profiles added in <<_advanced.topics.cobbler.addprofile>>. 

The [option]``--mac-address=``[replaceable]``AA:BB:CC:DD:EE:FF`` option allows systems with the specified MAC address automatically being provisioned to the profile associated with the system record when they are being installed. 

For more options, such as setting hostname or IP addresses, refer to the Cobbler manpage ([command]``man cobbler``). 

[[_advanced.topics.cobbler.templates]]
== Using Cobbler Templates


The {susemgr}
Web interface facilitates creating variables for use with Kickstart distributions and profiles.
To create a Kickstart profile variable, refer to <<_s4_sm_system_kick_details_variables>>. 

Kickstart variables are part of an infrastructural change in {susemgr}
to support templating in Kickstart files.
Kickstart templates are files describing how to build actual Kickstart files rather than creating specific Kickstarts. 

These templates are shared by various profiles and systems that have their own variables and corresponding values.
These variables modify the templates and a template engine parses the template and variable data into a usable Kickstart file.
Cobbler uses an advanced template engine called Cheetah that provides support for templates, variables, and snippets. 

Advantages of using templates include: 

* Robust features that allow administrators to create and manage large amounts of profiles or systems without duplication of effort or manually creating Kickstarts for every unique situation. 
* While templates can become complex and involve loops, conditionals and other enhanced features and syntax, you can keep them simple by creating Kickstart files without such complexity. 


[[_advanced.topics.cobbler.templates.usage]]
=== Using Templates


Kickstart templates can have static values for certain common items such as PXE image file names, subnet addresses, and common paths such as [path]``/etc/sysconfig/network-scripts/``
.
However, templates differ from standard Kickstart files in their use of variables. 

For example, a standard Kickstart file may have a networking section similar to the following: 

----
{prompt.root}
network --device=eth0 --bootproto=static --ip=192.168.100.24 \
  --netmask=255.255.255.0 --gateway=192.168.100.1 --nameserver=192.168.100.2
----


In a Kickstart template file, the networking section would rather look like this: 

----
{prompt.root}
network --device=$net_dev --bootproto=static --ip=$ip_addr \
  --netmask=255.255.255.0 --gateway=$my_gateway --nameserver=$my_nameserver
----


These variables will be substituted with the values set in your Kickstart profile variables or in your system detail variables.
If the same variables are defined in both the profile and the system detail, then the system detail variable takes precedence. 

[NOTE]
====
The template for the autoinstallation has syntax rules, using punctuation symbols.
To avoid clashes, they need to be properly treated. 
====


In case the autoinstallation scenario contains any shell script using variables like ``$(example)``, its content should be escaped by using the backslash symbol: ``\$(example)``. 

If the variable named `example` is defined in the autoinstallation snippet, the templating engine will evaluate `$example` with its content.
If there is no such variable, the content will be left unchanged.
Escaping the kbd:[$]
 symbol will prevent the templating engine to perform its evaluation as an internal variable.
Long scripts or strings can be escaped by wrapping them with the `\#raw` and `\#end raw` directives.
For example: 

----
#raw
#!/bin/bash
for i in {0..2}; do
 echo "$i - Hello World!"
done
#end raw
----


Also, pay attention to similar scenarios like the following: 

----
#start some section (this is a comment)
echo "Hello, world"
#end some section (this is a comment)
----


Any line with a kbd:[#]
 symbol followed by a whitespace is treated as a comment and is therefore not evaluated. 

For more information about Kickstart templates, refer to the Cobbler project page at: 

https://fedorahosted.org/cobbler/wiki/KickstartTemplating

[[_advanced.topics.cobbler.templates.snippets]]
=== Kickstart Snippets


If you have common configurations across all Kickstart templates and profiles, you can use the Snippets feature of Cobbler to take advantage of code reuse. 

Kickstart snippets are sections of Kickstart code that can be called by a [option]``$SNIPPET()`` function that will be parsed by Cobbler and substituted with the contents of the snippet. 

For example, you might have a common hard drive partition configuration for all servers, such as: 

----
clearpart --all
part /boot --fstype ext3 --size=150 --asprimary
part / --fstype ext3 --size=40000 --asprimary
part swap --recommended

part pv.00 --size=1 --grow

volgroup vg00 pv.00
logvol /var --name=var vgname=vg00 --fstype ext3 --size=5000
----


Save this snippet of the configuration to a file like [path]``my_partition``
 and place the file in [path]``/var/lib/cobbler/snippets/``
, where Cobbler can access it. 

Use the snippet by calling the [option]``$SNIPPET()`` function in your Kickstart templates.
For example: 

----
$SNIPPET('my_partition')
----


Wherever you invoke that function, the Cheetah parser will substitute the function with the snippet of code contained in the [path]``my_partition``
 file. 

[[_advanced.topics.cobbler.koan]]
== Using Koan


Whether you are provisioning guests on a virtual machine or reinstalling a new distribution on a running system, koan works in conjunction with Cobbler to provision systems. 

[[_advanced.topics.cobbler.koan.virt]]
=== Using Koan to Provision Virtual Systems


If you have created a virtual machine profile as documented in <<_advanced.topics.cobbler.addprofile>>, you can use [command]``koan`` to initiate the installation of a virtual guest on a system. 

For example, create a Cobbler profile with the following command: 

----
{prompt.root}
cobbler add profile --name=virtualfileserver \
  --distro=sles12-x86_64-server --virt-file-size=20 --virt-ram=1000
----


This profile is for a fileserver running {sls}{nbsp}
12 with a 20 GB guest image size and allocated 1 GB of system RAM. 

To find the name of the virtual guest system profile, run the following [command]``koan`` command: 

----
{prompt.root}
koan --server=hostname --list-profiles
----


This command lists all the available profiles created with [command]``cobbler
    profile add``. 

Start creating the image file and the installation of the virtual guest system: 

----
{prompt.root}
koan --virt --server=cobbler-server.example.com \
  --profile=virtualfileserver --virtname=marketingfileserver
----


The command specifies that a virtual guest system be created from the Cobbler server (hostname [server]``cobbler-server.example.com``
) using the `virtualfileserver` profile.
The [option]``virtname`` option specifies a label for the virtual guest, which by default is the system's MAC address. 

Once the installation of the virtual guest is complete, it can be used as any other virtual guest system. 

[[_advanced.topics.cobbler.koan.reinstall]]
=== Using Koan to Reinstall Running Systems

[command]``koan`` can replace a still running system with a new installation from the available Cobbler profiles by executing the following command __on the system to be reinstalled__: 

----
{prompt.root}
koan --replace-self --server=hostname --profile=name
----


This command, running on the system to be replaced, will start the provisioning process and replace its own system using the profile in [option]``--profile=name`` on the Cobbler server specified in [option]``--server=hostname``. 

[[_advanced.topics.cobbler.buildiso]]
== Building ISOs with Cobbler


Some environments might lack PXE support.
The cobbler buildiso command provides functionality to create a boot ISO image containing a set of distributions and kernels, and a menu similar to PXE network installations.
Define the name and output location of the boot ISO using the [option]``--iso`` option. 

.ISO Build Directory
[NOTE]
====
Depending on Cobbler related systemd settings (see [path]``/usr/lib/systemd/system/cobblerd.service``
) writing ISO images to public [path]``tmp``
 directories will not work. 
====

----
{prompt.root}
cobbler buildiso --iso=/path/to/boot.iso
----


The boot ISO includes all profiles and systems by default.
Limit these profiles and systems using the [option]``--profiles`` and [option]``--systems`` options. 

----
{prompt.root}
cobbler buildiso --systems="system1,system2,system3" \
  --profiles="profile1,profile2,profile3"
----

[NOTE]
====
Building ISOs with the [command]``cobbler buildiso`` command is supported for all architectures except the {zsystems}
 architecture. 
====

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]