[[bp.chap.suma.backup]]
= Database Backup and Restoration
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:linkattrs:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Enterprise Linux
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname: 
:susemgr: SUSE Manager
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:saltversion: 2018.3.0
:webui: WebUI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
:ay: AutoYaST
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images


Backing up SUSE Manager can be done in several ways.
Regardless of the method chosen, the associated database also needs to be backed up.

== Files and Directories Requiring Backup


The following files and directories should be backed up:

* The location of your SUSE Manager database, for example: [path]``/var/spacewalk/db-backup``
* [path]``/etc/sysconfig/rhn/``
* [path]``/etc/rhn/``
* [path]``/etc/sudoers``
* [path]``/srv/www/htdocs/pub/``
* [path]``/var/spacewalk/packages/1`` (/2, /3, for each additional organization using custom RPMs)
* [path]``/root/.gnupg/``
* [path]``/root/ssl-build/``
* [path]``/etc/dhcp.conf``
* [path]``/srv/tftpboot/``
* [path]``/etc/cobbler/``
* [path]``/var/lib/cobbler/``
* [path]``/var/lib/rhn/kickstarts/``
* [path]``/srv/www/cobbler``
* [path]``/root/.ssh`` (Backup is required when using ssh tunnel or ssh push. Keep in mind if you need to reinstall the server and you do not have a copy of the id-susemanager key saved, you must perform a mgr-ssh-push-init again for all clients.lsls)
* Directories containing your custom data (scripts, kickstart profiles, autoyast, custom rpms, etc) should be included in the backup.
* If you have mountpoints to ISO's needed for distributions, these ISOs and the [path]``/etc/fstab`` should be part of your backup.

{suse}
recommends backing up the entire [path]``/var/spacewalk/``
 tree.
In case of failure, this will save you lengthy download/resync time.
Since [path]``/var/spacewalk/``
 (more specifically [path]``/var/spacewalk/packages/NULL/``
) is primarily a duplicate of the package repository, it can be regenerated with [command]``mgr-sync``.

If you are running SUSE Manager in a disconnected setup [path]``/var/spacewalk/``__must__ be backed up.

Backing up only these files and directories requires reinstalling the {susemgr}
RPMs and re-registering {susemgr}
.
In addition, packages need to be resynchronized using the [command]``mgr-sync`` tool.
Finally, you have to reinstall the [path]``/root/ssl-build/rhn-org-httpd-ssl-key-pair-MACHINE_NAME-VER-REL.noarch.rpm``
.

Another method is to back up all the files and directories mentioned above but reinstall the {susemgr}
without re-registering it.
During the installation, cancel or skip the registration and SSL certificate generation sections.

The most comprehensive method is to back up the entire machine.
This saves time in downloading and reinstalling but requires additional disk space and backup time.

[NOTE]
====
Regardless of the backup method used, when restoring {susemgr}
from a backup, you must run the following command to schedule the recreation of search indexes the next time the [command]``rhn-search`` service is started:

----
rcrhn-search cleanindex
----
====

[[config.suma.database.smdba]]
== Administering the Database with smdba

The [command]``smdba`` tool is used for managing a local PostgreSQL database.
It allows you to back up and restore your database, and manage backups.
It can also be used to check the status of your database, and perform administration tasks, such as restarting.

[NOTE]
====
The [command]``smdba`` tool works with local PostgreSQL databases only, it will not work with remotely accessed databases, or Oracle databases.
====

[IMPORTANT]
====
The [command]``smdba`` tool requires [command]``sudo`` access, in order to execute system changes.
Ensure you have enabled [command]``sudo`` access for the [username]``admin`` user before you begin, by checking the [path]``/etc/sudoers`` file for this line:

----
admin   ALL=(postgres) /usr/bin/smdba
----

====


[[bp.sect.backup.smdba.admin]]
== Administering Your Database with smdba

Check the runtime status of your database with the [command]``smdba db-status`` command.
This command will return either ``online`` or ``offline``:

----
smdba db-status
Checking database core...       online
----

To check the full connection to the database, use the [command]``smdba db-check`` command.
Depending on your environment, this command will report on the status of listeners, in addition to connectivity status.

----
smdba db-check
----

Starting and stopping the database can be performed with [command]``smdba db-start`` and [command]``smdba db-stop``

----
smdba db-start
Starting core...       done
----

----
smdba db-stop
Stopping the SUSE Manager database...
Stopping core:         done
----

[[bp.sect.backup.smdba.performbackup]]
== Database Backup with smdba


The [command]``smdba`` tool performs a continuous archiving backup.
This backup method combines a log of every change made to the database during the current session, with a more traditional series of backup files.
When a crash occurs, the database state is first restored from the most recent backup file on disk, then the log of the current session is replayed, to bring the database back to a current state.
A continuous archiving backup can be performed whether the database and {productname} is running (hot) or shut down (cold).

This method of backing up is stable and generally creates consistent snapshots, however it can take up a lot of storage space.
Ensure you have at least three times the current database size of space available for backups.
You can check your current database space usage by navigating to [path]``/var/lib/pgsql/`` and running [command]``df -h``.



=== Performing a Cold Database Backup


A cold, or offline, database backup occurs when the service is completely shut down at the time of the backup.
This method can reduce the risk of incomplete backups, but does require significant downtime.
We recommend that you perform a cold backup after initial installation and configuration, and then at weekly or monthly intervals during operation, but rely on hot backups for daily or hourly intervals.
Additionally, we recommend that you consider backing up your database to an NFS share location, which can itself be backed up.


<!-- TODO: Fixme LKB -->
When using smdba, you should never require a cold backup.
You may perform a cold backup once after initial SUSE Manager installation and configuration. {suse}
recommends creating a full-backup once a month or weekly and an additional incremental backup for single days.
Moving [path]``/var/spacewalk``
 to an NFS share that is centrally backed-up, will save you alot of time when a restore is required.
The NFS share may also be used during the migration from SUSE Manager 2.1 to SUSE Manager 3.


<!-- TODO: Fixme LKB -->
.Procedure: Performing a Cold Backup
. Step 1
. Step 2
. FIXME



=== Performing a Hot Database Backup


A hot, or dynamic, database backup occurs when the service continues normal operation while the backup occurs.
This method can sometimes result in data loss or conflicts, and can effect database performance while the operation is underway.
However, hot backups also enable much finer-grained archives, and can often result in seamless restoration from failure, in addition to maintaining uptime.
We recommend that you perform a hot backup on daily or hourly intervals, to serve as a more complete record between cold backups.
Additionally, we recommend that you consider backing up your database to an NFS share location, which can itself be backed up.


.Procedure: Performing a Hot Backup
. Allocate permanent storage space for your backup. In this procedure, we will be using an NFS share located at [path]``/var/spacewalk/``.
This will become a permanent target for your backup, so ensure it will remain accessible by your server at all times.
. In your backup location, create a directory for the backup:
+

----
sudo -u postgres mkdir /var/spacewalk/db-backup
----
+

Or, as root:
+

----
install -d -o postgres /var/spacewalk/db-backup
----

. Ensure you have the correct permissions set on the backup location:
+

----
chown postgres:postgres /var/spacewalk/db-backup
----
+

. To run a backup for the first time, run the [command]``smdba backup-hot`` command with the [command]``enable`` option set.
This will create the backup in the specified directory, and restart the database:
+

----
smdba backup-hot --enable=on --backup-dir=/var/spacewalk/db-backup
----
+

. After the initial hot backup has occurred, you can run subsequent hot backups without requiring a database restart:
+

----
smdba backup-hot --backup-dir=/var/spacewalk/db-backup
----
+

. Check that the backup files exist in the [path]``/mnt/backup/database`` directory, to ensure that your backup has been successful.



[[smdba.automatic.backup.with.cron]]
== Automatic Backup with cron


It is important to ensure your SUSE Manager database is backed up within a regularly defined schedule.
You can do this with a cron job.
The following procedure describes this process.

.Database Backup Space Requirements
[IMPORTANT]
====
For all forms of database backup (hot, cold, or automated via cron) you must have at least 3 times the amount of space of the current database.
Check current database space usage with [command]``df -h`` on [path]``/var/spacewalk/``
.
====

.Procedure: Automatic Backup with cron
. If you have not created a backup directory do so now:
+

----
# mkdir /var/spacewalk/db-backup
----
. Set the correct user and rights permissions to the directory:
+

----
# chown -R postgres:postgres /var/spacewalk/db-backup
----
+

----
# chmod 700 /var/spacewalk/db-backup
----
. Add the following line to the cron job at [path]``/etc/cron.d/db-backup-mgr`` :
+

----
0 2 * * * root /usr/bin/smdba backup-hot --enable=on --backup-dir=/var/spacewalk/db-backup
----


[[config-smdb.restore-backup]]
== Restoring a Database Backup


Use [command]``smdba backup-restore`` to restore to an earlier point in time.
To restore the backup, proceed as follows:


. Shutdown the database:
+

----
smdba db-stop
----
. Start the restore process:
+

----
smdba backup-restore start
----
. Restart the database:
+

----
smdba db-start
----
. Run [command]``spacewalk-data-fsck`` to check if there are differences between the RPMs and the database.


The above steps can be combined with:

----
smdba backup-restore force
----


In this case it will select the most recent backup and purge the rest.
Every time you create a new backup, it also purges the previous backups.

.Restoring the Most Recent Backup Only
[NOTE]
====
Because [command]``smdba`` makes automatic running database backups, it allows restoration of only the most recent backup, which includes merging of current archive logs.
====

[[config-smdb.archivelog]]
== Archive Log Settings


In {susemgr}
with an embedded database, archive logging is enabled by default.
This feature allows the database management tool [command]``smdba`` to perform hot backups.

With archive log enabled, even more data is stored on the hard disk:

* Postgresql maintains a limited number of archive logs. Using the default configuration, approx. 64 files with a size of 16 MiB are stored.


Creating a user and syncing the channels:

* SLES12-SP2-Pool-x86_64
* SLES12-SP2-Updates-x86_64
* SLE-Manager-Tools12-Pool-x86_64-SP2
* SLE-Manager-Tools12-Updates-x86_64-SP2


Postgresql will generate an additional ~1 GB of data.
So it is important to think about a backup strategy and create a backups in a regular way.

Archive logs are stored at:

* [path]``/var/lib/pgsql/data/pg_xlog/`` (postgresql)


[[config-smdb.spaces]]
== Retrieving an Overview of Occupied Database Space


Database administrators may use the subcommand [command]``space-overview`` to get a report about occupied table spaces, for example:

----
smdba space-overview
SUSE Manager Database Control. Version 1.5.2
Copyright (c) 2012 by SUSE Linux Products GmbH


Tablespace  | Size (Mb) | Avail (Mb) | Use %
------------+-----------+------------+------
postgres    | 7         | 49168      | 0.013
susemanager | 776       | 48399      | 1.602
----


The following command is available for Postgresql.
For a more detailed report, use the [command]``space-tables`` subcommand.
It lists the table and its size, for example:

----
smdba space-tables
SUSE Manager Database Control. Version 1.5.2
Copyright (c) 2012 by SUSE Linux Products GmbH


Table                                 | Size
--------------------------------------+-----------
public.all_primary_keys               | 0 bytes
public.all_tab_columns                | 0 bytes
public.allserverkeywordsincereboot    | 0 bytes
public.dblink_pkey_results            | 0 bytes
public.dual                           | 8192 bytes
public.evr_t                          | 0 bytes
public.log                            | 32 kB
...
----

== Moving the Database


It is possible to move the database to another location.
For example if your database storage space is running low.
The following procedure will guide you through moving the database to a new location for use by SUSE Manager.

.Procedure: Moving the Database
. The default storage location for {susemgr} is: [path]``/var/lib/pgsql/`` . You would like to move it, for example to: [path]``/storage/postgres/`` . To begin, stop the running database with:
+

----
# rcpostgresql stop
----
+
Shutdown running spacewalk services with:
+

----
# spacewalk-service stop
----
. Copy the current working directory structure with the following syntax:
+

----
cp [OPTION]... SOURCE... DIRECTORY
----
+
using the [option]``-a, --archive`` option.
For example:
+

----
# cp -ar /var/lib/pgsql/ /storage/postgres/
----
+
This command will copy the contents of [path]``/var/lib/pgsql/``
to [path]``/storage/postgres/pgsql/``
.
+
IMPORTANT: The contents of the /var/lib/pgsql needs to remain the same or the SUSE Manager database may malfunction.
You also should ensure there is enough available disk space.
+

. Mount the new database directory with:
+

----
# mount /storage/postgres/pgsql
----
. Make sure ownership is `postgres:postgres` and not `root:root` by changing to the new directory and running the following command:
+

----
/var/lib/pgsql/ # cd /storage/postgres/pgsql/
/storage/postgres/pgsql/ # l
total 8
drwxr-x---  4 postgres postgres   47 Jun  2 14:35 ./
----
. Add the new database mount location to your servers fstab by editing  [path]``etc/fstab`` .
. Start the database with:
+

----
# rcpostgresql start
----
+
Start spacewalk-services with:
+

----
# spacewalk-service start
----


== Recovering from a Crashed Root Partition


This section provides guidance on restoring your server after its root partition has crashed.
This section assumes you have setup your server similar to the procedure explained in Getting Started guide with separate partitions for the database and for channels mounted at [path]``/var/lib/pgsql``
 and [path]``/var/spacewalk/``
.

.Procedure: Recovering from a Crashed Root Partition
. Start by installing SLES12 SP2 and the SUSE Manager Extension. Do not mount the [path]``/var/spacewalk`` and [path]``/var/lib/pgsql`` partitions.
. Once installation of SUSE Manager has completed shutdown services with [command]``spacewalk-service shutdown`` and the database with [command]``rcpostgresql stop``.
. Mount your [path]``/var/spacewalk`` and [path]``/var/lib/pgsql`` partitions and restore the directories listed in section one.
. Start SUSE Manager services and the database with [command]``spacewalk-services start`` and [command]``rcpostgresql start``
. SUSE Manager should now operate normally without loss of your database or synced channels.


== Database Connection Information


The information for connecting to the SUSE Manager database is located in [path]``/etc/rhn/rhn.conf``
:

----
db_backend = postgresql
db_user = susemanager
db_password = susemanager
db_name = susemanager
db_host = localhost
db_port = 5432
db_ssl_enabled =
----
