[[_bp.expanded_support]]
= Expanded Support
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .


In the following sections find information about Red Hat and Centos clients. 

[[_bp.expanded_support.resclients]]
== Managing RES Clients


The following sections provide guidance on managing Red Hat Expanded Support clients, this includes Salt minions and traditional systems. 

[[_bp.expanded_support.resclients.server]]
=== Server Configuration for RES Channels


This section provides guidance on server configuration for RES Channels provided by {suse}
. 

* Minimum of 8 GB RAM and at least two physical or virtual CPUs. Taskomatic will use one of these CPUs. 
* Taskomatic requires of minimum of 3072 MB RAM. This should be set in [path]``/etc/rhn/rhn.conf`` : 
+

----
taskomatic.java.maxmemory=3072
----
* Provision enough disk space. [path]``/var/spacewalk`` contains all mirrored RPMs. For example, RES 6 x86_64 channels require 90 GB and more. 
* LVM or an NFS mount is recommended. 
* Access to RHEL 5/6/7 Subscription Media. 


.Access to RHEL Media or Repositories
[WARNING]
====
Access to Red Hat base media repositories and RHEL installation media is the responsibility of the user.
Ensure that all your RHEL systems obtain support from RHEL or all your RHEL systems obtain support from {suse}
.
If you do not follow these practices you may violate terms with Red Hat. 
====

[[_bp.expanded_support.resclients.tips]]
=== RES Channel Management Tips


This section provides tips on RES channel management. 

* The base parent distribution RES channel per architecture contains zero packages. No base media is provided by {suse} . The RHEL media or installation ISOs should be added as child channels of the RES parent channel. 
* The RES and tools channels are provided by SUSE Customer Center (SCC) using [command]``mgr-sync``. 
* It can take up to 24 hours for an initial channel synchronization to complete. 
* When you have completed the initial synchronization process of any RES channel it is recommended to clone the channel before working with it. This provides you with a backup of the original synchronization. 


=== Mirroring RHEL Media into a Channel


The following procedure guides you through setup of the RHEL media as a {susemgr}
channel.
All packages on the RHEL media will be mirrored into a child channel located under RES 5/6/7 distribution per architecture. 

.Procedure: Mirroring RHEL Media into a Channel
. Create a new Channel by log in to the {webui} and selecting menu:Channels[Manage Software Channels > Create Channel] . 
. Fill in basic channel details and add the channel as a child to the corresponding RES 5/6/7 distribution channel per architecture from SCC. The base parent channel should contain zero packages. 
. Modify the RES 5/6/7 activation key to include this new child channel. 
. As {rootuser} on the {susemgr} command line copy the ISO to the [path]``/tmp`` directory. 
. Create a directory to contain the media content: 
+

----
{prompt.root}
mkdir -p /srv/www/htdocs/pub/rhel
----
. Mount the ISO: 
+

----
{prompt.root}
mount -o loop /tmp/name_of_iso /srv/www/htdocs/pub/rhel
----
. Start [command]``spacewalk-repo-sync`` to synchronize packages: 
+

----
{prompt.root}
spacewalk-repo-sync -c channel_name -u https://127.0.0.1/pub/rhel/Server/
Repo URL: https://127.0.0.1/pub/rhel/Server/
Packages in repo:              3690
Packages already synced:          0
Packages to sync:              3690
1/3690 : texlive-latex-2007-57.el6_2-0.x86_64
2/3690 : boost-filesystem-1.41.0-18.el6-0.i686
3/3690 : policycoreutils-newrole-2.0.83-19.39.el6-0.x86_64
[...]
----
. When the channel has completed the synchronization process you can use the channel as any normal {susemgr} channel. 


=== Registering RES Salt Minions with {susemgr}


This section will guide you through registering RHEL minions with {susemgr}
.
This section assumes you have updated your server to the latest patch level. 

==== Synchronizing Appropriate RES Channels


Ensure you have the corresponding RES product enabled and required channels have been fully synchronized: 

.RHEL 7.x
* Product: RES 7 
* Mandatory channels: [systemitem]``rhel-x86_64-server-7`` , [systemitem]``res7-suse-manager-tools-x86_64`` , [systemitem]``res7-x86_64`` systemitem> 


.RHEL 6.x
* Product: RES 6 
* Mandatory channels: [systemitem]``rhel-x86_64-server-6`` , [systemitem]``res6-suse-manager-tools-x86_64`` , [systemitem]``res6-x86_64``


.Checking Synchronization Progress
[TIP]
====
To check if a channel has finished synchronizing you can do one of the following: 

* From the {susemgr}{webui} browse to menu:Admin[Setup Wizard] and select the menu:SUSE Products[] tab. Here you will find a percent completion bar for each product. 
* Alternatively, you may check the synchronization log file located under [path]``/var/log/rhn/reposync/channel-label.log`` using cat or the tailf command. Keep in mind that base channels can contain multiple child channels. Each of these child channels will generate its own log during the synchronization progress. Do not assume a channel has finished synchronizing until you have checked all relevant log files including base and child channels. 

====


Create an activation key associated with the RES channel. 

==== Creating a Bootstrap Repository


The following procedure demonstrate creating a bootstrap repository for RHEL 


. On the server command line as root, create a bootstrap repo for RHEL with the following command: 
+

----
mgr-create-bootstrap-repo RHEL_activation_channel_key
----
. Rename [command]``bootstrap.sh`` to [command]``resversion-boostrap.sh``: 
+

----
{prompt.root}
cp bootstrap.sh res7-bootstrap.sh
----


=== Register a Salt Minion via Bootstrap


The following procedure will guide you through registering a Salt minion using the bootstrap script. 

.Procedure: Registration Using the Bootstrap Script
. For your new minion download the bootstrap script from the {susemgr} server: 
+

----
wget --no-check-certificate https://`server`
/pub/bootstrap/res7-bootstrap.sh
----
. Add the appropriate res-gpg-pubkey-#####-#####.key to the `ORG_GPG_KEY` key parameter, comma delimited in your [command]``res7-bootstrap.sh`` script. These are located on your {susemgr} server at: 
+

----
http://`server`
/pub/
----
. Make the [command]``res7-bootstrap.sh`` script executable and run it. This will install necessary Salt packages from the bootstrap repository and start the Salt minion service: 
+

----
{prompt.root}
chmod +x res7-bootstrap.sh{prompt.root}
./res7-boostrap.sh
----
. From the {susemgr}{webui} select menu:Salt[Keys] and accept the new minion's key. 


.Troubleshooting Bootstrap
[IMPORTANT]
====
If bootstrapping a minion fails it is usually caused by missing packages.
These missing packages are contained on the RHEL installation media.
The RHEL installation media should be loop mounted and added as a child channel to the RES channel.
See the warning in <<_bp.expanded_support.resclients>> on access to RHEL Media. 
====

=== Manual Salt Minion Registration


The following procedure will guide you through the registration of a Salt minion manually. 


. Add the bootstrap repository: 
+

----
yum-config-manager --add-repo https://`server`
/pub/repositories/res/7/bootstrap
----
. Install the [package]#salt-minion# package: 
+

----
{prompt.root}
yum install salt-minion
----
. Edit the Salt minion configuration file to point to the {susemgr} server: 
+

----
{prompt.root}
mkdir /etc/salt/minion.d{prompt.root}
echo "master:`server_fqdn`
" > /etc/salt/minion.d/susemanager.conf
----
. Start the minion service: 
+

----
{prompt.root}
systemctl start salt-minion
----
. From the {susemgr}{webui} select the menu:Salt[Keys] and accept the new minion's key. 


[[_bp.expanded_support.centos_repos.trad]]
== Preparing Channels and Repositories for CentOS Traditional Clients


This following section provides an example procedure for configuring CentOS channels and repositories and finally registering a CentOS client with {susemgr}
.
These steps will be identical for Scientific Linux and Fedora. 

.Procedure: Preparing Channels and Repositories
. As {rootuser} install [package]#spacewalk-utils# on your {susemgr} server: 
+

----
zypper in spacewalk-utils
----
+

.Supported Tools
IMPORTANT: The [package]#spacewalk-utils#
 package contains a collection of upstream command line tools which provide assistance with spacewalk administrative operations.
You will be using the [command]``spacewalk-common-channels`` tool.
Keep in mind {suse}
 only provides support for [command]``spacewalk-clone-by-date`` and [command]``spacewalk-manage-channel-lifecycle`` tools. 
. Run the [command]``spacewalk-common-channels`` script to add the CentOS7 base, updates, and Spacewalk client channels. 
+

----
{prompt.root}
spacewalk-common-channels -u admin -p`secret`
-a x86_64 'centos7'{prompt.root}
spacewalk-common-channels -u admin -p`secret`
-a x86_64 'centos7-updates'{prompt.root}
spacewalk-common-channels -u admin -p`secret`
-a x86_64 'spacewalk26-client-centos7'
----
+

.Required Channel References
NOTE: The [path]``/etc/rhn/spacewalk-common-channels.ini``
 must contain the channel references to be added.
If a channel is not listed, check the latest version here for updates: https://github.com/spacewalkproject/spacewalk/tree/master/utils
. From the {webui} select menu:Software[Manage Software Channels > Overview] . Select the base channel you want to synchronize, in this case ``CentOS7 (x86_64)``. Select menu:Repositories[Sync] . Check the channels you want to synchronize and then click the menu:Sync Now[] button or, optionally, schedule a regular synchronization time. 
. Copy all relevant GPG keys to [path]``/srv/www/htdocs/pub`` . Depending on what distribution you are interested in managing these could include an EPEL key, SUSE keys, Red Hat keys, and CentOS keys. After copying these you can reference them in a comma-delimited list within your bootstrap script (see <<_proc.bp.expanded_support.centos_repos.trad.bsscript>>). 
** CentOS7 key files: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
** EPEL key file: http://mirrors.kernel.org/fedora-epel/RPM-GPG-KEY-EPEL-7
** Spacewalk key: http://spacewalk.redhat.com/yum/RPM-GPG-KEY-spacewalk-2015
** Red Hat keys: http://www.redhat.com/contact/security-response-team/gpg-keys.html
. Install and setup a CentOS 7 client with the default installation packages. 
. Ensure the client machine can resolve itself and your {susemgr} server via DNS. Validate that there is an entry in [path]``/etc/hosts`` for the real IP address of the client. 
. Create an activation key (``centos7``) on the {susemgr} server that points to the correct parent/child channels, including the CentOS base repo, updates, and Spacewalk client. 


Now prepare the bootstrap script. 

[[_proc.bp.expanded_support.centos_repos.trad.bsscript]]
.Procedure: Preparing the Bootstrap Script
. Create/edit your bootstrap script to correctly reflect the following: 
+

----
# can be edited, but probably correct (unless created during initial install):

# NOTE: ACTIVATION_KEYS *must* be used to bootstrap a client machine.

ACTIVATION_KEYS=1-centos7

ORG_GPG_KEY=res.key,RPM-GPG-KEY-CentOS-7,suse-307E3D54.key,suse-9C800ACA.key,RPM-GPG-KEY-spacewalk-2015

FULLY_UPDATE_THIS_BOX=0

yum clean all
# Install the prerequisites
yum -y install yum-rhn-plugin rhn-setup
----
. Add the following lines to the bottom of your script, (just before `echo "`-bootstrap complete -`"` ): 
+

----
# This section is for commands to be executed after registration
mv /etc/yum.repos.d/Cent* /root/
yum clean all
chkconfig rhnsd on
chkconfig osad on
service rhnsd restart
service osad restart
----
. Continue by following normal bootstrap procedures to bootstrap the new client. 


[[_bp.expanded_support.centos_salt]]
== Registering CentOS Salt Minions with {susemgr}


The following procedure will guide you through registering a CentOS Minion. 

.Support for CentOS Patches
[WARNING]
====
CentOS uses patches originating from CentOS is not officially supported by {suse}
.
See the matrix of {susemgr}
clients on the main page of the {susemgr}
wiki, linked from the [ref]_Quick
    Links_
 section: https://wiki.microfocus.com/index.php?title=SUSE_Manager
====

.Procedure: Register a CentOS 7 Minion
. Add the Open Build Service repo for Salt: 
+

----
{prompt.root}
yum-config-manager --add-repo http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products/RHEL_7/
----
. Import the repo key: 
+

----
{prompt.root}
rpm --import http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products/RHEL_7/repodata/repomd.xml.key
----
. Check if there is a different repository that contains Salt. If there is more than one repository listed disable the repository that contains Salt apart from the OBS one. 
+

----
{prompt.root}
yum list --showduplicates salt
----
. Install the Salt minion: 
+

----
{prompt.root}
yum install salt salt-minion
----
. Change the Salt configuration to point to the {susemgr} server: 
+

----
{prompt.root}
mkdir -p /etc/salt/minion.d{prompt.root}
echo "master:`server_fqdn`
" > /etc/salt/minion.d/susemanager.conf
----
. Restart the minion 
+

----
{prompt.root}
systemctl restart salt-minion
----
. Proceed to menu:Salt[Keys] from the {webui} and accept the minion's key. 
