[[bp.postgresql.database.migration]]
= PostgreSQL Database Migration

include::entities.adoc[]


{productname} 3 uses PostgreSQL version 9.4.
{productname} 3.2 uses PostgreSQL version 10.

PostgreSQL version 9.6 has been released for {sls} 12 SP3.
PostgreSQL version 10 has been released for {sls} 12 SP4 and later.
This chapter provides guidance on migrating your {productname} Server from PostgreSQL 9.4 to 9.6, or migrating from 9.6 to 10.


[[bp.postgresql.database.migration.new.installations]]
== New {productname} Installations


PostgreSQL version 10 is now supported on {productname}.
New {productname} installations will have PostgreSQL version 10 installed by default.
When you install {productname} on {sle}{nbsp}12 SP4, the latest version of PostgreSQL will be installed by default.
This will be fully transparent to the user.
Check the active PostgreSQL version with this command:

----
suse-manager-example-srv:~ # psql --version
psql (PostgreSQL) 10.9
----



[[bp.postgresql.database.migrating.existing.installations]]
== Migrating an Existing Installation

[WARNING]
====
Always create a database backup before performing a migration.
For more information about a database backup, see xref:bp_chap_suma_backup.adoc[].
====

PostgreSQL upgrades can be performed in two ways: a regular upgrade, or a fast upgrade:

A regular upgrade will create a complete copy of the database, so you will need double the existing database size of space available.
Regular upgrades can take a considerable amount of time, depending on the size of the database and the speed of the storage system.

A fast upgrade only takes a few minutes, and uses almost no additional disk space.
However, if a fast upgrade fails, you must restore the database from the backup.
A fast upgrade reduces the risk of running out of disk space.

In case of failure you do not have the implicit backup that you get when doing a regular upgrade.
The regular upgrade will copy the database files instead of hardlinking them.

PostgreSQL stores data at [path]``/var/lib/pgsql/data/``, and logs to [path]``/var/lib/pgsql/data/pg_xlog/``.



=== Upgrade from PostgreSQL 9.4 to 9.6

Before you migrate to PostgreSQL 9.6, ensure SUSE Manager is the latest version, and fully updated.
You can check if the system is ready to use PostgreSQL 9.6 with:

----
psql --version
----

If you are using PostgreSQL{nbsp}9.4, you can upgrade to PostgreSQL{nbsp}9.6.


[IMPORTANT]
====
PostgreSQL 9.6 requires smdba version 1.5.8 or higher.
Check with:
----
rpm -q smdba
----
====


.Procedure: Performing a Regular Upgrade
. Perform a database backup.
For more information on backing up, see xref:bp_chap_suma_backup.adoc[].
. Begin the upgrade:
+
----
/usr/lib/susemanager/bin/pg-migrate.sh
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
The old directory is renamed to [path]``/var/lib/pgsql/data-pg94``.


The [path]``pg-migrate.sh`` script performs these operations:

* Stop spacewalk services
* Shut down the running database
* Check if PostgreSQL 9.6 is installed and install it if necessary
* Switch from PostgreSQL 9.4 to PostgreSQL 9.6 as the new default
* Start the database migration
* Create a PostgreSQL configuration file tuned for use by {productname}
* Start the database and spacewalk services


[NOTE]
====
If the upgrade fails, the migration script will attempt to restore the database to its original state.
====


.Procedure: Performing a Fast PostgreSQL Upgrade
. Perform a database backup.
Without a verified database backup, you must not initiate a fast upgrade.
For more information on backing up, see xref:bp_chap_suma_backup.adoc[].
. Begin the upgrade:
+
----
/usr/lib/susemanager/bin/pg-migrate.sh fast
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
The old directory is renamed to [path]``/var/lib/pgsql/data-pg94``.



=== Upgrade from PostgreSQL 9.6 to 10


Before you migrate to PostgreSQL 9.10, ensure SUSE Manager is the latest version, and fully updated.
You can check if the system is ready to use PostgreSQL 9.10 with:

----
psql --version
----

If you are using PostgreSQL{nbsp}9.6, you can upgrade to PostgreSQL{nbsp}10.

[IMPORTANT]
====
PostgreSQL 9.10 requires smdba version 1.6.2 or higher.
Check with:
----
rpm -q smdba
----
====

.Procedure: Performing a Regular Upgrade
. Perform a database backup.
// For more information on backing up, see xref:administration:backup-restore.adoc[].
. Begin the upgrade:
+
----
/usr/lib/susemanager/bin/pg-migrate-96-to-10.sh
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
The old directory is renamed to [path]``/var/lib/pgsql/data-pg96``.

The [path]``pg-migrate-96-to-10.sh`` script performs these operations:

* Stop spacewalk services
* Shut down the running database
* Check if PostgreSQL{nbsp}10 is installed and install it if necessary
* Switch from PostgreSQL{nbsp}9.6 to PostgreSQL{nbsp}10 as the new default
* Initiate the database migration
* Create a PostgreSQL configuration file tuned for use by {productname}
* Start the database and spacewalk services

[NOTE]
====
If the upgrade fails, the migration script will attempt to restore the database to its original state.
====

.Procedure: Performing a Fast PostgreSQL Upgrade
. Perform a database backup.
Without a verified database backup, you must not initiate a fast upgrade.
// For more information on backing up, see xref:administration:backup-restore.adoc[].
. Begin the upgrade:
+
----
/usr/lib/susemanager/bin/pg-migrate-96-to-10.sh fast
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
The old directory is renamed to [path]``/var/lib/pgsql/data-pg96``.



== Typical Migration Sample Session


A slow migration should provide you with the following output:

----
d235:~ # /usr/lib/susemanager/bin/pg-migrate.sh
15:58:00   Shut down spacewalk services...
Shutting down spacewalk services...
Done.
15:58:03   Checking postgresql version...
15:58:03   Installing postgresql 9.6...
Dienst 'SUSE_Linux_Enterprise_Server_12_SP2_x86_64' wird aktualisiert.
Dienst 'SUSE_Manager_Server_3.1_x86_64' wird aktualisiert.
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...
Paketabhängigkeiten werden aufgelöst...

Die folgenden 3 NEUEN Pakete werden installiert:
  postgresql96 postgresql96-contrib postgresql96-server

3 neue Pakete zu installieren.
Gesamtgröße des Downloads: 5,7 MiB. Bereits im Cache gespeichert: 0 B. Nach der Operation werden zusätzlich 25,3 MiB belegt.
Fortfahren? [j/n/...? zeigt alle Optionen] (j): j
Paket postgresql96-9.6.3-2.4.x86_64 abrufen (1/3),   1,3 MiB (  5,1 MiB entpackt)
Abrufen: postgresql96-9.6.3-2.4.x86_64.rpm [fertig]
Paket postgresql96-server-9.6.3-2.4.x86_64 abrufen (2/3),   3,7 MiB ( 17,9 MiB entpackt)
Abrufen: postgresql96-server-9.6.3-2.4.x86_64.rpm [.fertig]
Paket postgresql96-contrib-9.6.3-2.4.x86_64 abrufen (3/3), 648,9 KiB (  2,2 MiB entpackt)
Abrufen: postgresql96-contrib-9.6.3-2.4.x86_64.rpm [fertig]
Überprüfung auf Dateikonflikte läuft: [......fertig]
(1/3) Installieren: postgresql96-9.6.3-2.4.x86_64 [............fertig]
(2/3) Installieren: postgresql96-server-9.6.3-2.4.x86_64 [............fertig]
(3/3) Installieren: postgresql96-contrib-9.6.3-2.4.x86_64 [............fertig]
15:58:08   Ensure postgresql 9.6 is being used as default...
15:58:09   Successfully switched to new postgresql version 9.6.
15:58:09   Create new database directory...
15:58:09   Initialize new postgresql 9.6 database...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/pgsql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/pgsql/data -l logfile start

15:58:12   Successfully initialized new postgresql 9.6 database.
15:58:12   Upgrade database to new version postgresql 9.6...
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* system OID user data types                ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for roles starting with 'pg_'                      ok
Creating dump of global objects                             ok
Creating dump of database schemas
  postgres
  susemanager
  template1
                                                            ok
Checking for presence of required libraries                 ok
Checking database user is the install user                  ok
Checking for prepared transactions                          ok

If pg_upgrade fails after this point, you must re-initdb the
new cluster before continuing.

Performing Upgrade
------------------
Analyzing all rows in the new cluster                       ok
Freezing all rows on the new cluster                        ok
Deleting files from new pg_clog                             ok
Copying old pg_clog to new server                           ok
Setting next transaction ID and epoch for new cluster       ok
Deleting files from new pg_multixact/offsets                ok
Copying old pg_multixact/offsets to new server              ok
Deleting files from new pg_multixact/members                ok
Copying old pg_multixact/members to new server              ok
Setting next multixact ID and offset for new cluster        ok
Resetting WAL archives                                      ok
Setting frozenxid and minmxid counters in new cluster       ok
Restoring global objects in the new cluster                 ok
Restoring database schemas in the new cluster
  postgres
  susemanager
  template1
                                                            ok
Copying user relation files
  /var/lib/pgsql/data-pg94/base/12753/12710

[...]

  /var/lib/pgsql/data-pg94/base/1/12574
                                                            ok
Setting next OID for new cluster                            ok
Sync data directory to disk                                 ok
Creating script to analyze new cluster                      ok
Creating script to delete old cluster                       ok

Upgrade Complete
----------------
Optimizer statistics are not transferred by pg_upgrade so,
once you start the new server, consider running:
    ./analyze_new_cluster.sh

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
15:58:51   Successfully upgraded database to postgresql 9.6.
15:58:51   Tune new postgresql configuration...
INFO: Database configuration has been changed.
INFO: Wrote new general configuration. Backup as /var/lib/pgsql/data/postgresql.2017-07-26-15-58-51.conf
INFO: Wrote new client auth configuration. Backup as /var/lib/pgsql/data/pg_hba.2017-07-26-15-58-51.conf
INFO: Configuration has been changed, but your database is right now offline.
Database is offline
System check finished
15:58:51   Successfully tuned new postgresql configuration.
15:58:51   Starting spacewalk services...
Starting spacewalk services...
Done.
----
