[[suse.mgr.command.line.tools]]
= SUSE Manager Command Line Tools
ifdef::env-github,backend-html5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:linkattrs:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:susemgr: SUSE Manager
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:saltversion: 2018.3.0
:webui: WebUI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
:ay: AutoYaST
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images


== Installing Command Line Tool Packages

In addition to the SUSE Manager Web interface, SUSE Manager offers two command line tools for managing (Traditional) system configuration files :

* The Configuration Client (*mgrcfg-client*)
* The Configuration Manager (*mgrcfg-manager*)

You can use the *mgrcfg-actions* tool to _enable_ and _disable_ configuration management on client systems.

To work with these tools install them from the SUSE Manager Tools child channel as root.

----
zypper in rhncfg-manager
----

----
zypper in rhncfg-actions
----

Install the following package on client systems:
----
zypper in rhncfg-client
----

[TIP]
.Configuration File Backups
====
When a configuration file is deployed via SUSE Manager, a backup of the previous file including its full path is stored in the [path]``/var/lib/rhncfg/backups/``.
The backup retains its filename but has a _.rhn-cfg-backup_ extension appended.
====



[[mgr.actions.control]]
== Actions Control [mgr-actions-control]

The Actions Control (*mgr-actions-control*) application is used to enable and disable configuration management on a system.
Client systems cannot be managed in this fashion by default.
This tool allows SUSE Manager administrators to enable or disable specific modes of allowable actions such as:

* Deploying a configuration file on the system
* Uploading a file from the system
* Using the diff command to find out what is currently managed on a system with what is available
* Running remote commands

These various modes are enabled/disabled by placing/removing files and directories in the [path]``/etc/sysconfig/rhn/allowed-actions/`` directory.
Due to the default permissions of the [path]``/etc/sysconfig/rhn/`` directory, Actions Control has to be run by someone with root access.

=== General command line options

There is a manpage available, as for most command line tools.
First, decide which scheduled actions should be enabled for use by system administrators.
The following options enable the various scheduled action modes:

--enable-deploy::
Allow mgrcfg-client to deploy files.

--enable-diff::
Allow mgrcfg-client to diff files.

--enable-upload::
Allow mgrcfg-client to upload files.

--enable-mtime-upload::
Allow mgrcfg-client to upload mtime (file modification time).

--enable-all::
Allow mgrcfg-client to do everything.

--enable-run::
Enable running scripts.

--disable-deploy::
Disable deployment.

--disable-diff::
Prohibit diff use.

--disable-upload::
No file uploads allowed.

--disable-mtime-upload::
Disable mtime upload.

--disable-all::
Disable all options.

--disable-run::
No scripts allowed to run.

--report::
Report whether modes are enabled or disabled.

-f, --force::
Force the operation without asking first.

-h, --help::
Show help message and exit.

Once a mode is set, your system is ready for configuration management through SUSE Manager.
A common option is [command]``mgr-actions-control --enable-all``.



[[mgrcfg.client.tool]]
== Configuration Client [mgrcfg-client]

The Configuration Client (mgrcfg-client) is installed on and run from an individual client system to gain knowledge about how SUSE Manager deploys configuration files to the client.

The Configuration Client offers these primary modes:

* list
* get
* channels
* diff
* verify

=== Listing Configuration Files

To list the configuration files for the machine and the labels of the config channels containing them, issue the command:

----
mgrcfg-client list
----

The output resembles the following list (“DoFoS” is a shortcut for “D or F or S”, which means “Directory”, “File”, or “Something else”(?)):

----
DoFoS   Config Channel      File
F      config-channel-17   /etc/example-config.txt
F      config-channel-17   /var/spool/aalib.rpm
F      config-channel-14   /etc/rhn/rhn.conf
----

These configuration files apply to your system.
However, there may be duplicate files present in other channels.
For example, issue the following command:

----
mgrcfg-manager list config-channel-14
----

and observe the following output:

----
Files in config channel 'config-channel-14'
/etc/example-config.txt /etc/rhn/rhn.conf
----

You may wonder why the second version of [path]``/etc/example-config.txt`` in *config-channel-14* does not apply to the client system.
The rank of the [path]``/etc/example-config.txt`` file in *config-channel-17* was higher than that of the same file in *config-channel-14*.
As a result, the version of the configuration file in config-channel-14 is not deployed for this system, therefore mgrcfg-client command does not list the file.



[[getting.a.config.file]]
=== Downloading a Config File

To download the most relevant configuration file for the machine, issue the command:

----
mgrcfg-client get /etc/example-config.txt
----

You should see output resembling:

----
Deploying /etc/example-config.txt
----

View the contents of the file with less or another pager.
Note that the file is selected as the most relevant based on the rank of the config channel containing it.
This is accomplished within the Configuration tab of the System Details page.
Refer to Section “System Details” (Chapter 4, Systems, ↑User Guide) for instructions.


[[viewing.config.channels]]
=== Viewing Config Channels

To view the labels and names of the config channels that apply to the system, issue the command:

----
mgrcfg-client channels
----

You should see output resembling:

----
Config channels:
Label                   Name
-----                   ----
config-channel-17       config chan 2
config-channel-14       config chan 1
----

The list of options available for [command]``mgrcfg-client get``:

--topdir=TOPDIR::
Make all file operations relative to this string.
+

--exclude=EXCLUDE::
Exclude a file from being deployed with get.
May be used multiple times.
+

-h, --help::
Show help message and exit.

[[diff.between.config.files]]
=== Differentiating between Config Files

To view the differences between the config files deployed on the system and those stored by SUSE Manager, issue the command:

----
mgrcfg-client diff
----

The output resembles the following:

----
rhncfg-client diff
--- /etc/test
+++ /etc/test 2013-08-28 00:14:49.405152824 +1000
@@ -1 +1,2 @@
This is the first line
+This is the second line added
----

In addition, you can include the [option]``--topdir`` option to compare config files with those located in an arbitrary (and unused) location on the client system, like this:

----
# mgrcfg-client diff --topdir /home/test/blah/
/usr/bin/diff: /home/test/blah/etc/example-config.txt: No such file or directory
/usr/bin/diff: /home/test/blah/var/spool/aalib.rpm: No such file or directory
----


[[verify.config.files]]
=== Verifying Config Files

To quickly determine if client configuration files are different from those associated with it via SUSE Manager, issue the command:

----
mgrcfg-client verify
----

The output resembles the following:

----
modified /etc/example-config.txt /var/spool/aalib.rpm
----

The file [filename]``example-config.txt`` is locally modified, while [package]``aalib.rpm`` is not.

The list of the options available for mgrcfg-client verify:

-v, --verbose::
Increase the amount of output detail.
Display differences in the mode, owner, and group permissions for the specified config file.

-o, --only::
Only show differing files.

-h, --help::
Show help message and exit.



[[the.configuration.manager]]
== Configuration Manager [mgrcfg-manager]

The Configuration Manager (*mgrcfg-manager*) is designed to maintain SUSE Manager's central repository of config files and channels, not those located on client systems.
This tool offers a command line alternative to the configuration management features in the SUSE Manager Web interface.
Additionally, some or all of the related maintenance tasks can be scripted.

To use the command line interface, configuration administrators require a SUSE Manager account (username and password) with the appropriate permission set.
The username may be specified in [path]``/etc/sysconfig/rhn/rhncfg-manager.conf`` or in the [option]``[rhncfg-manager]`` section of [path]``~/.rhncfgrc``.

When the Configuration Manager is run as *root*, it attempts to pull in needed configuration values from the Red Hat Update Agent.
When run as a user other than root, you may have to change the [path]``~/.rhncfgrc`` configuration file.
The session file is cached in [path]``~/.rhncfg-manager-session`` to avoid having to log in for every command.

The default timeout for the Configuration Manager is 30 minutes.
To adjust this, add the [option]``server.session_lifetime`` option and a new value to the [path]``/etc/rhn/rhn.conf`` file on the server running the manager.
For example set the time out to *120 minutes*:

----
server.session_lifetime = 120
----

The Configuration Manager offers the following primary *modes*:

* add
* create-channel
* diff
* diff-revisions
* download-channel
* get
* list
* list-channels
* remove
* remove-channel
* revisions
* update
* upload-channel

Each mode offers its own set of options, which can be displayed by issuing the following command:

----
mgrcfg-manager mode --help
----

Replace mode with the name of the mode whose options you want to see:

----
mgrcfg-manager diff-revisions --help
----



[[creating.a.config.channel]]
=== Creating a Config Channel

To create a config channel for your organization, issue the command:

----
mgrcfg-manager create-channel channel-label
----

If prompted for your SUSE Manager username and password, provide them.
Once you have created a config channel, use the remaining modes listed above to populate and maintain that channel.



[[adding.files.to.a.config.channel]]
=== Adding Files to a Config Channel

To add a file to a config channel, specify the channel label and the local file to be uploaded:

----
mgrcfg-manager add --channel=channel-label /path/to/file
----

In addition to the required channel label and the path to the file, you can use the available options for modifying the file during its addition.
For instance, you can alter the path and file name by including the [option]``--dest-file`` option in the command:

----
mgrcfg-manager add --channel=channel-label \
  --dest-file=/new/path/to/file.txt/path/to/file
----

The output resembles the following:

----
Pushing to channel example-channel
Local file >/path/to/file -> remote file /new/path/to/file.txt
----

The list of options available for mgrcfg-manager add:

-c CHANNEL --channel=CHANNEL::
Upload files in this config channel.

-d DEST_FILE --dest-file=DEST_FILE::
Upload the file as this path.

--delim-start=DELIM_START::
Start delimiter for variable interpolation.

--delim-end=DELIM_END::
End delimiter for variable interpolation.

-i, --ignore-missing::
Ignore missing local files.

-h, --help::
Show help message and exit.

[[_syncing.suse.mgr.repositories.scc]]
== Syncing SUSE Manager Repositories from SCC [mgr-sync]

[command]``mgr-sync`` should be used if SUSE Manager is connected to SUSE Customer Center (SCC).
With [command]``mgr-sync`` you may add or synchronize products and channels.
The [command]``mgr-sync`` command also enables and refreshes SCC data.

This tool requires that SCC is enabled by running [command]``mgr-sync enable-scc`` first (Enabled by default in {susemgr} 2.1 and greater).

[IMPORTANT]
.Admin credentials
====
[command]``mgr-sync`` now requires the username/password of a *SUSE Manager administrator*.
Most functions are available as part of the public API.
====

mgr-sync provides a command structure with sub-commands similar to git or osc.
For a complete list of command line option, see the mgr-sync manpage (man mgr-sync).
Basic actions are:

----
mgr-sync enable-scc

mgr-sync list channel(s)|product(s)|credentials
mgr-sync add  channel(s)|product(s)|credentials
mgr-sync delete  credentials

mgr-sync refresh [--refresh-channels] [--from-mirror MIRROR]
----

See the following examples.

List channels::
+

----
mgr-sync list channels
----

Add a channel::
+

----
mgr-sync add channel LABEL
----

List products::
+

----
mgr-sync list products
----

Add a product::
+

----
mgr-sync add product
----

Refresh the data::
+

----
mgr-sync refresh
----

Refresh data and schedule a reposync for all installed vendor channels::
+

----
mgr-sync refresh --refresh-channels
----

List SCC credentials::
+

----
mgr-sync list credentials
----

Add new SCC credentials::
+

----
mgr-sync add credentials
----

[TIP]
.Credentials
====
There can be one primary credential only.
This is username/password used first when retrieving the list of available channels and packages.
====

Add SCC primary credentials::
+

----
mgr-sync add credentials --primary
----

Delete SCC credentials::
+

----
mgr-sync delete credentials
----
