= Available Documentation

include::entities.adoc[]

The following manuals are available on this product:

ifdef::env-github,backend-html5[]
<<book_mgr_getting_started.adoc#book.suma.getting-started, SUSE Manager Getting Started>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.getting-started>>::
endif::[]
Lists installation scenarios and example topologies for different {productname} setups.
Guides you step by step through the installation, setup and basic configuration of {productname}.
Also contains detailed information about {productname} maintenance and troubleshooting.

ifdef::env-github,backend-html5[]
<<book_suma_reference_manual.adoc#book.suma.reference.manual, Reference>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.reference.manual>>::
endif::[]
Reference documentation that covers the Web interface to {productname} ({webui}).

ifdef::env-github,backend-html5[]
<<book_mgr_best_practices.adoc#book.suma.best.practices, Best Practices>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.best.practices>>::
endif::[]
Best practices on selected topics.

ifdef::env-github,backend-html5[]
<<book_suma_advanced_topics.adoc#book.suma.advanced.topics, Advanced Topics>>::
endif::[]
ifndef::env-github,backend-html5[]
<<book.suma.advanced.topics>>::
endif::[]
A collection of advanced topics not covered under the Best Practices Guide.

// Add docmentation develop link once dev docs are up on gh-pages. Latest docs will always be develop.
HTML versions of the product manuals can be found in the installed system under [path]``/usr/share/doc/manual``.
Find the latest documentation updates at http://www.suse.com/documentation/suse-manager/[Latest Docmentation,window="_blank"] where you can download PDF or HTML versions of the manuals for your product.

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]
