= Documentation Conventions


The following typographical conventions are used in this manual: 

* [path]``/etc/passwd`` : directory names and file names 
* [replaceable]``placeholder``: replace [replaceable]``placeholder`` with the actual value 
* [var]``PATH``: the environment variable PATH 
* [command]``ls``, [option]``--help``: commands, options, and parameters 
* [username]``user`` : users or groups 
* [package]#packagename# : name of a package 
* kbd:[Alt] , kbd:[+F1] : a key to press or a key combination; keys are shown in uppercase as on a keyboard 
* menu:File[] , menu:File[Save As] : menu items, buttons 
* This paragraph is only relevant for the x86_64 architecture. The arrows mark the beginning and the end of the text block. 
+ 
This paragraph is only relevant for the architectures `{zseries}` and ``POWER``.
The arrows mark the beginning and the end of the text block. 
* _Dancing Penguins_ (Chapter __Penguins__, {uarr} Another Manual): This is a reference to a chapter in another manual. 
