= Introduction to High Availability on {productname}
include::entities.adoc[]

== Overview

[WARNING]
====
For SUSE Internal Use Only
====

SUSE® Linux Enterprise High Availability Extension is an integrated suite of open source clustering technologies that enables you to implement highly available physical and virtual Linux clusters. For quick and efficient configuration and administration, the High Availability Extension includes both a graphical user interface (GUI) and a command line interface (CLI). Additionally, it comes with the HA Web Konsole (Hawk), allowing you to administer your Linux cluster also via a Web interface.

Since you are reading this you are most likely interested in configuring {productname} to be Highly Available. This guide covers configuration of {productname} with {sleha}.

== What You Will Accomplish
In this guide you will use KVM to setup {productname} on two nodes with {sleha}.
You will also setup a third server that provides the iSCSI shared storage for the nodes.

For this guide you will setup High Availability manually.
You will not be using the *ha-cluster-init* scripts provided by SUSE in the {sleha}.
By performing these tasks manually you will learn where and how HA should be configured for {productname}.

[NOTE]
.What you Should Already Know
====
This guide assumes that you understand foundational {sleha} and {sle} installation concepts, however additional information will be provided when necessary.
For an overview and more information on {sleha} see:

https://www.suse.com/documentation/sle-ha-12/[{sleha} {sles-version} {sp-version} Documentation]
====