[[_sles.installation.within.kvm.jeos]]
= JeOS Installation
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
//
:susemgr: SUSE Manager
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
:zseries: z Systems
:productnumber: 3.2
:sles-version: 12
:sp-version: SP3
endif::[]
:doctype: book
:sectnums:
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images

[[_quickstart.sect.kvm.settings]]
== Virtual Machine Manager (virt-manager) Settings


This chapter provides the required (KVM) settings for installation of {sle} Just Enough Operating System (JeOS) 12 as the base for {susemgr}.
A kernel virtual machine (KVM) combined with Virtual Machine Manager (_virt-manager_) will be used as a sandbox for your first installation.

.{suse}Virtualization Guide
[TIP]
====
For more information on virtualization, see: https://www.suse.com/documentation/sles-12/singlehtml/book_virt/book_virt.html[SUSE Linux Enterprise Virtualization Guide]
====

//This section needs revision its ugly and outdated.
Enter the following settings when creating a new virtual machine using _virt-manager_ (replace _version with the actual version string):

[cols="1,1", options="header"]
|===
2+<| KVM Settings
| Installation Method | Import Existing Disk Image
| OS:                 | Linux
| Version:            | _SLES<VERSION>-JeOS-for-kvm-and-xen.x86_64-GM.qcow2_
| Memory:             | 4096 MB
| CPU's:              | 2
| Storage Format:     |_.qcow2_ 24 GB (Default) JeOS Root Partition
| Virtual Disks:

VirtIO Disk 2

VirtIO Disk 3

VirtIO Disk 4         | 101 GB for [path]``/var/spacewalk``

                        50 GB for [path]``/var/lib/pgsql``

                        4 GB for swap
| Name:               | test-setup
| Network             |Bridge _br0_
|===

.{suse}Virtualization Guide
[TIP]
====
For more information on virtualization, see: https://www.suse.com/documentation/sles-12/singlehtml/book_virt/book_virt.html[SUSE Linux Enterprise Virtualization Guide]
====

[[_jeos.kvm.settings]]
== JeOS KVM Settings


Create 3 additional virtual disks required for the {susemgr} storage partitions.

.Procedure: Creating the Required Partitions with KVM
. Create a new virtual machine using the downloaded JeOS KVM image and select menu:Import existing disk image[] .
. Configure RAM and number of CPUs (At least 4 GB RAM and 2 CPUs).
. Name your KVM machine and select the menu:Customize configuration before install[] check box.
. Select the btn:[Add Hardware] button and create three new virtual disks with the following specifications.
These disks will be partitioned and mounted in <<_proc.jeos.susemgr.prep>>.
+

[cols="1,1,1", options="header"]
|===
| VirtIO Storage Disks | Name      | Sizing
| VirtIO Disk 2        | spacewalk | 101 GB
| VirtIO Disk 3        | pgsql     | 50 GB
| VirtIO Disk 4        | swap      | 4 GB
|===

. Click menu:Begin Installation[] and your new VM will boot from the JeOS image.


Proceed through the basic JeOS installation prompts until you reach the command line.

.Root Password
[TIP]
====
During the basic installation prompts you are asked to enter the {rootuser} password.
Select a strong password and then in the next message box btn:[Confirm root Password].
====

[[_jeos.susemgr.prep]]
== Preparing JeOS for {susemgr}

[[_proc.jeos.susemgr.prep]]
.Procedure: Preparing JeOS for {susemgr}Installation
. Register with SCC:
+

----
SUSEConnect -e`EMAIL_ADDRESS`-r`SUSE_MANAGER_CODE`
----
. Add {susemgr} repositories:
+

----
SUSEConnect -p SUSE-Manager-Server/{productnumber}/x86_64 -r`SUSE_MANAGER_CODE`
----
. Install [package]#yast2-storage# with all required dependencies (approx. 40 packages, 30 MB when installed).
This basic administration package is required for preparing storage partitions:
+

----
zypper in -t package yast2-storage
----
. Partition and mount the virtual disks at the following locations using {yast} Partitioner ([command]``yast2 disk``).
+

[cols="1,1,1,1", options="header"]
|===
| VirtIO Storage Disks | Name                     | Storage Size | File System Type
| VirtIO Disk 2        | [path]``/var/spacewalk`` | 101 GB       | XFS
| VirtIO Disk 3        | [path]``/var/lib/pgsql`` | 50 GB        | XFS
| VirtIO Disk 4        | [path]``swap``           | 4 GB         | swap
|===

. {slsa} by default uses the BTRFS file system. A mount point is created automatically for [path]``/var/lib/pgsql/`` (even when not installed). This must be removed or commented out from the [path]``/etc/fstab`` entries. As {rootuser} edit [path]``/etc/fstab`` and comment out or remove the line:
+

----
/var/lib/pgsql btrfs subvol=@/var/lib/pgsql 0 0
----
+
.Removing the `pgsql` in the[path]``/etc/fstab``Entry
WARNING: If you do not remove this line from fstab the first time you shutdown the server you will lose your database.
This occurs because you will have duplicate entries in the fstab.

Updated tools shipped with recent SPs will no longer require human intervention.
+

. Exit the partitioner and install the {susemgr} pattern:
+

----
zypper in -t pattern suma_server
----


For executing {susemgr}
setup: proceed to <<_suma.setup.with.yast.sumasetup>>.
