:sectnums!:

[preface]
[[_preface.susemanager.user]]
= About This Guide

{susemgrreg}
enables you to efficiently manage a set of Linux systems and keep them up-to-date.
It provides automated and cost-effective software management, asset management, system provisioning, and monitoring capabilities. {susemgr}
is compatible with {rh}
Satellite Server and offers seamless management of both {sle}
and {rhel}
client systems. 

include::common_version_info.adoc[leveloffset=1]


This manual explains the features of the Web interface and is intended for {susemgr}
administrators and administrators with restricted roles for specific tasks.
On certain topics we also provide background information, while some chapters contain links to additional documentation resources.
The latter include additional documentation available on the installed system as well as documentation on the Internet. 

For an overview of the documentation available for your product and the latest documentation updates, refer to http://www.suse.com/documentation/suse-manager-3/ or to the following section. 

HTML versions of the manuals are also available from the menu:Help[]
 tab of the {susemgr}
 Web interface. 

.Obtaining the Release Notes
[NOTE]
====
Although this manual reflects the most current information possible, read the [ref]_SUSE Manager Release Notes_
 for information that may not have been available prior to the finalization of the documentation.
The release notes can be found at http://www.suse.com/documentation/suse-manager-3/. 
====

include::common_intro_available_doc_i.adoc[leveloffset=1]


include::common_intro_feedback_i.adoc[leveloffset=1]


include::common_intro_typografie_i.adoc[leveloffset=1]


include::common_intro_typografie_suma.adoc[leveloffset=1]


:sectnums: