[[retail.chap.install]]
= Installation
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname:
:susemgr: SUSE Manager
:smr: SUSE Manager for Retail
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:webui: Web UI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images





[[retail.sect.running.requirements]]
== Requirements

This is a checklist of tasks to prepare generic {smr} stack:

install and configure central {susemgr} server

install {smr} pattern on central {susemgr} server

install and configure SLES12SP3 to be used as a build host

register build host to {susemgr} using salt

set build host as an OS Image build host in {susemgr} web user interface and apply highstate

install and configure branch server

register branch server to {susemgr} using salt

assign and configure branch server formulas


Hardware requirements
Central {susemgr}:

check relevant {susemgr} documentation

Branch servers:

check relevant {susemgr} Proxy documentation

Build hosts:

only x86_64 architecture is supported by {smr}

Terminals:

only x86_64 architecture is supported by {smr}

Images:

only x86_64 architecture is supported by {smr}

Network Requirements
Central {susemgr} server requires reasonably fast WAN connect

Branch server

Branch server requires a WAN connection where central {susemgr} server is reachable

In case of shared network, router/firewall filtering DHCP requests from shared network to WAN must be present

In case of dedicated network, branch server requires at least two network interfaces. One connected to WAN with reachable central {susemgr} and the second connected to internal branch LAN

Terminals require LAN connection to branch shared or dedicated network


[[retail.sect.running.install]]
== Installation

Installation of central {susemgr} server
Refer to [quickstart3_chap_install_overview.adoc] how to install underlying {susemgr}.

Install {smr} pattern

Make sure all {smr} formulas are installed.

{smr} formulas consists of several packages that are available from {susemgr} media

{smr} formula packages
bind-formula
branch-network-formula
dhcpd-formula
image-sync-formula
pxe-formula
tftp-formula
vsftpd-formula
If any package is missing, install missing package using zypper call

zypper install $package_name
and synchronize salt filesystem and salt modules

salt-run fileserver.update
salt '*' saltutil.sync_all
When all packages are present on central {susemgr} server saltboot runner needs to be manually configured by providing Salt API access to {susemgr} system.

/etc/salt/master.d/spacewalk.conf
spacewalk:
    localhost:
        username: $administration_user
        password: $administration_password
In order to avoid putting overall {susemgr} administration credentials to the configuration files, any administration account for given organization is sufficient.

exclamation
To finish configuration of central {susemgr} server, restart of salt master service is required. Restart salt master service now.

systemctl restart salt-master

Installation of branch servers
Branch servers are installed as regular SLES12SP3 system registered to {susemgr} via salt minion.

Images
Preparing customized image
Building
Standard OS Image building feature of {susemgr} is used. Images are built from customized Kiwi templates, as a starting point see SUSE provided OS Image templates.

Adapt these templates to contain all required software, branding, configurations. Refer to Kiwi Image System documentation for details how to work with Kiwi templates.

If you are creating Kiwi template from scratch, please make sure image/preferences/type elements attribute boot is set to saltboot/suse-SLES12

Once the image is build, it will be automatically transferred to {susemgr} server

[[retail.sect.running.setup]]
== Initial setup


Having installed and configured {smr} infrastructure, generic workflow is as follows:

build image to be deployed on terminals

synchronize images from {susemgr} server to branch servers

boot terminal
