[[retail.chap.admin]]
= Administration
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname:
:susemgr: SUSE Manager
:smr: SUSE Manager for Retail
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:webui: Web UI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images

// For the github environment we use cross references. These are only used with gh-pages, jekyll and browsing via github.
// Add a new installation document with methods for each type of installation(jeos, sles extension, ncurses etc.)
ifdef::env-github[]
// <<quickstart3_chap_install_overview.adoc#gs-overview, Overview>>
endif::[]

// For DAPS processing, Includes are not friendly with gh-pages, and jekyll due to default safe methods.
ifndef::env-github[]
// include::quickstart3_chap_install_overview.adoc[leveloffset=1]
endif::[]



[[retail.sect.admin]]
== Basic Administration




This section assumes:

central SUSE Manager is installed and configured

SUSE Manager for Retail formulas are present on central SUSE Manager

branch server is installed and registered using salt in central SUSE Manager

Branch server can be configured in many different ways. In this guide two widely used options are presented.

Branch server with dedicated LAN for terminals
In this configuration, Branch server has at least two network interfaces. One network interface connected to WAN with the central SUSE Manager server reachable. The other network interface is connected to isolated LAN which terminals are connected to.

Branch server is the provider of DHCP, DNS, TFTP, PXE and FTP services. These services are configured by respective SUSE Manager for Retail formulas. Enable these formulas for selected Branch server in SUSE Manager web user interface. For information how to do so, refer to bp_chap_getting_started_with_salt_formulas.adoc.

Branch Network formula for dedicated LAN
This formula configures networking of Branch server.

Keep Dedicated Nic checked

Enter name of the network device which is connected to the internal LAN

Static IP address to be assigned to Branch server on internal LAN

Network mask of the internal LAN

Check Enable route if you want Branch server to route traffic from internal LAN to WAN

Check Enable NAT if you want Branch server to translate addresses from internal LAN to WAN

Select DNS forwarder mode. Select bind to ensure Branch provided DNS can resolve WAN domain names

Check DNS forwarder fallback. Disable if you do not want to rely on external DNS if Branch DNS is down

Server directory specify working directory for SUSE Manager for Retail

Server directory user and group specify directory owner and group of SUSE Manager for Retail working directory

DHCPD
This formula configures DHCP service at Branch server

exclamation
Generic configuration
Listen interface must be the same entered in Branch Network formula

Domain Name Servers must be configured to point to Branch server

exclamation
Subnet configuration
Branch static IP address must be reachable from Network provided by DHCP service

Next server must be configured to point to Branch server

Be sure configured ranges match configured network and netmask

If terminals MAC addresses are known beforehand, host configuration can be specified for static IP address assignment.

If Branch server acts as a router for internal LAN, router option must point to Branch server.

Now continue at Common Branch server configuration

Branch server with shared network for terminals
In this configuration, Branch server has only one network interface card which is connected to network used to connect to central SUSE Manager as well as to terminals.

Branch server is provider of DNS, TFTP, PXE and FTP services. DHCP may or may not be provided by branch server.

exclamation
If DHCP service is not provided by Branch server, external DHCP configuration must contain:

next-server option must point to the Branch server for PXE boot to work

filename option must correctly identify network boot program (by default /boot/pxelinux)

domain-name-servers option must point to the Branch server for correct host name resolution

Branch Network formula for shared network
This formula configures networking of Branch server.

Keep Dedicated Nic unchecked

Select which services should be enabled on Branch server’s firewall.

exclamation
DNS, TFTP and FTP services should be enabled on Branch server’s firewall.
Select DNS forwarder mode. Select bind to ensure Branch provided DNS can resolve WAN domain names

Check DNS forwarder fallback. Disable if you do not want to rely on external DNS if Branch DNS is down

Server directory specify working directory for SUSE Manager for Retail

Server directory user and group specify directory owner and group of SUSE Manager for Retail working directory

Now continue at Common Branch server configuration

Common Branch server configuration
DNS
TFTP
PXE
VSFTP
Images synchronization
Synchronization is done by applying salt state 'image-sync'

Example of image synchronization call:
salt $branch_server_id state.apply image-sync
Image deployment configuration and terminal deployment
This section expects: - configured central SUSE Manager - configured branch server - saltboot PXE image

In order to deploy a terminal, several more configuration steps are required:

create a hardware type group for terminal hardware type

assign and configure saltboot formula for given SUSE Manager group

Before terminal is booted and registered for the first time, there is no system entry in SUSE Manager database. For this reason, hardware type groups are used to determine what image should be deployed on specific terminal.

Each terminal has a specific hardware type. This hardware type is constructed from SMBios information provided by terminal hardware and contain information about the manufacturer and product name.

information_source
Hardware type construction
Hardware type is a concatenation of system manufacturer and system product name using - as a delimiter.

Hardware type groups
Hardware type groups are regular SUSE Manager system groups with two important details.

Hardware type group follows very specific naming

Saltboot formula is assigned and configured

exclamation
Hardware type group naming
Hardware type groups follows naming:

prefix "HWTYPE:"

appendix is hardware type of the terminals

any spaces or non alphanumeric characters are removed (except delimiters _, -)

Example for system manufacturer 'POS Vendor' and system product name 'Terminal 1'. The resulting hardware type group is HWTYPE:POSVendor-Terminal1.

Saltboot formula
Once the correct hardware type group is created, saltboot formula must be enabled and configured for this group. Refer to bp_chap_getting_started_with_salt_formulas.adoc how to work with SUSE Manager formulas.

This formula specifies partitioning and image to deploy for given terminal hardware type.

Partitioning and Image assignment for specific hardware type
Partitioning and Image assignment for specific machine
First terminal boot
During first terminal boot salt minion id and fingerprint will be presented on the screen. Depending on the configuration, accepting terminal key on SUSE Manager may be required.

exclamation
Accept the terminal key only when information provided on terminal screen match those in SUSE Manager Main Menu › Salt › Keys
Terminal will now continue booting, download the image from branch server and deploy it on the machine. Then proceeds to boot deployed image
