[[retail.chap.admin]]
= Administration

include::entities.adoc[]



[[retail.sect.admin]]
== Administration

This sections contains notes on administering your {smr} installation.
For general administration tasks, see the {susemgr} documentation at https://www.suse.com/documentation/suse-manager-3/

[[retail.sect.admin.branch_network_config]]
== Branch Server Network Configuration

The branch server can be configured to use networking in many different ways.
The most common ways provide either a dedicated or shared LAN for terminals.


.Procedure: Set up a Branch Server with a Dedicated LAN

In this configuration, the branch server requires at least two network interfaces: one acts as a WAN to communicate with the central server, and the other one acts as an isolated LAN to communicate with terminals.
This configuration allows for the branch server to provide DHCP, DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` checked
* In the [guimenu]``NIC`` field, enter the name of the network device that is connected to the internal LAN.
* In the [guimenu]``IP`` field, enter the static IP address to be assigned to the branch server on the internal LAN.
* In the [guimenu]``Netmask`` field, enter the network mask of the internal LAN.
. Check [guimenu]``Enable Route`` if you want the branch server to route traffic from internal LAN to WAN.
* Check [guimenu]``Enable NAT`` if you want the branch server to convert addresses from internal LAN to WAN.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click [btn]``Save`` to save your changes.


.Procedure: Set up a Branch Server with a Shared Network

In this configuration, the branch server has only one network interface card which is used to connect to the central server as well as the terminals.
This configuration allows for the branch server to provide DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.
Optionally, the branch server can also provide DHCP services in this configuration.

[NOTE]
====
If DHCP services are not provided by the branch server, ensure that your external DHCP configuration is set correctly:
* The [systemitem]``next-server`` option must point to the branch server for PXE boot to work
* The [systemitem]``filename`` option must correctly identify the network boot program (by default, this is [path]``/boot/pxelinux``)
* The [systemitem]``domain-name-servers`` option must point to the branch server for correct host name resolution
====

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` unchecked
* Select which services to enable on the branch server’s firewall.
Ensure you include DNS, TFTP and FTP services.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click [btn]``Save`` to save your changes.
. Apply the salt state and synchronize your settings:
+
----
salt $branch_server_id state.apply image-sync
----



[[retail.sect.admin.branch_mass_config]]
== Branch Server Mass Configuration

You can either configure branch servers one by one using formulas (*TODO* see xxx) or create system groups of branch servers (*TODO* see yyy) or with a flexible command-line script.
Such a command-line script is suitable to do a mass configuration of branch servers.



// https://gitlab.suse.de/SLEPOS/SUMA_Retail/tree/master/python-susemanager-retail
For mass deployments use the script coming with the [package]``python-susemanager-retail`` package.
Install it on the central server.
When installed call it on the command-line with [command]``retail_yaml``.
This is the [command]``retail_yaml --help`` output:

----
usage: retail_yaml [-h] [--api-host API_HOST] [--api-user API_USER]
                   [--api-pass API_PASS] [--from-yaml FROM_YAML]
                   [--to-yaml TO_YAML]

Initialize Branch Server

optional arguments:
  -h, --help            show this help message and exit
  --api-host API_HOST   API host
  --api-user API_USER   API user
  --api-pass API_PASS   API password
  --from-yaml FROM_YAML
                        initialize retail system from YAML file
  --to-yaml TO_YAML     save structure of retail system to YAML file
----

The actual settings are filled in a ``YAML`` file that you will read with the [option]``--from-yaml`` option.
Here is the documentated [path]``example.yml`` coming with the package:

----
# /usr/share/doc/packages/python-susemanager-retail/example.yml
branches:
# there are 2 possible setups: with / without dedicated NIC
#
# with dedicated NIC
  branchserver1.branch1.cz:     # salt ID of branch server
    branch_prefix: branch1      # optional, default guessed from salt id
    server_name: branchserver1  # optional, default guessed from salt id
    server_domain: branch1.cz   # optional, default guessed from salt id
    dedicated_nic: eth1         # optional
    salt_ip: 10.100.24.130      # ip of salt master / broker for terminals, mandatory
    branch_ip: 192.168.2.1      # default for dedicated NIC: 192.168.1.1
    netmask: 255.255.255.0      # default for dedicated NIC: 255.255.255.0
    dyn_range:                  # default for dedicated NIC: 192.168.1.10 - 192.168.1.250
        - 192.168.2.10
        - 192.168.2.250

# without dedicated NIC
# the DHCP formula is not used, DHCP is typically provided by a router
# the network parameters can be autodetected if the machine is already connected to SUSE Manager
  branchserver2.branch2.cz:     # salt ID of branch server
    branch_prefix: branch2      # optional, default guessed from salt id
    server_name: branchserver2  # optional, default guessed from salt id
    server_domain: branch2.cz   # optional, default guessed from salt id
    salt_ip: 10.100.24.130      # ip of salt master / broker for terminals, mandatory
    branch_ip: 192.168.2.1      # optional, default taken from SUMA data if the machine is registered
    netmask: 255.255.255.0      # optional, default taken from SUMA data if the machine is registered


hwtypes:
  IBM CORPORATION-4838910:      # HWTYPE string (manufacturer-model) as returned by bios
    description: 4838-910       # freetext description
    saltboot:
      partitioning:             # partitioning pillar as described in saltboot documentation
        disk1:
          device: /dev/sda
          disklabel: msdos
          partitions:
            p1:
              flags: swap
              format: swap
              size_MiB: 1000.0
            p2:
              image: POS_Image_JeOS6
              mountpoint: /
          type: DISK
  TOSHIBA-6140100:
    description: HWTYPE:TOSHIBA-6140100
    saltboot:
      partitioning:
        disk1:
          device: /dev/sda
          disklabel: msdos
          partitions:
            p1:
              flags: swap
              format: swap
              size_MiB: 1000.0
            p2:
              image: POS_Image_JeOS6
              mountpoint: /
          type: DISK
----

For details about network settings and ``hwtypes`` related settings, see above.



[[retail.sect.admin.deploy_terminals]]
== Deploying Terminals

Each terminal requires a specific hardware type, which contains information about the product name and terminal manufacturer.
However, the {susemgr} database does not have this information to begin with.
In order to tell {susemgr} what image to deploy on each terminal, you can set hardware type groups.
After you have created your new hardware type group, you can apply the [systemitem]``saltboot-formula`` to the group and configure it for your environment.


.Procedure: Create a Hardware Type Group

For this procedure, you will require the system manufacturer name and product name for your terminal.

. Determine the hardware type group name.
Prefix the name with [systemitem]``HWTYPE:``, followed by the system manufacturer name and product name, separated by a hyphen.
For example:
+
----
HWTYPE:POSVendor-Terminal1
----
+
[NOTE]
====
Only use colons (``:``), hyphens (``-``) or underscores (``_``) in hardware type group names.
Spaces and other non-alphanumeric characters will be removed when the name is processed.
====
+
. In the {susemgr} {webui}, navigate to menu:Systems[Overview], and click on the [guimenu]``Groups`` tab.
. Click the [btn]``Create new`` button.
. In the [guimenu]``Create System Group`` dialog, create a new system group, using the hardware type group name you created earlier.


.Procedure: Apply and configure the Saltboot Formula

. Open the details page for your new hardware group, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``saltboot-formula`` and click [btn]``Save`` to save your changes.
. An additional [guimenu]``saltboot`` tab will become available from the top menu, click on it to configure the new formula.
+
[NOTE]
====
There are many different configurations possible.
This procedure outlines a simple, single-disk, three-partition configuration.
Adjust it to suit your own environment.
====
. In the [guimenu]``Disk 1`` section, set these parameters:
* In the [guimenu]``Disk symbolic ID`` field, enter a custom name for the disk (for example, [systemitem]``disk1``).
* In the [guimenu]``Device type`` field, select [systemitem]``DISK``.
* In the [guimenu]``Disk device`` field, select the device that corresponds to the device name on the target machine (for example, [path]``/dev/sda``).
* In the [guimenu]``RAID level`` field, leave it empty.
* In the [guimenu]``Disk Label`` field, select [systemitem]``gpt``.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 1``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p1``).
* In the [guimenu]``Partition size`` field, specify a size for the partition in Mebibytes (MiB).
* In the [guimenu]``Device mount point`` field, select a location to mount the partition (for example, [path]``/data``).
* In the [guimenu]``Filesystem format`` field, select your preferred format (for example, [systemitem]``xfs``).
* In the [guimenu]``OS Image to deploy`` field, leave it empty.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, leave it empty.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 2``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p2``).
* In the [guimenu]``Partition size`` field, specify a size for the partition in Mebibytes (MiB).
* In the [guimenu]``Device mount point`` field, leave it empty.
* In the [guimenu]``Filesystem format`` field, select [systemitem]``swap``.
* In the [guimenu]``OS Image to deploy`` field, leave it empty.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, select [systemitem]``swap``.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 3``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p3``).
* In the [guimenu]``Partition size`` field, leave it empty.
This will ensure the partition uses up all remaining space.
* In the [guimenu]``Device mount point`` field, select [systemitem]``/``.
* In the [guimenu]``Filesystem format`` field, leave it empty.
* In the [guimenu]``OS Image to deploy`` field, enter the name of the image to deploy.
* In the [guimenu]``Image version`` field, leave it empty.
This will ensure you use the latest available version.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, leave it empty.
. Click [btn]``Save Formula`` to save your formula.
. Apply highstate to apply your configuration changes.
Click [btn]``Apply Highstate``.
Applying highstate will execute the state associated with the formula and configure the affected systems.


[[retail.sect.admin.terminal_mass_config]]
== Terminal Mass Configuration

System profiles can be used to configure terminals before they are deployed.
This is particularly useful when you a large number of terminals that need to be configured in the same way.
In this procedure, you create an empty system profile with a network interface and a given hardware address using XMLRPC.
When a new machine connects using the specified hardware address, it is paired to the system profile and configured accordingly.

.Procedure: Configuring Multiple Terminals
. In the {susemgr} {webui}, navigate to menu:Systems[Overview].
. Locate the build host system, and click on the corresponding number in the [guimenu]``Packages`` column.
. Click on the [guimenu]``Profiles`` tab.
. Click on the [btn]``Create System Profile`` button.
. Give the system profile using the hardware address for your terminals, in the format:
+
----
hwaddress:01-23-45-67-89-AB
----
. Add a description and click [btn]``Save`` to save your profile.
By default, the new profile will have the [systemitem]``BOOTSTRAP`` entitlement, and a single network interface with the specified hardware address.
All other values are created as default values, and will be updated when the terminal connects.
. Boot the terminal with the matching hardware address.
The terminal pairs to the profile you have created, and configuration values are loaded.



////
Commenting this heading out until we have content for it. LKB
[[retail.sect.admin.troubleshooting]]
== Troubleshooting

TODO: https://github.com/SUSE/spacewalk/issues/5616
////
