[[retail_migr.chap.slepostosuma]]
= {slepos} 11 to {smr}


include::entities.adoc[]



[[retail_migr.sect.slepostosuma.s1]]
== Migration from {slepos} 11 to {smr}

This section describes migrating from an existing {slepos} 11 installation, to a new {susemgr} installation.  During this procedure, you will either dump the complete on the admin server in one session (see <<retail_migr.sect.slepostosuma.s1.complete>>) or dump the data branch by branch separately (see <<retail_migr.sect.slepostosuma.s1.bbb>>); similar approaches are available for importing and deploying the converted data.



[[retail_migr.sect.slepostosuma.s1.complete]]
=== Migration with Complete Data Dump

This procedure explains how you can migrate the SLEPOS infrastructure all at once.

. Install a {susemgr} server {productnumber} (with the Retail pattern).  For more information, see https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.install.html.

. On the SLEPOS Admin server export all your data stored in LDAP to an XML file.
Use the following command that relies on the admin credentials:
+
----
posAdmin --export --type xml --file dumpfile.xml
----
+
The resulting [literal]``dumpfile.xml`` file will contain global information, with parts about images, hardware and its partitioning, and the description of the branch servers with networking data, services, and attached terminals.

. Move the XML file to the {susemgr} server (see Step 1) and convert it to YAML:
+
----
retail_migration dumpfile.xml retail.yml
----

. Review the generated YAML file ([literal]``retail.yml``) and adjust it as necessary.
Consider ``HWTYPE`` group naming and image name and version changes in the partitioning data.
You can shorten the names as needed, and the image names must match the images in {susemgr}.
The [option]``--save-mapping`` option can help you with this task.
+
Also check whether there are duplicate MAC addresses of the terminals in the generated YAML file.
Choose which entry you want to keep.
As long as there are duplicate MAC addresses, {susemgr} will refuse importing the YAML file.
+
[NOTE]
====
{slepos} images will not be migrated. You must rebuild the images using the OS image building functionality.
For more information about building images, see https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-advanced-topics/html/book.suma.advanced.topics/at.images.html#at.images.kiwi.
====

. Import the complete data (YAML) with:
+
----
retail_yaml --from-yaml retail.yml
----
+
You can see statistical data while importing.  Then check the results in the {webui}. In menu:Main Menu[Systems > Systems > All], find empty profiles, and in menu:Main Menu[Systems > Groups], the groups for the hardware configuration, the branches, servers, and terminals.

After all the branches are migrated, shutdown and remove the old SLEPOS Admin Server.



[[retail_migr.sect.slepostosuma.s1.bbb]]
=== Migration with Branch by Branch Data Dump

This procedure explains how you can migrate the SLEPOS infrastructure and the branches one by one, exporting and then importing.

. Install a {susemgr} server {productnumber} (with the Retail pattern).  For more information, see https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.install.html.

. On every branch server:
----
posAdmin --export --type xml --file dumpfile.xml
----
+
These dumps will contain only the LDAP data of the branch plus the global data.
+
. Similarily, you can export the LDAP data of every branch if you run the command on the Admin server with the branch credentials explicitly specified:
+
----
posAdmin --export --type xml --file dumpfile.xml --user $branch_dn \
    --password $password
----
+
For background information about SLEPOS branch server configuration, see https://www.suse.com/documentation/slepos11/book_slepos/data/cha_slepos_branchserv.html.

The data can be imported branch by branch.
For each branch perform the following steps:

. Replace each old SLEPOS branch server with a {smr} branch server (see https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.install.html[Install Branch Server]) and connect it to the {smr} server (the same procedure as for https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.admin.html#retail.sect.admin.branch_mass_config[Branch Server Mass Configuration]).

. If you want to import one branch after the other from the YAML data instead of a complete import in one go, specify the wanted branch with:
+
----
retail_yaml --from-yaml retail.yml --branch <branch_name>
----
+
Repeat the command for every branch.

. Apply highstate on the branch server.

. Boot the terminals of the branch.

After all the branches are migrated, shutdown and remove the old SLEPOS Admin Server.



include::retail_migr_chap_slepostosumaind.adoc[leveloffset=1]
