[[retail.chap.admin]]
= Administration
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname:
:susemgr: SUSE Manager
:smr: SUSE Manager for Retail
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:webui: Web UI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images





[[retail.sect.admin]]
== Administration

This sections contains notes on administering your {smr} installation.

[[retail.sect.admin.branch_network_config]]
== Branch Server Network Configuration

The branch server can be configured to use networking in many different ways.
The most common ways provide either a dedicated or shared LAN for terminals.

.Procedure: Set up a Branch Server with a Dedicated LAN

In this configuration, the branch server requires at least two network interfaces: one acts as a WAN to communicate with the central server, and the other one acts as an isolated LAN to communicate with terminals.
This configuration allows for the branch server to provide DHCP, DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.

. In the {susemgr} {webui} for the branch server, go to menu:System Details[Formulas > Branch Network]
. Keep [guimenu]``Dedicated NIC`` checked
. Enter name of the network device which is connected to the internal LAN ([guimenu]``NIC``)
. Static IP address to be assigned to Branch server on internal LAN ([guimenu]``IP``)
. Network mask of the internal LAN ([guimenu]``Netmask``)
. Check [guimenu]``Enable Route`` if you want the branch server to route traffic from internal LAN to WAN
. Check [guimenu]``Enable NAT`` if you want the branch server to convert addresses from internal LAN to WAN
. Select DNS forwarder mode ([guimenu]``Forwarder``): select bind to ensure Branch provided DNS can resolve WAN domain names
. Check DNS forwarder fallback ([guimenu]``Forwarder Fallback``). Disable if you do not want to rely on external DNS if Branch DNS is down
. As [guimenu]``server directory`` specify working directory for {smr}
. As [guimenu]``server directory user`` and [guimenu]``server directory group`` specify directory owner and group of {smr} working directory



This formula (menu:System Details[Formulas > Dhcpd]) configures DHCP service at Branch server

Listen interface must be the same entered in Branch Network formula

Domain Name Servers must be configured to point to Branch server

Branch static IP address must be reachable from Network provided by DHCP service

Next server must be configured to point to Branch server

Be sure configured ranges match configured network and netmask

If terminals MAC addresses are known beforehand, host configuration can be specified for static IP address assignment.

If Branch server acts as a router for internal LAN, router option must point to Branch server.



.Procedure: Set up a Branch Server with a Shared Network

In this configuration, the branch server has only one network interface card which is used to connect to the central server as well as the terminals.
This configuration allows for the branch server to provide DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.
Optionally, the branch server can also provide DHCP services in this configuration.

[NOTE]
====
If DHCP services are not provided by the branch server, ensure that your external DHCP configuration is set correctly:
* The [systemitem]``next-server`` option must point to the branch server for PXE boot to work
* The [systemitem]``filename`` option must correctly identify the network boot program (by default, this is [path]``/boot/pxelinux``)
* The [systemitem]``domain-name-servers`` option must point to the branch server for correct host name resolution
====

. In the {susemgr} {webui} for the branch server, go to menu:System Details[Formulas > Branch Network]
. Keep [guimenu]``Dedicated NIC`` unchecked
. Select which services should be enabled on Branch server’s firewall. Ensure you include DNS, TFTP and FTP services.
. Select DNS forwarder mode. Select bind to ensure Branch provided DNS can resolve WAN domain names
. Check DNS forwarder fallback. Disable if you do not want to rely on external DNS if Branch DNS is down
. Server directory specify working directory for {smr}
. Server directory user and group specify directory owner and group of {smr} working directory


Synchronization is done by applying salt state 'image-sync'

Example of image synchronization call:
salt $branch_server_id state.apply image-sync


[[retail.sect.admin.deploy_terminals]]
== Deploying Terminals

TODO: https://github.com/SUSE/spacewalk/issues/5613

Each terminal requires a specific hardware type, which contains information about the product name and terminal manufacturer.
However, the {susemgr} database does not have this information to begin with.
In order to tell {susemgr} what image to deploy on each terminal, you can set hardware type groups.


.Procedure: Create a Hardware Type Group

For this procedure, you will require the system manufacturer name and product name for your terminal.

. Determine the hardware type group name.
Prefix the name with [systemitem]``HWTYPE:``, followed by the system manufacturer name and product name, separated by a hyphen.
For example:
+
----
HWTYPE:POSVendor-Terminal1
----
+
[NOTE]
====
Only use colons (``:``), hyphens (``-``) or underscores (``_``) in hardware type group names.
Spaces and other non-alphanumeric characters will be removed when the name is processed.
====
+
. TODO: Another step


TODO: Possibly https://gitlab.suse.de/SLEPOS/SLEPOS/blob/master/doc/devel/howto-add_terminal.txt ??


[[retail.sect.admin.saltboot]]
== Saltboot

TODO: https://github.com/SUSE/spacewalk/issues/5614

After you have created a hardware type group, you will need to enable and configure the saltboot formula.

.Procedure: Working with Salt Formulas

Default formulas are supplied with {smr} and can be installed as RPM packages.

. Download the formula RPM to your system.
Save the formula custom states to [path]``/srv/salt/your-formula-name/``.
Save the metadata files ([path]``form.yaml`` and [path]``metadata.yml``) to [path]``/srv/formula_metadata/your-formula-name/``.
. Check that your formula has been installed correctly.
In the {susemgr} {webui}, navigate to menu:Salt[Formula Catalog] and check that your new formula appears in the list.
. Open the details page for the group or system you want to apply the formula to, and navigate to the [guimenu]``Formulas`` tab.
. Select the formulas you want to apply to the group or system and click [btn]``Save`` to save your changes.

After applying one or more formulas to a group or system, additional tabs will become available from the top menu, one for each formula selected.
These tabs give you specific configuration options for each formula.

When you have finished customizing your formula values you will need to apply highstate for them to take effect.
Do this by clicking [btn]``Apply Highstate`` from any formulas page.
Applying highstate will execute the state associated with the formula and configure the affected systems.

If you need to change any values, or re-apply formulas because of a failure, make the changes in the [guimenu]``Formulas`` tab, save your changes, and re-apply the highstatee.
Salt will ensure that only modified values are adjusted and restart or reinstall services only when necessary.

For additional information about Salt formulas, see: https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html



[[retail.sect.admin.image_building]]
== Image Building

TODO: https://github.com/SUSE/spacewalk/issues/5612

￼ setting root user (or other users), see docu of SLEPOS
￼ note that image needs to stay on the same SUMA instance
￼ point to the git repository with examples, describe how to use it


[[retail.sect.admin.troubleshooting]]
== Troubleshooting

TODO: https://github.com/SUSE/spacewalk/issues/5616
