[[retail.chap.install]]
= Installation
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname:
:susemgr: SUSE Manager
:smr: SUSE Manager for Retail
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:webui: Web UI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images



[[retail.sect.running.requirements]]
== Requirements

Before you install {smr}, ensure your environment meets the minimum requirements:


[IMPORTANT]
====
{smr} is only supported on {x86_64} architecture.
====


.Network Requirements

* The central server requires a reliable and fast WAN connection
* The Branch server requires a reliable WAN connection in order to reach the central server
* If you are using a shared network, ensure that your router and firewall can filter DHCP requests between the shared network annd the WAN
* If you are using a dedicated network, the branch server requires at least two network interfaces: one connected to the WAN with reachable central server, and one connected to the internal branch LAN.
* Terminals require a LAN connection to the branch server network.



[[retail.sect.running.install]]
== Installation


Most {smr} installations require several steps:

. Install and configure the central server
. Install the {smr} pattern on the central server
. Install the build host and register it to {susemgr}
. Configure the build host
. Install the branch server and register it to {susemgr}
. Assign and configure branch server formulas

Each procedure is detailed in this section.

.Procedure: Install and configure the central server

Refer to [quickstart3_chap_install_overview.adoc] for instructions to install {susemgr}.

{smr} uses formulas to simplify configuration, which require packages to operate correctly.

. Check that you have these packages installed and available, after installing {susemgr}:

* bind-formula
* branch-network-formula
* dhcpd-formula
* image-sync-formula
* pxe-formula
* tftp-formula
* vsftpd-formula
+
Install any missing packages with [command]``zypper``:
+
----
zypper install package_name
----
. Synchronize the salt filesystem and salt modules:
+
----
salt-run fileserver.update
salt '*' saltutil.sync_all
----
. Grant the Salt API access to the central server, by opening the [filename]``/etc/salt/master.d/spacewalk.conf`` file in your preferred text editor, and adding your administration credentials in the [systemitem]``spacewalk`` section:
+
----
spacewalk:
    localhost:
        username: $administration_user
        password: $administration_password
----
+
[IMPORTANT]
====
We recommend that do not put your master {susemgr} administration credentials in plain text in the configuration file.
Instead, use the credentials for an administration account for any organization.
This allows you to more easily change the password, should it become compromised.
====

. Restart the salt master service to pick up the changes:
+
----
Restart salt master service now.

systemctl restart salt-master
----

.Procedure: Install the {smr} pattern on the central server
. Step one
. Another step

.Procedure: Install the build host and register it to {susemgr}
. Step one
. Another step

.Procedure: Configure the build host

The build host must be set as an OS Image build host in the {susemgr} {webui}, and highstate applied.

. In the {susemgr} {webui}, navigate to menu:Systems[Overview].
Locate the system to be made a build host, and click on its name.
. In the [guimenu]``System Properties`` window, click [btn]``Edit These Properties``.
. In the [guimenu]``Edit System Details`` window, ensure the [guimenu]``OS Image Build Host`` option is checked, and click [btn]``Update Properties`` to save your changes.
. Select the [guimenu]``States`` tab, and navigate to the [guimenu]``Highstate`` window.
. Click the [btn]``Apply Highstate`` button.


.Procedure: Install the branch server and register it to {susemgr}
. Step one
. Another step

.Procedure: Assign and configure branch server formulas
TODO: https://github.com/SUSE/spacewalk/issues/5610

. Set the branch server hostname and CNAME aliases, so that services can reach the branch server accurately.
. Check each formula to ensure the values are appropriate for your environment.
. Configure the branch server network.
This will vary depending on your preferred topology.
See [retail.chap.admin] for more information.



[[retail.sect.running.setup]]
== Initial setup


To get started with {smr} after installation, perform these steps:

. Build the image that will be deployed on terminals
. Synchronize images from the central server to the branch servers
. Boot terminals

Each procedure is detailed in this section.

.Procedure: Build the image that will be deployed on terminals
. Step one
. Another step

.Procedure: Synchronize images from the central server to the branch servers
. Step one
. Another step

.Procedure: Boot terminals
. Step one
. Another step
