[[retail.chap.install]]
= Installation

ifdef::env-github,backend-html5,backend-docbook5[]

include::entities.adoc[]



[[retail.sect.running.requirements]]
== Requirements

Before you install {smr}, ensure your environment meets the minimum requirements.
This section lists the requirements for your {smr} installation.
These requirements are in addition to the {susemgr} requirements listed at
xref:quickstart3_chap_install_overview.adoc#quickstart.sect.prereq.hardware[Hardware Prerequisites]
and
xref:advanced_topics_proxy_quickstart.adoc#at.manager.proxy.requirements[Proxy Requirements].

[IMPORTANT]
====
{smr} is only supported on {x86_64} architecture.
====


.Central Server Requirements

* {x86_64} processor
* A minimum of 4{nbsp}GB hard disk space (recommended 15{nbsp}GB)
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Build Host Requirements

* {x86_64} processor
* A minimum of 8{nbsp}GB hard disk space (recommended 25{nbsp}GB)
 terminals.
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Branch Server Requirements

* {x86_64} processor
* A minimum of 4{nbsp}GB hard disk space (recommended 10{nbsp}GB)
 terminals.
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Network Requirements

* The central server requires a reliable and fast WAN connection
* The branch server requires a reliable WAN connection, to reach the central server
* If you are using a shared network, ensure that DHCP requests are filtered before reaching the rest of your shared network
* If you are using a dedicated network, the branch server requires at least two network interfaces: one connected to the WAN with reachable central server, and one connected to the internal branch LAN.
* Terminals require a LAN connection to the branch server network.



[[retail.sect.running.install]]
== Installation

Most {smr} installations require several steps:

. Install the central server
. Configure the central server
. Install the {smr} pattern on the central server
. Install the build host and register it to {susemgr}
. Configure the build host
. Install the branch server and register it to {susemgr}
. Assign and configure branch server formulas

Each procedure is detailed in this section.



=== Procedure Install the Central Server

For instructions to install {susemgr}, see the xref:quickstart3_chap_install_overview.adoc[{susemgr} Getting Started Guide].

{smr} uses formulas to simplify configuration, which are installed as RPM packages.

. Check that you have these packages installed and available, after installing {susemgr}:

* bind-formula
* branch-network-formula
* dhcpd-formula
* image-sync-formula
* pxe-formula
* susemanager-retail-tools
* tftp-formula
* vsftpd-formula
+
Install any missing packages with [command]``zypper``:
+
----
zypper install package_name
----
. Synchronize the salt filesystem and salt modules:
+
----
salt-run fileserver.update
salt '*' saltutil.sync_all
----
. Grant the Salt API access to the central server, by opening the [filename]``/etc/salt/master.d/spacewalk.conf`` file in your preferred text editor, and adding your administration credentials in the [systemitem]``spacewalk`` section:
+
----
spacewalk:
    localhost:
        username: $administration_user
        password: $administration_password
----
+
[IMPORTANT]
====
We recommend that do not put your master {susemgr} administration credentials in plain text in the configuration file.
Instead, use the credentials for an administration account for any organization.
This allows you to more easily change the password, should it become compromised.
====

. Restart the salt master service to pick up the changes:
+
----
Restart salt master service now.

systemctl restart salt-master
----



=== Procedure Configure the central server

Default formulas are supplied with {smr}, and should be installed automatically.

In the {susemgr} {webui}, navigate to menu:Salt[Formula Catalog] and check that the required formula appears in the list.
. Open the details page for the group or system you want to apply the formula to, and navigate to the [guimenu]``Formulas`` tab.
. Select the formulas you want to apply to the group or system and click btn:[Save] to save your changes.

After applying one or more formulas to a group or system, additional tabs will become available from the top menu, one for each formula selected.
These tabs give you specific configuration options for each formula.

When you have finished customizing your formula values you will need to apply highstate for them to take effect.
In the [guimenu]``States`` tab, click btn:[Apply Highstate].
Applying highstate will execute the state associated with the formula and configure the affected systems.

If you need to change any values, or re-apply formulas because of a failure, make the changes in the [guimenu]``Formulas`` tab, save your changes, and re-apply the highstate.
Salt will ensure that only modified values are adjusted and restart or reinstall services only when necessary.

For additional information about Salt formulas, see: https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html



=== Procedure Install the {smr} pattern on the central server

. Install the [package]``SUSE Manager for Retail`` pattern on the central server:
+
----
zypper in -t pattern suma_retail
----



=== Procedure Install the build host and register it to {susemgr}

Your build host should be a Salt minion, running {sls}{nbsp}12 SP3.
See [quickstart3_chap_suma_keys_and_first_clients.adoc] for instructions to install Salt minions and register them to {susemgr}.


=== Procedure Configure the build host

The build host must be set as an OS Image build host in the {susemgr} {webui}, and highstate applied.

. In the {susemgr} {webui}, navigate to menu:Systems[Overview].
Locate the system to be made a build host, and click on its name.
. In the [guimenu]``System Properties`` window, click btn:[Edit These Properties].
. In the [guimenu]``Edit System Details`` window, ensure the [guimenu]``OS Image Build Host`` option is checked, and click btn:[Update Properties] to save your changes.
. Select the [guimenu]``States`` tab, and navigate to the [guimenu]``Highstate`` window.
. In the [guimenu]``States`` tab, click btn:[Apply Highstate].



=== Procedure Install the branch server and register it to {susemgr}

Your branch server should be installed as a default Salt-based client ("minion"), running {susemgrproxy} 3.2.
Do not install it as a traditionally managed client.

[WARNING]
.Do Not Enable PXE Boot
====
Do not enable PXE boot functionality on the {susemgrproxy} during initial setup.
This functionality will be installed later, after the initial setup.
====


[IMPORTANT]
====
First completely download the channels and then create the activation key.
Only then you can select the correct child channels.
Here is a channel overview for {susemgrproxy}:
----
- SLES 12 SP3 (SP4 in the future) as a base
  - SLES Pool
    - SLES Update
- SUSE Manager 3.2 Proxy
  - SUSE Manager 3.2 Proxy Pool
    - SUSE Manager 3.2 Proxy Update
- SUSE Manager 3.2 Proxy for Retail
  - SUSE Manager 3.2 Proxy for Retail Pool
    - SUSE Manager 3.2 Proxy for Retail Update
----
====

For instructions to install Salt-based proxy minions and register them to {susemgr}, see xref:advanced_topics_proxy_quickstart.adoc#at.manager.proxy.inst[{susemgr} Advanced Topics].


For mass deployments, see xref:#retail.sect.admin.branch_mass_config[Branch Server Mass Configuration].



=== Procedure Assign and configure branch server formulas

Before you configure the branch server formulas, ensure you have configured networking, and know the Salt ID of the branch server.

. Branch server configuration is performed using the [command]``retail_branch_init`` command:
+
----
retail_branch_init <branch_server_salt_id>
----
+
If you need to specify values for your architecture, use:
+
----
retail_branch_init <branch_server_salt_id> --dedicated-nic eth1 --branch-ip 192.168.10.1 --netmask 255.255.255.0 --dyn-range 192.168.10.50 192.168.10.100
----
+
You can use the [command]``retail_branch_init --help`` command for additional options.
. Verify that your changes have been configured correctly by checking the {susemgr} {webui}.
