[[retail.chap.admin]]
= Administration

include::entities.adoc[]



[[retail.sect.admin]]
== Administration

This sections contains notes on administering your {smr} installation.
For general administration tasks, see the {susemgr} documentation at https://www.suse.com/documentation/suse-manager-3/



[[retail.sect.admin.branch_network_config]]
== Branch server network configuration

The branch server can be configured to use networking in many different ways.
The most common ways provide either a dedicated or shared LAN for terminals.



=== Set up a branch server with a dedicated LAN

In this configuration, the branch server requires at least two network interfaces: one acts as a WAN to communicate with the {susemgr} server, and the other one acts as an isolated LAN to communicate with terminals.

This configuration allows for the branch server to provide DHCP, DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.

.Procedure: Setting up a branch server with a dedicated LAN

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` checked
* In the [guimenu]``NIC`` field, enter the name of the network device that is connected to the internal LAN.
* In the [guimenu]``IP`` field, enter the static IP address to be assigned to the branch server on the internal LAN.
* In the [guimenu]``Netmask`` field, enter the network mask of the internal LAN.
. Check [guimenu]``Enable Route`` if you want the branch server to route traffic from internal LAN to WAN.
* Check [guimenu]``Enable NAT`` if you want the branch server to convert addresses from internal LAN to WAN.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click btn:[Save] to save your changes.
. Apply the highstate.



=== Set up a branch server with a shared network

In this configuration, the branch server has only one network interface card which is used to connect to the {susemgr} server as well as the terminals.

This configuration allows for the branch server to provide DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.
Optionally, the branch server can also provide DHCP services in this configuration.

[NOTE]
====
If DHCP services are not provided by the branch server, ensure that your external DHCP configuration is set correctly:
* The [systemitem]``next-server`` option must point to the branch server for PXE boot to work
* The [systemitem]``filename`` option must correctly identify the network boot program (by default, this is [path]``/boot/pxelinux``)
* The [systemitem]``domain-name-servers`` option must point to the branch server for correct host name resolution
====

.Procedure: Setting up a branch server with a shared network

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` unchecked
* Select which services to enable on the branch server’s firewall.
Ensure you include DNS, TFTP and FTP services.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click btn:[Save] to save your changes.
. Apply the highstate.



[[retail.sect.admin.branch_mass_config]]
== Branch server mass configuration

Branch servers are configured individually using formulas.
If you are working in an environment with many branch servers, you might find it easier to configure the terminals automatically with a pre-defined configuration file, rather than configuring each branch server individually.

// https://gitlab.suse.de/SLEPOS/SUMA_Retail/tree/master/python-susemanager-retail



=== Configure multiple branch servers

This procedure requires the [package]``python-susemanager-retail`` package, which is provided with {smr}.
Install the [package]``python-susemanager-retail`` package on the {susemgr} server.

.Procedure: Configuring multiple branch servers

. Create a YAML file describing the infrastructure you intend to install.
An example YAML file is at the end of this chapter, for you to reference.
. On a clean {susemgr} installation, import the YAML file you have created:
+
----
retail_yaml --from-yaml filename.yaml
----
You can use the [command]``retail_yaml --help`` command for additional options.

If you need to change your configuration, you can edit the YAML file at any time, and use the [command]``retail_yaml --from-yaml`` command to upload the new configuration.


[[retail.sect.admin.deploy_terminals]]
== Deploying terminals

Before terminals can be deployed, ensure you have prepared a saltboot based OS image.
For how to build OS images, see xref:advanced_topics_image_management.adoc#at.images.kiwi[OS image building].

Each terminal requires a specific hardware type, which contains information about the product name and terminal manufacturer.
However, the {susemgr} database does not have this information to begin with.
In order to tell {susemgr} what image to deploy on each terminal, you can set hardware type groups.
After you have created your new hardware type group, you can apply the [systemitem]``saltboot-formula`` to the group and configure it for your environment.

After you have registered new terminals, always check the {susemgr} {webui} to ensure your terminal has connected successfully to the branch server, and you have not connected directly to the {susemgr} server by mistake.



=== Create a Hardware Type group

For this procedure, you will require the system manufacturer name and product name for your terminal.

.Procedure: Creating a Hardware Type group

. Determine the hardware type group name.
Prefix the name with [systemitem]``HWTYPE:``, followed by the system manufacturer name and product name, separated by a hyphen.
For example:
+
----
HWTYPE:POSVendor-Terminal1
----
+
[IMPORTANT]
====
Only use colons (``:``), hyphens (``-``) or underscores (``_``) in hardware type group names.
Spaces and other non-alphanumeric characters will be removed when the name is processed.
====
+
. In the {susemgr} {webui}, navigate to menu:Systems[Overview], and click on the [guimenu]``Groups`` tab.
. Click the btn:[Create new] button.
. In the [guimenu]``Create System Group`` dialog, create a new system group, using the hardware type group name you created earlier.



=== Configure the Saltboot formula

.Procedure: Configuring the Saltboot formula

. Open the details page for your new hardware group, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``saltboot-formula`` and click btn:[Save] to save your changes.
. An additional [guimenu]``saltboot`` tab will become available from the top menu, click on it to configure the new formula.
+
[NOTE]
====
There are many different configurations possible.
This procedure outlines a simple, single-disk, three-partition configuration.
Adjust it to suit your own environment.
====
. In the [guimenu]``Disk 1`` section, set these parameters:
* In the [guimenu]``Disk symbolic ID`` field, enter a custom name for the disk (for example, [systemitem]``disk1``).
* In the [guimenu]``Device type`` field, select [systemitem]``DISK``.
* In the [guimenu]``Disk device`` field, select the device that corresponds to the device name on the target machine (for example, [path]``/dev/sda``).
* In the [guimenu]``RAID level`` field, leave it empty.
* In the [guimenu]``Disk Label`` field, select [systemitem]``gpt``.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 1``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p1``).
* In the [guimenu]``Partition size`` field, specify a size for the partition in Mebibytes (MiB).
* In the [guimenu]``Device mount point`` field, select a location to mount the partition (for example, [path]``/data``).
* In the [guimenu]``Filesystem format`` field, select your preferred format (for example, [systemitem]``xfs``).
* In the [guimenu]``OS Image to deploy`` field, leave it empty.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, leave it empty.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 2``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p2``).
* In the [guimenu]``Partition size`` field, specify a size for the partition in Mebibytes (MiB).
* In the [guimenu]``Device mount point`` field, leave it empty.
* In the [guimenu]``Filesystem format`` field, select [systemitem]``swap``.
* In the [guimenu]``OS Image to deploy`` field, leave it empty.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, select [systemitem]``swap``.
. In the [guimenu]``Partition`` section, set these parameters for [guimenu]``Partition 3``:
* In the [guimenu]``Partition symbolic ID`` field, enter a custom name for the partition (for example, [systemitem]``p3``).
* In the [guimenu]``Partition size`` field, leave it empty.
This will ensure the partition uses up all remaining space.
* In the [guimenu]``Device mount point`` field, select [systemitem]``/``.
* In the [guimenu]``Filesystem format`` field, leave it empty.
* In the [guimenu]``OS Image to deploy`` field, enter the name of the image to deploy.
* In the [guimenu]``Image version`` field, leave it empty.
This will ensure you use the latest available version.
* In the [guimenu]``Partition encryption password`` field, enter a password if you want to encrypt the partition.
* In the [guimenu]``Partition flags`` field, leave it empty.
. Click btn:[Save Formula] to save your formula.



[[retail.sect.admin.terminal_naming]]
== Terminal Names

In the {susemgr} {webui}, terminals have a standard naming format which allows you to match the physical device with its record.
By default, the name uses this format:

----
BranchName.Manufacturer-ProductName-SerialNumber-MachineID
----

For example:

----
B002.TOSHIBA-6140100-41BA03X-c643
----

You can adjust this behaviour by toggling the [systemitem]``DISABLE_HOSTNAME_ID`` and [systemitem]``DISABLE_UNIQUE_SUFFIX`` parameters in the PXE formula settings.
For more information about the PXE formula, see xref:retail.chap.formulas.adoc#retail.sect.formulas.pxe[PXE Formula].




[[retail.sect.admin.terminal_mass_config]]
== Terminal mass configuration

If you are working in an environment with many terminals, you might find it easier to configure the terminals automatically with a pre-defined configuration file, rather than configuring each terminal individually.

In order to do this, you will need to have your infrastructure planned out ahead of time, including the IP addresses, hostnames, and domain names of branch servers and terminals.
You will also require the hardware (MAC) addresses of each terminal.

[NOTE]
====
The settings specified in the configuration file cannot always be successfully applied.
In cases where there is a conflict, {susemgr} will ignore the request in the file.
This is especially important when designating hostnames.
You should always check the details have been applied as expected after using this configuration method.
====


=== Configure multiple terminals

.Procedure: Configuring multiple terminals

. Create a YAML file describing the infrastructure you intend to install, specifying the hardware address for each terminal.
An example YAML file is at the end of this chapter, for you to reference.
. On a clean {susemgr} installation, import the YAML file you have created:
+
----
retail_yaml --from-yaml filename.yaml
----
+
You can use the [command]``retail_yaml --help`` command for additional options.
. In the {susemgr} {webui}, check that your systems are listed and displaying correctly, and the formulas you require are available.
. Create activation keys for each of your branch servers, connect them using bootstrap, and configure them as proxy servers.
For further information on these steps, see the {susemgr} documentation.
. Apply highstate to apply your configuration changes.
In the [guimenu]``States`` tab, click btn:[Apply Highstate].
. Connect your terminals according to your infrastructure plan.


If you need to change your configuration, you can edit the YAML file at any time, and use the [command]``retail_yaml --from-yaml`` command to upload the new configuration.

If you have a current configuration that you would like to export to a YAML file, use:
----
retail_yaml --to-yaml filename.yaml
----
This can be a good way to create a basic mass configuration file, however it is important to check the file before using it, as some mandatory configuration entries will be missing.

[IMPORTANT]
====
When you are designing your configuration and creating the YAML file, ensure the branch server ID matches the fully qualified hostname, and the Salt ID.
If these do not match, the bootstrap script could fail.
====



== Example YAML file for mass configuration

// Ensure this section stays at the end of the chapter, its location is referenced earlier in this file. -LKB

You can use the [command]``retail_yaml`` command to import configuration parameters from a pre-prepared YAML file.
This section contains a commented example YAML file for you to reference.

.Example: YAML mass terminal configuration file
----
branches:
# there are 2 possible setups: with / without dedicated NIC
#
# with dedicated NIC
  branchserver1.branch1.cz:     # salt ID of branch server
    branch_prefix: branch1      # optional, default guessed from salt id
    server_name: branchserver1  # optional, default guessed from salt id
    server_domain: branch1.cz   # optional, default guessed from salt id
    nic: eth1                   # nic used for connecting terminals, default taken from hw info in SUMA
    dedicated_nic: true         # set to true if the terminals are on separate network
    salt_cname: branchserver1.branch1.cz      # hostname of salt master / broker for terminals, mandatory
    configure_firewall: true    # modify firewall configuration
    branch_ip: 192.168.2.1      # default for dedicated NIC: 192.168.1.1
    netmask: 255.255.255.0      # default for dedicated NIC: 255.255.255.0
    dyn_range:                  # default for dedicated NIC: 192.168.1.10 - 192.168.1.250
        - 192.168.2.10
        - 192.168.2.250
# without dedicated NIC
# the DHCP formula is not used, DHCP is typically provided by a router
# the network parameters can be autodetected if the machine is already connected to SUSE Manager
  branchserver2.branch2.cz:     # salt ID of branch server
    branch_prefix: branch2      # optional, default guessed from salt id
    server_name: branchserver2  # optional, default guessed from salt id
    server_domain: branch2.cz   # optional, default guessed from salt id
    salt_cname: branchserver2.branch1.cz      # FQDN of salt master / broker for terminals, mandatory
    branch_ip: 192.168.2.1      # optional, default taken from SUMA data if the machine is registered
    netmask: 255.255.255.0      # optional, default taken from SUMA data if the machine is registered
    exclude_formulas:           # optional, do not configure listed formulas
      - dhcp                    # without dedicated NIC the dhcp service is typically provided by a router
    hwAddress: 11:22:33:44:55:66 # optional, required to connect pre-configured entry with particular machine
                                 # during onboarding
    terminals:                       # configuration of static terminal entries
      hostname1:                     # hostname
        hwAddress: aa:aa:aa:bb:bb:bb # required as unique id of a terminal
        IP: 192.168.2.50             # required for static dhcp and dns entry
        saltboot:                    # optional, alternative 1: configure terminal-specific pillar data
          partitioning:              # partitioning pillar as described in saltboot documentation
            disk1:
              device: /dev/sda
              disklabel: msdos
              partitions:
                p1:
                  flags: swap
                  format: swap
                  size_MiB: 2000.0
                p2:
                  image: POS_Image_JeOS6
                  mountpoint: /
              type: DISK
      hostname2:                     # hostname
        hwAddress: aa:aa:aa:bb:bb:cc # required as unique id of a terminal
        IP: 192.168.2.51             # required for static dhcp and dns entry
        hwtype: IBMCORPORATION-4838910 # optional, alternative 2: assign the terminal to hwtype group
        # if neither of hwtype nor saltboot is specified, a group is assigned according to hwtype
        # reported by bios on the first boot
hwtypes:
  IBMCORPORATION-4838910:      # HWTYPE string (manufacturer-model) as returned by bios
    description: 4838-910       # freetext description
    saltboot:
      partitioning:             # partitioning pillar as described in saltboot documentation
        disk1:
          device: /dev/sda
          disklabel: msdos
          partitions:
            p1:
              flags: swap
              format: swap
              size_MiB: 1000.0
            p2:
              image: POS_Image_JeOS6
              mountpoint: /
          type: DISK
  TOSHIBA-6140100:
    description: HWTYPE:TOSHIBA-6140100
    saltboot:
      partitioning:
        disk1:
          device: /dev/sda
          disklabel: msdos
          partitions:
            p1:
              flags: swap
              format: swap
              size_MiB: 1000.0
            p2:
              image: POS_Image_JeOS6
              mountpoint: /
          type: DISK
----



////
Commenting this heading out until we have content for it. LKB
[[retail.sect.admin.troubleshooting]]
== Troubleshooting

TODO: https://github.com/SUSE/spacewalk/issues/5616
////
