[[retail.chap.formulas]]
= Formulas

include::entities.adoc[]


Formulas are pre-written Salt states, that are used to configure your {smr} installation.

This section lists the primary formulas shipped with {smr} and their configuration options.


.State and formula name collisions
[IMPORTANT]
====
If a formula uses the same name as an existing Salt state, the two names will collide, and could result in the formula being used instead of the state.
Always check the names of states and formulas to avoid name collisions.
====

Most formulas can be updated using the {susemgr} {webui}.
Once you have made changes to your formula, ensure you apply the highstate to propagate your changes to the appropriate services.


// We should ensure these are in alphabetical order. LKB

[[retail.sect.formulas.branch-network]]
== Branch Network Formula

The branch network formula is used to configure the networking services required by the branch server, including DHCP, DNS, TFTP, PXE, and FTP.

The branch server can be configured to use networking in many different ways.
The most common ways provide either a dedicated or shared LAN for terminals.



=== Set up a branch server with a dedicated LAN

In this configuration, the branch server requires at least two network interfaces: one acts as a WAN to communicate with the {susemgr} server, and the other one acts as an isolated LAN to communicate with terminals.

This configuration allows for the branch server to provide DHCP, DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.


.Procedure: Setting up a branch server with a dedicated LAN

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` checked
* In the [guimenu]``NIC`` field, enter the name of the network device that is connected to the internal LAN.
* In the [guimenu]``IP`` field, enter the static IP address to be assigned to the branch server on the internal LAN.
* In the [guimenu]``Netmask`` field, enter the network mask of the internal LAN.
. Check [guimenu]``Enable Route`` if you want the branch server to route traffic from internal LAN to WAN.
* Check [guimenu]``Enable NAT`` if you want the branch server to convert addresses from internal LAN to WAN.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click btn:[Save] to save your changes.
. Apply the highstate.



=== Set up a branch server with a shared network

In this configuration, the branch server has only one network interface card, which is used to connect to the {susemgr} server as well as the terminals.

This configuration allows for the branch server to provide DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.
Optionally, the branch server can also provide DHCP services in this configuration.

[NOTE]
====
If DHCP services are not provided by the branch server, ensure that your external DHCP configuration is set correctly:
* The [systemitem]``next-server`` option must point to the branch server for PXE boot to work
* The [systemitem]``filename`` option must correctly identify the network boot program (by default, this is [path]``/boot/pxelinux``)
* The [systemitem]``domain-name-servers`` option must point to the branch server for correct host name resolution
====


.Procedure: Setting up a branch server with a shared network

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` unchecked
* Select which services to enable on the branch server’s firewall.
Ensure you include DNS, TFTP and FTP services.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click btn:[Save] to save your changes.
. Apply the highstate.



[[retail.sect.formulas.image-sync]]
== Image Sync Formula

The image sync formula is used to configure how images are synchronized to the branch server.


.Procedure: Configuring image synchronization

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Pxe`` formula, and click [btn]``Save``.
. Navigate to the menu:Formulas[Pxe] tab, and set these parameters:
* In the [guimenu]``Kernel filename`` field, keep the default value.
* In the [guimenu]``Initrd filename`` field, keep the default value.
* In the [guimenu]``Kernel commandline parameters`` field, keep the default value.
* In the [guimenu]``PXE root directory`` field, enter the path to the saltboot directory (for example, [systemitem]``/srv/saltboot``).
* In the [guimenu]``Branch id`` field, type a name to use as a branch identifier (for example: [systemitem]``Branch0001``).
Use only alphanumeric characters for the branch identifier.
. Click [btn]``Save Formula`` to save your configuration
. Apply the highstate.



[[retail.sect.formulas.pxe]]
== PXE Formula

The PXE formula is used to configure PXE booting on the branch server.


.Procedure: Configuring PXE booting
. Step One
. Step Two
. Another step
////
Kernel filename:
Initrd filename:
Kernel commandline parameters:
PXE root directory:
Branch id:
////



[[retail.sect.formulas.saltboot]]
== Saltboot Formula

The Saltboot formula is used to configure the boot image on a terminal.


.Procedure: Configuring a retail branch server with saltboot

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab￼.
. Check the [systemitem]``Bind`` formula, and click [btn]``Save``.
. Navigate to the menu:Formulas[Bind] tab, and set these parameters for Zone1:
* In the [guimenu]``Config`` section, select [systemitem]``Include Forwarders``.
* In the [guimenu]``Name`` field, use the fully qualified domain name (FQDN) of the  branch server (for example: [systemitem]``branch1.mycompany.org``).
* In the [guimenu]``Type`` field, select [systemitem]``master``.
. Click [btn]``Add item`` to save your changes.
. Set these parameters for Zone2:
* In the [guimenu]``Name`` field, use the reverse zone for the configured IP range (for example: [systemitem]``1.168.192.in-addr.arpa``).
* In the [guimenu]``Type`` field, select [systemitem]``master``
. In the [guimenu]``Available Zones`` section, use these parameters for Zone1:
* In the [guimenu]``Name`` field, use the FQDN of the  branch server (for example: [systemitem]``branch1.mycompany.org``).
* In the [guimenu]``File`` field, type the name of your configuration file *TODO: Check this* (for example: [systemitem]``branch1.txt``).
. In the [guimenu]``Start of Authority (SOA)`` section, use these parameters for Zone1:
* In the [guimenu]``Nameserver (Ns)`` field, use the FQDN of the  branch server (for example: [systemitem]``branch1.mycompany.org``).
* In the [guimenu]``Contact`` field, use the email address for the domain administrator.
* Leave all other fields as their default values.
. In the [guimenu]``Records`` section, in subsection [guimenu]``A``, click on [btn]``Add Item`` and use these parameters to set up an A record for Zone1:
* In the [guimenu]``Hostname`` field, use the hostname of the branch server (for example: [systemitem]``branchserver``).
* In the [guimenu]``IP`` field, use the IP address of the branch server (for example, [systemitem]``192.168.1.1``).
. In the [guimenu]``Records`` section, subsection [guimenu]``NS``, click on [btn]``Add Item`` and use these parameters to set up an NS record for Zone1:
* In the input box, use the hostname of the branch server (for example: [systemitem]``branchserver``).
. In the [guimenu]``Records`` section, subsection [guimenu]``CNAME``, click on [btn]``Add Item`` and add the hostname of the branch server in each of these fields:
* [systemitem]``tftp``
* [systemitem]``ftp``
* [systemitem]``dns``
* [systemitem]``dhcp``
* [systemitem]``salt``
. Set up Zone2 using the same parameters as for Zone1, but ensure you use the reverse  details.
. Click [btn]``Save Formula`` to save your configuration
. Apply the highstate.



[[retail.sect.formulas.tftpd]]
== TFTPd Formula

The TFTPd formula is used to configure the TFTP service on the branch server.


.Procedure: Configuring TFTP

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Tftpd`` formula, and click [btn]``Save``.
. Navigate to the menu:Formulas[Tftpd] tab, and set these parameters:
* In the [guimenu]``Internal Network Address`` field, enter the IP address of the branch server (for example: [systemitem]``192.168.1.1``).
* In the [guimenu]``TFTP Base Directory`` field, enter the path to the saltboot directory (for example, [systemitem]``/srv/saltboot``).
* In the [guimenu]``Run TFTP Under User`` field, enter [systemitem]``saltboot``.
. Click [btn]``Save Formula`` to save your configuration.
. Apply the highstate.



[[retail.sect.formulas.vsftpd]]
== VsFTPd Formula

The VsFTPd formula is used to configure the FTP service on the branch server.
Use of this formula is optional.


.Procedure: Configuring VsFTPd

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Select the [systemitem]``Vsftpd`` formula, and click [btn]``Save``.
. Navigate to the menu:Formulas[Vsftpd] tab, and set these parameters:
* In the [guimenu]``Internal Network Address``, enter IP address of branch server (for example: [systemitem]``192.168.1.1``).
* All other fields can retain their default values.
. Click [btn]``Save Formula`` to save your configuration
. Apply the highstate.
