[[retail_migr.chap.slepostosuma]]
= {slepos} 11 to {smr}


include::entities.adoc[]



[[retail_migr.sect.slepostosuma.s1]]
== Migration from {slepos} 11 to {smr}

This section describes migrating from an existing {slepos} 11 installation, to a new {susemgr} installation.

. Install a {susemgr} server {productnumber} (with the Retail pattern).  For more information, see https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.install.html.

. On the SLEPOS Admin server export your LDAP data to an XML file with the following command:
+
----
posAdmin --export --type xml --file dumpfile.xml
----
+
The resulting [literal]``dumpfile.xml`` file will contain global information, with parts about images, hardware and its partitioning, and the description of the branch servers with networking data, services, and attached terminals.
+
Alternatively, this data can be exported branch by branch with:
+
----
posAdmin --export --type xml --file dumpfile.xml --user $branch_dn \
    --password $password
----

. Move the XML file to the {susemgr} server and convert it to YAML:
+
----
retail_migration dumpfile.xml retail.yml
----

. Review the generated YAML file ([literal]``retail.yml``) and adjust it as necessary.
Consider ``HWTYPE`` group naming and image name and version changes in the partitioning data.
You can shorten the names as needed, and the image names must match the images in {susemgr}.
The [option]``--save-mapping`` option can help you with this task.
+
Also check whether there are duplicate MAC addresses of the terminals in the generated YAML file.
Choose which entry you want to keep.
As long as there are duplicate MAC addresses, {susemgr} will refuse importing the YAML file.
+
[NOTE]
====
{slepos} images will not be migrated. You must rebuild the images using the OS image building functionality.
For more information about building images, see https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-advanced-topics/html/book.suma.advanced.topics/at.images.html#at.images.kiwi.
====

. Import the complete data (YAML) with:
+
----
retail_yaml --from-yaml retail.yml
----
+
You can statistical data while importing and check the results in the {webui}. In menu:Main Menu[Systems > Systems > All], you will see empty profiles, and in menu:Main Menu[Systems > Groups], you will see the groups for the hardware configurations, branches, servers, and terminals.
+
Alternatively, it can be imported branch by branch.


For each branch perform the following steps:

. Replace each old SLEPOS branch server with a {smr} branch server (see https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.install.html[Install Branch Server]) and connect it to the {smr} server (the same procedure as for https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.admin.html#retail.sect.admin.branch_mass_config[Branch Server Mass Configuration]).

. If you want to import one branch after the other from the YAML data instead of a complete import in one go, specify the wanted branch with:
+
----
retail_yaml --from-yaml retail.yml --branch <branch_name>
----
+
Repeat the command for every branch.

. Apply highstate on the branch server.

. Boot the terminals of the branch.

After migrating all branches, shutdown and remove the old SLEPOS Admin Server.

include::retail_migr_chap_slepostosumaind.adoc[leveloffset=1]
