[[retail.chap.introduction]]
= Introduction

include::entities.adoc[]



[abstract]
--

{smr} {productnumber} is an open source infrastructure management solution, optimized and tailored specifically for the retail industry.

This document provides an overview of {smr}, and guides you through initial installation and setup.
It should be read in conjunction with the {susemgr} documentation suite, available from https://www.suse.com/documentation/suse-manager-3/

If you need more information about managing your {smr} environment, or to find out where to get help, see <<retail_chap_next.adoc#retail.chap.next>>.
--


[[retail.sect.intro.what]]
== What is {smr}?

{smr} is designed for use in environments that include servers, workstations, point-of-service terminals, and other devices.
It allows administrators to configure the network topology of servers, build PXE-based operating system images, and manage the deployment and provisioning of target machines.

{smr} is designed to help you reduce costs, optimize operations, and ensure compliance while increasing the flexibility, reliability, and uptime of your point-of-service devices.

{smr} provides a reliable, flexible, and open platform for managing point-of-service and point-of-sale terminals, kiosks, self-service systems, and reverse-vending systems.


////
[[retail.sect.intro.architecture]]
== Architecture

TODO: Import https://www.suse.com/documentation/suse-manager-for-retail-3-1/book_susemanager_retail/data/sec_overview_architecture.html here
////
