[[retail.chap.introduction]]
= Introduction
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname:
:susemgr: SUSE Manager
:smr: SUSE Manager for Retail
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:webui: Web UI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images

// For the github environment we use cross references. These are only used with gh-pages, jekyll and browsing via github.
// Add a new installation document with methods for each type of installation(jeos, sles extension, ncurses etc.)
ifdef::env-github[]
// <<quickstart3_chap_install_overview.adoc#gs-overview, Overview>>
endif::[]

// For DAPS processing, Includes are not friendly with gh-pages, and jekyll due to default safe methods.
ifndef::env-github[]
// include::quickstart3_chap_install_overview.adoc[leveloffset=1]
endif::[]


[[retail.sect.intro]]
== Introducing SUSE Manager for Retail

Introduction
This document provides overview about SUSE Manager for Retail solution and guidance on setting up complete SUSE Manager for Retail stack.

What is SUSE Manager for Retail
SUSE Manager for Retail is an extension of SUSE Manager specifically addressing needs of organizations requiring automated image based deployment of servers, workstations, point of sale terminals and other devices. It allows administrators to configure network topologies of selected servers, build PXE based OS images and manage the deployment and provisioning of target machines.

SUSE Manager for Retail is a spiritual successor of SUSE Linux Enterprise Point of Sale product with similar architecture design and target users.

Architecture
SUSE Manager for Retail employs three layer architecture design:

layer consists of central SUSE Manager server and one or more build hosts

layer consists of one or more servers providing local network services and boot server services. These servers are generally referred to as branch servers

layer consists of deployed machines e.g. point of sale machines. These machines are generally referred to as terminals

[[retail.sect.intro.what]]
=== What is SUSE Manager for Retail?

SUSE Manager for Retail supports two modes of operation for Branch server:

branch server has a dedicated network interface card, 3rd. layer machines are using isolated internal branch network.

Branch server is managing internal network, provides DHCP, DNS, PXE, FTP and TFTP services.

branch server shares one network with 3rd. layer machines and connection to SUSE Manager central server.

Branch server does not manage network, may or may not provide DHCP and DNS services, however acts as a PXE boot server and provides FTP and TFTP services.

[[retail.sect.intro.who]]
=== Who should you use SUSE Manager for Retail?
