[[retail.chap.admin]]
= Administration

include::entities.adoc[]



[[retail.sect.admin]]
== Administration

This sections contains notes on administering your {smr} installation.
For general administration tasks, see the {susemgr} documentation at https://www.suse.com/documentation/suse-manager-3/

[[retail.sect.admin.branch_network_config]]
== Branch Server Network Configuration

The branch server can be configured to use networking in many different ways.
The most common ways provide either a dedicated or shared LAN for terminals.

[[retail.sect.admin.branch_mass_config]]
== Branch server mass configuration

Branch servers are configured individually using formulas.
If you are working in an environment with many branch servers, you might find it easier to configure the terminals automatically with a pre-defined configuration file, rather than configuring each branch server individually.

// https://gitlab.suse.de/SLEPOS/SUMA_Retail/tree/master/python-susemanager-retail



=== Configure multiple branch servers

This procedure requires the [package]``python-susemanager-retail`` package, which is provided with {smr}.
Install the [package]``python-susemanager-retail`` package on the {susemgr} server.

.Procedure: Configuring multiple branch servers

. Create a YAML file describing the infrastructure you intend to install.
An example YAML file is at the end of this chapter, for you to reference.
. On a clean {susemgr} installation, import the YAML file you have created:
+
----
retail_yaml --from-yaml filename.yaml
----
You can use the [command]``retail_yaml --help`` command for additional options.

If you need to change your configuration, you can edit the YAML file at any time, and use the [command]``retail_yaml --from-yaml`` command to upload the new configuration.


Use the empty profiles together with activation keys to onboard all the systems of your infrastructure.
Use an activation key to assign the channels listed in xref:retail_chap_install.adoc#retail.sect.install.install.config[Configuring Server].



[[retail.sect.admin.deploy_terminals]]
== Deploying terminals

For hardware requirements, see xref:retail_chap_components.adoc#retail.sect.components.pos-terminals[Point-of-Service Terminals].

Before terminals can be deployed, ensure you have prepared a saltboot based OS image.
For how to build OS images, see https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-advanced-topics/html/book.suma.advanced.topics/at.images.html#at.images.kiwi.

Each terminal requires a specific hardware type, which contains information about the product name and terminal manufacturer.
However, the {susemgr} database does not have this information to begin with.
In order to tell {susemgr} what image to deploy on each terminal, you can set hardware type groups.
After you have created your new hardware type group, you can apply the [systemitem]``saltboot-formula`` to the group and configure it for your environment.

After you have registered new terminals, always check the {susemgr} {webui} to ensure your terminal has connected successfully to the branch server, and you have not connected directly to the {susemgr} server by mistake.



=== Create a Hardware Type group

Hardware types allow you to group devices according to manufacturer and device name, so that all devices of a particular type can be managed as one.

You will need to create appropriate hardware types in your system.

Empty profiles can be assigned to a hardware type group either before or after registration.
If an empty profile is not assigned to a hardware type group before registration, it will be assigned to group that best matches the product information available to it.

For this procedure, you will require the system manufacturer name and product name for your terminal.

.Procedure: Creating a Hardware Type group

. Determine the hardware type group name.
Prefix the name with [systemitem]``HWTYPE:``, followed by the system manufacturer name and product name, separated by a hyphen.
For example:
+
----
HWTYPE:POSVendor-Terminal1
----
+
[IMPORTANT]
====
Only use colons (``:``), hyphens (``-``) or underscores (``_``) in hardware type group names.
Spaces and other non-alphanumeric characters will be removed when the name is processed.
====
+
. In the {susemgr} {webui}, navigate to menu:Systems[Overview], and click on the [guimenu]``Groups`` tab.
. Click the btn:[Create new] button.
. In the [guimenu]``Create System Group`` dialog, create a new system group, using the hardware type group name you created earlier.



[[retail.sect.admin.terminal_naming]]
== Terminal Names

.Procedure: Set up a Branch Server with a Dedicated LAN

In this configuration, the branch server requires at least two network interfaces: one acts as a WAN to communicate with the central server, and the other one acts as an isolated LAN to communicate with terminals.
This configuration allows for the branch server to provide DHCP, DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` checked
* In the [guimenu]``NIC`` field, enter the name of the network device that is connected to the internal LAN.
* In the [guimenu]``IP`` field, enter the static IP address to be assigned to the branch server on the internal LAN.
* In the [guimenu]``Netmask`` field, enter the network mask of the internal LAN.
. Check [guimenu]``Enable Route`` if you want the branch server to route traffic from internal LAN to WAN.
* Check [guimenu]``Enable NAT`` if you want the branch server to convert addresses from internal LAN to WAN.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click [btn]``Save`` to save your changes.


.Procedure: Set up a Branch Server with a Shared Network

In this configuration, the branch server has only one network interface card which is used to connect to the central server as well as the terminals.
This configuration allows for the branch server to provide DNS, TFTP, PXE and FTP services to terminals, which are configured through {smr} formulas in the {susemgr} {webui}.
Optionally, the branch server can also provide DHCP services in this configuration.

[NOTE]
====
If DHCP services are not provided by the branch server, ensure that your external DHCP configuration is set correctly:
* The [systemitem]``next-server`` option must point to the branch server for PXE boot to work
* The [systemitem]``filename`` option must correctly identify the network boot program (by default, this is [path]``/boot/pxelinux``)
* The [systemitem]``domain-name-servers`` option must point to the branch server for correct host name resolution
====

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. In the [guimenu]``Branch Network`` section, set these parameters:
* Keep [guimenu]``Dedicated NIC`` unchecked
* Select which services to enable on the branch server’s firewall.
Ensure you include DNS, TFTP and FTP services.
* Select the [guimenu]``bind`` DNS forwarder mode.
* Check DNS forwarder fallback if you want to rely on an external DNS if the branch DNS fails.
* Specify the working directory, and the directory owner and group.
. Click [btn]``Save`` to save your changes.
. Apply the salt state and synchronize your settings:
+
----
salt $branch_server_id state.apply image-sync
----



[[retail.sect.admin.branch_mass_config]]
== Branch Server Mass Configuration

You can either configure branch servers one by one using formulas (*TODO* see xxx) or create system groups of branch servers (*TODO* see yyy) or with a flexible command-line script.
Such a command-line script is suitable to do a mass configuration of branch servers.



// https://gitlab.suse.de/SLEPOS/SUMA_Retail/tree/master/python-susemanager-retail
For mass deployments use the script coming with the [package]``python-susemanager-retail`` package.
Install it on the central server.
When installed call it on the command-line with [command]``retail_yaml``.
This is the [command]``retail_yaml --help`` output:

----
usage: retail_yaml [-h] [--api-host API_HOST] [--api-user API_USER]
                   [--api-pass API_PASS] [--from-yaml FROM_YAML]
                   [--to-yaml TO_YAML]

Initialize Branch Server

optional arguments:
  -h, --help            show this help message and exit
  --api-host API_HOST   API host
  --api-user API_USER   API user
  --api-pass API_PASS   API password
  --from-yaml FROM_YAML
                        initialize retail system from YAML file
  --to-yaml TO_YAML     save structure of retail system to YAML file
----

The actual settings are filled in a ``YAML`` file that you will read with the [option]``--from-yaml`` option.
Here is the documentated [path]``example.yml`` coming with the package:

----
# /usr/share/doc/packages/python-susemanager-retail/example.yml
branches:
# there are 2 possible setups: with / without dedicated NIC
#
# with dedicated NIC
  branchserver1.branch1.cz:     # salt ID of branch server
    branch_prefix: branch1      # optional, default guessed from salt id
    server_name: branchserver1  # optional, default guessed from salt id
    server_domain: branch1.cz   # optional, default guessed from salt id
    dedicated_nic: eth1         # optional
    salt_ip: 10.100.24.130      # ip of salt master / broker for terminals, mandatory
    branch_ip: 192.168.2.1      # default for dedicated NIC: 192.168.1.1
    netmask: 255.255.255.0      # default for dedicated NIC: 255.255.255.0
    dyn_range:                  # default for dedicated NIC: 192.168.1.10 - 192.168.1.250
        - 192.168.2.10
        - 192.168.2.250

# without dedicated NIC
# the DHCP formula is not used, DHCP is typically provided by a router
# the network parameters can be autodetected if the machine is already connected to SUSE Manager
  branchserver2.branch2.cz:     # salt ID of branch server
    branch_prefix: branch2      # optional, default guessed from salt id
    server_name: branchserver2  # optional, default guessed from salt id
    server_domain: branch2.cz   # optional, default guessed from salt id
    salt_ip: 10.100.24.130      # ip of salt master / broker for terminals, mandatory
    branch_ip: 192.168.2.1      # optional, default taken from SUMA data if the machine is registered
    netmask: 255.255.255.0      # optional, default taken from SUMA data if the machine is registered


hwtypes:
  IBM CORPORATION-4838910:      # HWTYPE string (manufacturer-model) as returned by bios
    description: 4838-910       # freetext description
    saltboot:
      partitioning:             # partitioning pillar as described in saltboot documentation
        disk1:
          device: /dev/sda
          disklabel: msdos
          partitions:
            p1:
              flags: swap
              format: swap
              size_MiB: 1000.0
            p2:
              image: POS_Image_JeOS6
              mountpoint: /
          type: DISK
  TOSHIBA-6140100:
    description: HWTYPE:TOSHIBA-6140100
    saltboot:
      partitioning:
        disk1:
          device: /dev/sda
          disklabel: msdos
          partitions:
            p1:
              flags: swap
              format: swap
              size_MiB: 1000.0
            p2:
              image: POS_Image_JeOS6
              mountpoint: /
          type: DISK
----

For details about network settings and ``hwtypes`` related settings, see above.



[[retail.sect.admin.deploy_terminals]]
== Deploying Terminals

TODO: https://github.com/SUSE/spacewalk/issues/5613

Each terminal requires a specific hardware type, which contains information about the product name and terminal manufacturer.
However, the {susemgr} database does not have this information to begin with.
In order to tell {susemgr} what image to deploy on each terminal, you can set hardware type groups.


.Procedure: Create a Hardware Type Group

For this procedure, you will require the system manufacturer name and product name for your terminal.

. Determine the hardware type group name.
Prefix the name with [systemitem]``HWTYPE:``, followed by the system manufacturer name and product name, separated by a hyphen.
For example:
+
----
HWTYPE:POSVendor-Terminal1
----
+
[NOTE]
====
Only use colons (``:``), hyphens (``-``) or underscores (``_``) in hardware type group names.
Spaces and other non-alphanumeric characters will be removed when the name is processed.
====
+
. TODO: Apply hardware type



////
Commenting this heading out until we have content for it. LKB
[[retail.sect.admin.troubleshooting]]
== Troubleshooting

TODO: https://github.com/SUSE/spacewalk/issues/5616
////
