[[retail.chap.install]]
= Installation

ifdef::env-github,backend-html5,backend-docbook5[]

include::entities.adoc[]



[[retail.sect.running.requirements]]
== Requirements

Before you install {smr}, ensure your environment meets the minimum requirements.
This section lists the requirements for your {smr} installation.
These requirements are in addition to the {susemgr} requirements listed at
xref:quickstart3_chap_install_overview.adoc#quickstart.sect.prereq.hardware[Hardware Prerequisites]
and
xref:advanced_topics_proxy_quickstart.adoc#at.manager.proxy.requirements[Proxy Requirements].

[IMPORTANT]
====
{smr} is only supported on {x86_64} architecture.
====


.Central Server Requirements

* {x86_64} processor
* A minimum of 4{nbsp}GB hard disk space (recommended 15{nbsp}GB)
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Build Host Requirements

* {x86_64} processor
* A minimum of 8{nbsp}GB hard disk space (recommended 25{nbsp}GB)
 terminals.
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Branch Server Requirements

* {x86_64} processor
* A minimum of 4{nbsp}GB hard disk space (recommended 10{nbsp}GB)
 terminals.
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Network Requirements

* The central server requires a reliable and fast WAN connection
* The branch server requires a reliable WAN connection, to reach the central server
* If you are using a shared network, ensure that DHCP requests are filtered before reaching the rest of your shared network
* If you are using a dedicated network, the branch server requires at least two network interfaces: one connected to the WAN with reachable central server, and one connected to the internal branch LAN.
* Terminals require a LAN connection to the branch server network.



[[retail.sect.running.install]]
== Installation

Most {smr} installations require several steps:

. Install the central server
. Configure the central server
. Install the {smr} pattern on the central server
. Install the build host and register it to {susemgr}
. Configure the build host
. Install the branch server and register it to {susemgr}
. Assign and configure branch server formulas

Each procedure is detailed in this section.



=== Procedure Install the Central Server

For instructions to install {susemgr}, see the xref:quickstart3_chap_install_overview.adoc[{susemgr} Getting Started Guide].

{smr} uses formulas to simplify configuration, which are installed as RPM packages.

. Check that you have these packages installed and available, after installing {susemgr}:

* bind-formula
* branch-network-formula
* dhcpd-formula
* image-sync-formula
* pxe-formula
* susemanager-retail-tools
* tftp-formula
* vsftpd-formula
+
Install any missing packages with [command]``zypper``:
+
----
zypper install package_name
----
. Synchronize the salt filesystem and salt modules:
+
----
salt-run fileserver.update
salt '*' saltutil.sync_all
----
. Grant the Salt API access to the central server, by opening the [filename]``/etc/salt/master.d/spacewalk.conf`` file in your preferred text editor, and adding your administration credentials in the [systemitem]``spacewalk`` section:
+
----
spacewalk:
    localhost:
        username: $administration_user
        password: $administration_password
----
+
[IMPORTANT]
====
We recommend that do not put your master {susemgr} administration credentials in plain text in the configuration file.
Instead, use the credentials for an administration account for any organization.
This allows you to more easily change the password, should it become compromised.
====

. Restart the salt master service to pick up the changes:
+
----
Restart salt master service now.

systemctl restart salt-master
----



=== Procedure Configure the central server

Default formulas are supplied with {smr} and can be installed as RPM packages.

. Formula RPMs are provided as part of the {susemgr} installation process.
Save the formula custom states to [path]``/srv/salt/formula-name/``.
Save the metadata files ([path]``form.yaml`` and [path]``metadata.yml``) to [path]``/srv/formula_metadata/formula-name/``.
. Check that your formula has been installed correctly.
In the {susemgr} {webui}, navigate to menu:Salt[Formula Catalog] and check that the required formula appears in the list.
. Open the details page for the group or system you want to apply the formula to, and navigate to the [guimenu]``Formulas`` tab.
. Select the formulas you want to apply to the group or system and click btn:[Save] to save your changes.

After applying one or more formulas to a group or system, additional tabs will become available from the top menu, one for each formula selected.
These tabs give you specific configuration options for each formula.

When you have finished customizing your formula values you will need to apply highstate for them to take effect.
Do this by clicking btn:[Apply Highstate] from any formulas page.
Applying highstate will execute the state associated with the formula and configure the affected systems.

If you need to change any values, or re-apply formulas because of a failure, make the changes in the [guimenu]``Formulas`` tab, save your changes, and re-apply the highstate.
Salt will ensure that only modified values are adjusted and restart or reinstall services only when necessary.

For additional information about Salt formulas, see: https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html



=== Procedure Install the {smr} pattern on the central server

. Install the [package]``SUSE Manager for Retail`` pattern on the central server:
+
----
zypper in -t pattern suma_retail
----



=== Procedure Install the build host and register it to {susemgr}

Your build host should be a Salt minion, running {sls}{nbsp}12 SP3.
See [quickstart3_chap_suma_keys_and_first_clients.adoc] for instructions to install Salt minions and register them to {susemgr}.


=== Procedure Configure the build host

The build host must be set as an OS Image build host in the {susemgr} {webui}, and highstate applied.

. In the {susemgr} {webui}, navigate to menu:Systems[Overview].
Locate the system to be made a build host, and click on its name.
. In the [guimenu]``System Properties`` window, click btn:[Edit These Properties].
. In the [guimenu]``Edit System Details`` window, ensure the [guimenu]``OS Image Build Host`` option is checked, and click btn:[Update Properties] to save your changes.
. Select the [guimenu]``States`` tab, and navigate to the [guimenu]``Highstate`` window.
. Click btn:[Apply Highstate] to save your changes.



=== Procedure Install the branch server and register it to {susemgr}

Your branch server should be installed as a default Salt-based client ("minion"), running {susemgrproxy} 3.2.
Do not install it as a traditionally managed client.
For instructions to install Salt-based proxy minions and register them to {susemgr}, see xref:advanced_topics_proxy_quickstart.adoc#at.manager.proxy.inst[{susemgr} Advanced Topics].

[WARNING]
.Do Not Enable PXE Boot
====
Do not enable PXE boot functionality on the {susemgrproxy} during initial setup.
This functionality will be installed later, after the initial setup.
====

////
Karl: Isn't this all documented in the SUMA docs? We only want the additional content here, I think. -LKB

[IMPORTANT]
====
First completely download the channels and then create the activation key.
Only then you can select the correct child channels.
Here is a channel overview:
----
- SLES 12 SP3 (SP4 in the future) as a base
  - SLES Pool
    - SLES Update
- SUSE Manager 3.2 Proxy
  - SUSE Manager 3.2 Proxy Pool
    - SUSE Manager 3.2 Proxy Update
- SUSE Manager 3.2 Proxy for Retail
  - SUSE Manager 3.2 Proxy for Retail Pool
    - SUSE Manager 3.2 Proxy for Retail Update
----
====

. Install a basic {sls} 12 SP3 system that you will deploy as a Retail Branch Server with the following steps.  For more information about installing {sls} 12 SP3, see the SLES documentation.
. Create an activation key based on the {sle} 12 SP3 base channel.  Open menu:Main Menu[Systems > Activation Keys] and click [guimenu]``Create Key``.  In the [guimenu]``Create Activation Key`` dialog enter required fields and select {sle} 12 SP3 as the base channel; confirm with btn:[Create Activation Key].  On the following activation key details page click the [guimenu]``Child Channels`` tab and select the {productname} {productnumber} Proxy child channel with the matching update channel and the Retail channels ([systemitem]``SUSE Manager Proxy-3.2-Pool`` and [systemitem]``SUSE-Manager-Proxy-3.2-Updates`` as well as [systemitem]``SUSE-Manager-Retail-3.2-Pool`` and [systemitem]``SUSE-Manager-Retail-3.2-Updates``).  Plus SLES12-SP3-Updates, SLE-Manager-Tools12-Pool, and SLE-Manager-Tools12-Updates.  Confirm with btn:[Update Activation Key].
+
. Create a bootstrap script to register the {smr} Proxy system: menu:Main Menu[Admin > Manager Configuration > Bootstrap Script].  Save the bootstrap script as [path]``bootstrap-proxy.sh``.  In the beginning of [path]``bootstrap-proxy.sh``, set ``ACTIVATION_KEY`` to the name of the created activation key.
. Create the SUSE Manager Tools Repository for bootstrapping, see [create.tools.repository]
// <<create.tools.repository>>.
. Bootstrap the proxy system. For more information, see [connect.first.client]
// <<connect.first.client>>.
. If not done automatically, accept the Salt key on the menu:Main Menu[Salt > Keys] page by clicking the check mark. The it will appear in the menu:Main Menu[Systems > Overview].
. Check via menu:System Details[Software > Software Channels] that all the above listed channels are selected.
. Install the [path]``patterns-suma_retail_proxy`` pattern.
. Copy the SSL certificate and key from the server
. Run [command]``configure-proxy.sh``.
+
*TODO*: add more info about the last 3 actions if wanted; it's in Advanced Topics, Proxy QS.
////


For mass deployments, see xref:#retail.sect.admin.branch_mass_config[Branch Server Mass Configuration].



=== Procedure Assign and configure branch server formulas

Before you configure the branch server formulas, ensure you have configured networking, and know the subdomain name and IP address of the branch server.

[IMPORTANT]
====
Check each formula to ensure the values are appropriate for your environment.
Note that these instructions will vary depending on your network architecture.
====

. In the {susemgr} {webui}, open the details page for the branch server, and navigate to the [guimenu]``Formulas`` tab.
. Check the [systemitem]``bind`` formula, and click btn:[Save].
. Navigate to the menu:Formulas[Bind] tab, and set these parameters for Zone1:
* In the [guimenu]``Name`` field, use the fully qualified domain name (FQDN) of the  branch server (for example: [systemitem]``branch1.example.com``).
* In the [guimenu]``Type`` field, select [systemitem]``master``.
. Click btn:[Add item], and set these parameters for Zone2:
* In the [guimenu]``Name`` field, use the reverse zone for the configured IP range (for example: [systemitem]``1.168.192.in-addr.arpa``).
* In the [guimenu]``Type`` field, select [systemitem]``master``.
. In the [guimenu]``Available Zones`` section, use these parameters for Zone1:
* In the [guimenu]``Name`` field, use the FQDN of the  branch server (for example: [systemitem]``branch1.example.com``).
* In the [guimenu]``File`` field, type the name of your configuration file *TODO: Check this* (for example: [systemitem]``branch1.txt``).
. In the [guimenu]``Start of Authority (SOA)`` section, use these parameters for Zone1:
* In the [guimenu]``Nameserver (Ns)`` field, use the FQDN of the  branch server (for example: [systemitem]``branch1.example.com``).
* In the [guimenu]``Contact`` field, use the email address for the domain administrator.
* Leave all other fields as their default values.
. In the [guimenu]``Records`` section, click on btn:[Add Item] and use these parameters to set up an A record for Zone1:
* In the [guimenu]``Hostname`` field, use the hostname of the branch server (for example: [systemitem]``branchserver``).
* In the [guimenu]``IP`` field, use the IP address of the branch server (for example, [systemitem]``192.168.1.1``).
. In the [guimenu]``Records`` section, click on btn:[Add Item] and use these parameters to set up an NS record for Zone1:
* In the [guimenu]``Hostname`` field, use the hostname of the branch server (for example: [systemitem]``branchserver``).
. In the [guimenu]``Common Name (CNAME) Records`` section, use these parameters:
* In the [systemitem]``tftp`` section, use the use the FQDN of the  branch server, ending with a period (for example: [systemitem]``branchserver.branch1.example.com.``).
* In the [systemitem]``ftp`` section, use the use the FQDN of the  branch server, ending with a period (for example: [systemitem]``branchserver.branch1.example.com.``).
* In the [systemitem]``dns`` section, use the use the FQDN of the  branch server, ending with a period (for example: [systemitem]``branchserver.branch1.example.com.``).
* In the [systemitem]``dhcp`` section, use the use the FQDN of the  branch server, ending with a period (for example: [systemitem]``branchserver.branch1.example.com.``).
* In the [systemitem]``salt`` section, use the use the FQDN of the  branch server, ending with a period (for example: [systemitem]``branchserver.branch1.example.com.``).
. Set up Zone2 using the same parameters as for Zone1, but ensure you use the reverse  details.
. Click btn:[Save Formula] to save your configuration.
