[[retail.chap.install]]
= Installation
ifdef::env-github,backend-html5,backend-docbook5[]
//Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// SUSE ENTITIES FOR GITHUB
// System Architecture
:zseries: z Systems
:ppc: POWER
:ppc64le: ppc64le
:ipf : Itanium
:x86: x86
:x86_64: x86_64
// Rhel Entities
:rhel: Red Hat Linux Enterprise
:rhnminrelease6: Red Hat Enterprise Linux Server 6
:rhnminrelease7: Red Hat Enterprise Linux Server 7
// SUSE Manager Entities
:productname:
:susemgr: SUSE Manager
:smr: SUSE Manager for Retail
:susemgrproxy: SUSE Manager Proxy
:productnumber: 3.2
:webui: Web UI
// SUSE Product Entities
:sles-version: 12
:sp-version: SP3
:jeos: JeOS
:scc: SUSE Customer Center
:sls: SUSE Linux Enterprise Server
:sle: SUSE Linux Enterprise
:slsa: SLES
:suse: SUSE
endif::[]
// Asciidoctor Front Matter
:doctype: book
:sectlinks:
:toc: left
:icons: font
:experimental:
:sourcedir: .
:imagesdir: images



[[retail.sect.running.requirements]]
== Requirements

Before you install {smr}, ensure your environment meets the minimum requirements:


[IMPORTANT]
====
{smr} is only supported on {x86_64} architecture.
====


.Central Server Requirements

* {x86-64} processor
* A minimum of 4{nbsp}GB hard disk space (recommended 15{nbsp}GB)
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Build Host Requirements

* {x86-64} processor
* A minimum of 8{nbsp}GB hard disk space (recommended 25{nbsp}GB)
 terminals.
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Branch Server Requirements

* {x86-64} processor
* A minimum of 4{nbsp}GB hard disk space (recommended 10{nbsp}GB)
 terminals.
* A minimum of 1{nbsp}GB RAM per CPU
* Networking capability


.Network Requirements

* The central server requires a reliable and fast WAN connection
* The Branch server requires a reliable WAN connection in order to reach the central server
* If you are using a shared network, ensure that your router and firewall can filter DHCP requests between the shared network annd the WAN
* If you are using a dedicated network, the branch server requires at least two network interfaces: one connected to the WAN with reachable central server, and one connected to the internal branch LAN.
* Terminals require a LAN connection to the branch server network.



[[retail.sect.running.install]]
== Installation


Most {smr} installations require several steps:

. Install and configure the central server
. Install the {smr} pattern on the central server
. Install the build host and register it to {susemgr}
. Configure the build host
. Install the branch server and register it to {susemgr}
. Assign and configure branch server formulas

Each procedure is detailed in this section.

.Procedure: Install and configure the central server

See [quickstart3_chap_install_overview.adoc] for instructions to install {susemgr}.

{smr} uses formulas to simplify configuration, which require packages to operate correctly.

. Check that you have these packages installed and available, after installing {susemgr}:

* bind-formula
* branch-network-formula
* dhcpd-formula
* image-sync-formula
* pxe-formula
* tftp-formula
* vsftpd-formula
+
Install any missing packages with [command]``zypper``:
+
----
zypper install package_name
----
. Synchronize the salt filesystem and salt modules:
+
----
salt-run fileserver.update
salt '*' saltutil.sync_all
----
. Grant the Salt API access to the central server, by opening the [filename]``/etc/salt/master.d/spacewalk.conf`` file in your preferred text editor, and adding your administration credentials in the [systemitem]``spacewalk`` section:
+
----
spacewalk:
    localhost:
        username: $administration_user
        password: $administration_password
----
+
[IMPORTANT]
====
We recommend that do not put your master {susemgr} administration credentials in plain text in the configuration file.
Instead, use the credentials for an administration account for any organization.
This allows you to more easily change the password, should it become compromised.
====

. Restart the salt master service to pick up the changes:
+
----
Restart salt master service now.

systemctl restart salt-master
----

.Procedure: Install the {smr} pattern on the central server

. Install the [package]``SUSE Manager for Retail`` pattern on the central server:
+
----
zypper in -t pattern suma_retail
----


.Procedure: Install the build host and register it to {susemgr}

Your build host should be a Salt minion, running {sls}{nbsp}12 SP3.
See [quickstart3_chap_suma_keys_and_first_clients.adoc] for instructions to install Salt minions and register them to {susemgr}.



.Procedure: Configure the build host

The build host must be set as an OS Image build host in the {susemgr} {webui}, and highstate applied.

. In the {susemgr} {webui}, navigate to menu:Systems[Overview].
Locate the system to be made a build host, and click on its name.
. In the [guimenu]``System Properties`` window, click [btn]``Edit These Properties``.
. In the [guimenu]``Edit System Details`` window, ensure the [guimenu]``OS Image Build Host`` option is checked, and click [btn]``Update Properties`` to save your changes.
. Select the [guimenu]``States`` tab, and navigate to the [guimenu]``Highstate`` window.
. Click the [btn]``Apply Highstate`` button.


.Procedure: Install the branch server and register it to {susemgr}

Your branch server should be a Salt minion, running {susemgrproxy} 3.2.
See [advanced_topics_proxy_quickstart.adoc#at.manager.proxy.inst] for instructions to install Salt-based proxy minions and register them to {susemgr}.
Then you will deploy the Retail Branch Server extension on top of it.

[WARNING]
.Do Not Enable PXE Boot Functionality
====
Do not enable PXE boot functionality of the {susemgrproxy} during initial setup.  To use it as Retail Branch Server you must not activate PXE as describe in
// <<advanced.topics.proxy.pxe>>.
Use the PXE formula later after the initial setup.
====

Detailed installation instructions of a {susemgrproxy} are outlined in
// <<advanced.topics.proxy.quickstart>>.
Keep all the defaults and install it as a Salt-based client ("minion"); do not install it as a traditionally managed client.

[IMPORTANT]
====
First completely download the channels and then create the activation key.
Only then you can select the correct child channels.
Here is a channel overview:
----
- SLES 12 SP3 (SP4 in the future) as a base
  - SLES Pool
    - SLES Update
- SUSE Manager 3.2 Proxy
  - SUSE Manager 3.2 Proxy Pool
    - SUSE Manager 3.2 Proxy Update
- SUSE Manager 3.2 Proxy for Retail
  - SUSE Manager 3.2 Proxy for Retail Pool
    - SUSE Manager 3.2 Proxy for Retail Update
----
====

. Install a basic {sls} 12 SP3 system that you will deploy as a Retail Branch Server with the following steps.  For more information about installing {sls} 12 SP3, see the SLES documentation.
. Create an activation key based on the {sle} 12 SP3 base channel.  Open menu:Main Menu[Systems > Activation Keys] and click [guimenu]``Create Key``.  In the [guimenu]``Create Activation Key`` dialog enter required fields and select {sle} 12 SP3 as the base channel; confirm with btn:[Create Activation Key].  On the following activation key details page click the [guimenu]``Child Channels`` tab and select the {productname} {productnumber} Proxy child channel with the matching update channel and the Retail channels ([systemitem]``SUSE Manager Proxy-3.2-Pool`` and [systemitem]``SUSE-Manager-Proxy-3.2-Updates`` as well as [systemitem]``SUSE-Manager-Retail-3.2-Pool`` and [systemitem]``SUSE-Manager-Retail-3.2-Updates``).  Plus SLES12-SP3-Updates, SLE-Manager-Tools12-Pool, and SLE-Manager-Tools12-Updates.  Confirm with btn:[Update Activation Key].
+
*TODO*: Do you need additionally Branch -POOL and -Updates repos???
. Create a bootstrap script to register the {smr} Proxy system: menu:Main Menu[Admin > Manager Configuration > Bootstrap Script].  Save the bootstrap script as [path]``bootstrap-proxy.sh``.  In the beginning of [path]``bootstrap-proxy.sh``, set ``ACTIVATION_KEY`` to the name of the created activation key.
. Create the SUSE Manager Tools Repository for bootstrapping, see [create.tools.repository]
// <<create.tools.repository>>.
. Bootstrap the proxy system. For more information, see [connect.first.client]
// <<connect.first.client>>.
. If not done automatically, accept the Salt key on the menu:Main Menu[Salt > Keys] page by clicking the check mark. The it will appear in the menu:Main Menu[Systems > Overview].
. Check via menu:System Details[Software > Software Channels] that all the above listed channels are selected.
. Install the [path]``patterns-suma_proxy`` pattern; Copy the SSL certificate and key from the server; Run [command]``configure-proxy.sh``.
+
*TODO*: add more info about these 3 actions if wanted; it's in Advanced Topics, Proxy QS.

*TODO*: do we have a suma_retail_proxy pattern?

After this basic proxy installation, use the formulas to deploy the Retail Branch Server functionality on it.

For mass deployments use the script coming with the [package]``python-susemanager-retail`` package.


.Procedure: Assign and configure branch server formulas
TODO: https://github.com/SUSE/spacewalk/issues/5610

. Set the branch server hostname and CNAME aliases, so that services can reach the branch server accurately.
. Check each formula to ensure the values are appropriate for your environment.
. Configure the branch server network.
This will vary depending on your preferred topology.
See [retail.chap.admin] for more information.
