[[retail_migr.chap.scenarios]]
= Scenarios


include::entities.adoc[]



[[retail_migr.chap.scenarios.s1]]
== Scenario 1—Migrate SLEPOS (No {susemgr} Installed)

Proceed as follows if you want to migrate an existing SLEPOS installation to {susemgr} that is not installed thus far.

. Install a {susemgr} server {productnumber} (with the Retail extension).  For more information, see xref:retail_chap_install.adoc#retail.chap.install[{smr} Installation].

. On the SLEPOS Admin server export your LDAP data to an XML file with the following command:
+
----
posAdmin --export --type xml --file dumpfile.xml
----
+
Alternatively, this data can be exported branch by branch with:
+
----
posAdmin --export --type xml --file dumpfile.xml --user 
----

. Move the XML file to the {susemgr} server and convert it to YAML:
+
----
retail_migration dumpfile.xml retail.yml
----

. For each SLEPOS image build a replacement image in {susemgr}, edit the [path]``retail.yml`` file, and adjust the image names and other settings if needed.
For more information about building images, see xref:advanced_topics_image_management.adoc#at.images.kiwi[OS image building].

. Import the complete data (YAML) with:
+
----
retail_yaml --from-yaml retail.yml
----
+
Alternatively, it can be imported branch by branch.


For each branch perform the following steps:

. Replace each old SLEPOS branch server with a {smr} branch server (see xref:retail_chap_install.adoc#retail.sect.install.branch[Install Branch Server]) and connect it to the {smr} server (the same procedure as for xref:retail_chap_admin.adoc#retail.sect.admin.branch_mass_config[Branch Server Mass Configuration]).

. Optionally, import a selected branch from the YAML data with:
+
----
retail_yaml --from-yaml retail.yml --branch <branch_name>
----
+
If it was not done in the previous step with the complete import. (The other steps before can also be repeated optionally).

. Apply highstate on the branch server.

. Boot the terminals of the banch.

Finally, shutdown and remove the old SLEPOS Admin Server.



[[retail_migr.chap.scenarios.s2a]]
== Scenario 2a—Migrate SLEPOS ({susemgr} Installed Independantly)


Proceed as follows if you want to migrate an existing SLEPOS installation to {susemgr} that was already installed independantly.

. Check the version number of the installed {susemgr}. If needed migrate {susemgr} to version 3.2.
. Check whether is the Retail extension is already installed. If not, see xref:retail_chap_install.adoc#retail.chap.install[{smr} Installation] and enhance your server accordingly.
. Continue as in xref:retail_migr_chap_scenarios.adoc#retail_migr.chap.scenarios.s1[Scenario 1, Step 2].

