[[retail.chap.install]]
= Installation

ifdef::env-github,backend-html5,backend-docbook5[]

include::entities.adoc[]



[[retail.sect.running.requirements]]
== Requirements

Before you install {smr}, ensure your environment meets the minimum requirements.
This section lists the requirements for your {smr} installation.
These requirements are in addition to the {susemgr} requirements listed at
xref:quickstart3_chap_install_overview.adoc#quickstart.sect.prereq.hardware[Hardware Prerequisites]
and
xref:advanced_topics_proxy_quickstart.adoc#at.manager.proxy.requirements[Proxy Requirements].

[IMPORTANT]
====
{smr} is only supported on {x86_64} architecture.
====


.Central Server Requirements

[cols="1,1", options="header"]
.Hardware Requirements for Central Server
|===
| Hardware                 | Recommended
| CPU                      | Multi-core 64-bit CPU
| RAM:                     | _Test Server_ Minimum 8{nbsp}GB
|                          | _Base Installation_ Minimum 16{nbsp}GB
|                          | _Production Server_ Minimum 32{nbsp}GB
| Disk Space:              | [path]``/`` _(root)_ 100{nbsp}GB
|                          | [path]``/var/lib/pgsql`` Minimum 50{nbsp}GB
|                          | [path]``/srv/`` 50{nbsp}GB (Minimum 2{nbsp}GB per OS image)
|                          | [path]``/var/spacewalk`` Minimum 50{nbsp}GB per SUSE product and 250{nbsp}GB per Red Hat product
|===

.Build Host Requirements

.Hardware Requirements for Build Host
|===
| Hardware                 | Recommended
| CPU                      | Multi-core 64-bit CPU
| RAM:                     | 4{nbsp}GB
| Disk Space:              | [path]``/`` _(root)_ 50{nbsp}GB
|===


.Branch Server Requirements

.Hardware Requirements for Branch Server
|===
| Hardware                 | Recommended
| CPU                      | Multi-core 64-bit CPU
| RAM:                     | 8{nbsp}GB
| Disk Space:              | [path]``/`` _(root)_ 100{nbsp}GB (Minimum 50{nbsp}GB per SUSE product and 2{nbsp}GB per OS image)
|===


.Network Requirements

* The central server requires a reliable and fast WAN connection
* The branch server requires a reliable WAN connection, to reach the central server
* If you are using a shared network, ensure that DHCP requests are filtered before reaching the rest of your shared network
* If you are using a dedicated network, the branch server requires at least two network interfaces: one connected to the WAN with reachable central server, and one connected to the internal branch LAN.
* Terminals require a LAN connection to the branch server network.



[[retail.sect.running.install]]
== Installation

{smr} can be installed in various ways depending on individual needs.
We recommend these steps:

. Install the Central Server
. Configure the Central Server
. Install the {smr} pattern on the Central Server
. Install the Build Host and register it to {susemgr}
. Configure the Build Host
. Create required system group

Branch server installation steps:

. Install the branch server and register it to {susemgr}
. Assign and configure branch server formulas

Each procedure is detailed in this section.



=== Procedure Install the Central Server

For instructions to install {susemgr}, see the xref:quickstart3_chap_install_overview.adoc[{susemgr} Getting Started Guide].
[WARNING]
.Do Not Enable PXE Boot
====
Do not enable PXE boot functionality on the {susemgrproxy} during initial setup.
This functionality will be installed later, after the initial setup.
====



=== Procedure Configure the Central Server

Available SUSE channels are essential for functional image building as well as day-to-day operations.
Make sure all the required channels are synchronized.
For instructions see the xref:command-line-tools.adoc[Syncing {susemgr} Repositories from SCC (mgr-sync)].

Channel overview required for {smr} functionality:
----
- SLES 12 SP3 (SP4 in the future) as a base
  - SLES Pool
    - SLES Update
- SUSE Manager 3.2 Tools
  - SUSE Manager 3.2 Tools Pool
    - SUSE Manager 3.2 Tools Update
- SUSE Manager 3.2 Proxy
  - SUSE Manager 3.2 Proxy Pool
    - SUSE Manager 3.2 Proxy Update
- SUSE Manager 3.2 Proxy for Retail
  - SUSE Manager 3.2 Proxy for Retail Pool
    - SUSE Manager 3.2 Proxy for Retail Update
----

After you have synchronized the required SUSE channels, create channels for custom software.
Channels are used to provide custom software for OS image building.
For instructions see the xref:reference-webui-channels.adoc[Software Channels Reference]



=== Procedure Install the {smr} pattern on the Central Server

. Install the [package]``SUSE Manager for Retail`` pattern on the Central Server:
+
----
zypper in -t pattern suma_retail
----

. Check that you have these packages installed and available, after installing {susemgr} and {smr} pattern:

* bind-formula
* branch-network-formula
* dhcpd-formula
* image-sync-formula
* pxe-formula
* susemanager-retail-tools
* tftp-formula
* vsftpd-formula
+
Install any missing packages with [command]``zypper``:
+
----
zypper install package_name
----
. Synchronize the salt filesystem and salt modules:
+
----
salt-run fileserver.update
salt '*' saltutil.sync_all
----
. Restart the salt master service to pick up the changes:
+
----
Restart salt master service now.

systemctl restart salt-master
----



=== Procedure Install the Build Host and register it to {susemgr}

Your build host should be a Salt minion, running {sls}{nbsp}12 SP3.
For instructions to install Salt minion see xref:quickstart3_chap_suma_keys_and_first_client.adoc[Registering Clients].

[WARNING]
====
Do not install the Build Host as a traditionally managed client.
====



=== Procedure Configure the Build Host

The build host must be set as an OS Image build host in the {susemgr} {webui}, and highstate applied.

. In the {susemgr} {webui}, navigate to menu:Systems[Overview].
Locate the system to be made a build host, and click on its name.
. In the [guimenu]``System Properties`` window, click btn:[Edit These Properties].
. In the [guimenu]``Edit System Details`` window, ensure the [guimenu]``OS Image Build Host`` option is checked, and click btn:[Update Properties] to save your changes.
. Select the [guimenu]``States`` tab, and navigate to the [guimenu]``Highstate`` window.
. In the [guimenu]``States`` tab, click btn:[Apply Highstate].

[IMPORTANT]
====
Check that the Build Host has following packages installed after Highstate run:

- kiwi
- kiwi-desc-saltboot

If any package is missing, make sure ``SUSE Manager 3.2 Tools`` repository is available on the Build Host and install packages manually using ``zypper install`` command.
====



=== Procedure Create required system group

When you register terminals, {smr} requires a system group called [systemitem]``Terminals``.
The [systemitem]``Terminals`` system group needs to be manually created during installation.
For instructions on how to create system groups, see xref:reference-webui-systems.adoc#ref.webui.systems.systemgroups[System groups reference]



=== Procedure Install the branch server and register it to {susemgr}

Your branch server should be installed as a default Salt-based client ("minion"), running {susemgrproxy} 3.2.

For instructions to install Salt-based proxy minions and register them to {susemgr}, see xref:advanced_topics_proxy_quickstart.adoc#at.manager.proxy.inst[{susemgr} Advanced Topics].


For mass deployments, see xref:#retail.sect.admin.branch_mass_config[Branch Server Mass Configuration].

[WARNING]
====
Do not install the branch server as a traditionally managed client.
====



=== Procedure Assign and configure branch server formulas

Before you configure the branch server, ensure you have decided on networking topology, and know the Salt ID of the branch server.

. Branch server configuration is performed using the [command]``retail_branch_init`` command:
+
.Configure branch server using default values and single shared network interface
----
retail_branch_init <branch_server_salt_id>
----
+
If you need to specify values for your architecture, use:
+
.Configure branch server using specified values and dedicated network interface for branch network
----
retail_branch_init <branch_server_salt_id> --dedicated-nic eth1 --branch-ip 192.168.10.1 --netmask 255.255.255.0 --dyn-range 192.168.10.50 192.168.10.100
----
+
You can use the [command]``retail_branch_init --help`` command for additional options.
. Verify that your changes have been configured correctly by checking the {susemgr} {webui} branch server system formulas.
. Apply highstate on branch server.
+
----
salt <branch_server_salt_id> state.apply
----
. Synchronize OS images from Central Server to branch server.
+
----
salt <branch_server_salt_id> state.apply image-sync
----
