[[db-migration]]
= Database Migration

This is about PostgreSQL database migration.

If you want to upgrade {productname} 3.2 to {productname} 4 you must check whether {productname} 3.2 is already based PostgreSQL version 10.
If you are already using PostreSQL version 10, skip this section.
If you are using an older version, such as version 9.6, you must migrate PostgreSQL to version 10 before you begin the database migration.
For more information about migrating PostgreSQL 9.6 to version 10, see xref:db-migration.adoc#db-migration-prepare[].
If you run PostgreSQL{nbsp}9.4 on {productname} 3.2, see the 3.2 product documentation: https://www.suse.com/documentation/suse-manager-3/3.2/susemanager-best-practices/html/book.suma.best.practices/bp.sp.migration.html#sp.migration.postgresql.
You cannot migrate directly from PostgreSQL{nbsp}9.4 to version 10.




[[db-migration-prepare]]
== Prepare to Upgrade

Before you begin the upgrade, prepare your existing 3.2 system and create a database backup.

PostgreSQL stores data at [path]``/var/lib/pgsql/data/``, and logs to [path]``/var/lib/pgsql/data/pg_xlog/``.

.Procedure: Preparing to Upgrade

. Check the active PostgreSQL version:
+
----
psql --version
----
+
If you are using PostgreSQL{nbsp}9.6, you can upgrade to PostgreSQL{nbsp}10.

. Check the active smdba version:
+
----
rpm -q smdba
----
+
PostgreSQL{nbsp}10 requires ``smdba`` version 1.6.2 or later.

. Perform a database backup.
For more information on backing up, see xref:administration:backup-restore.adoc[].




== Upgrade PostgreSQL

[WARNING]
====
Always create a database backup before performing a migration.
For more information about a database backup, see xref:db-migration.adoc#db-migration-prepare[].
====

PostgreSQL upgrades can be performed in two ways: a regular upgrade, or a fast upgrade:

A regular upgrade will create a complete copy of the database, so you will need double the existing database size of space available.
Regular upgrades can take a considerable amount of time, depending on the size of the database and the speed of the storage system.
Regular upgrades also require database downtime, your database will not be accessible while the upgrade is running.

A fast upgrade only takes a few minutes, and uses no additional disk space.
However, fast upgrades are more likely to fail, and if this occurs you must restore the database from the backup.


.Procedure: Performing a Regular Upgrade
. Perform a database backup.
For more information on backing up, see xref:administration:backup-restore.adoc[].
. Begin the upgrade:
+
----
/usr/lib/susemanager/bin/pg-migrate-96-to-10.sh
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
The old directory is renamed to [path]``/var/lib/pgsql/data-pg96``.

The [path]``pg-migrate-96-to-10.sh`` script performs these operations:

* Stop spacewalk services
* Shut down the running database
* Check if PostgreSQL{nbsp}10 is installed and install it if necessary
* Switch from PostgreSQL{nbsp}9.6 to PostgreSQL{nbsp}10 as the new default
* Initiate the database migration
* Create a PostgreSQL configuration file tuned for use by {productname}
* Start the database and spacewalk services

[NOTE]
====
If the upgrade fails, the migration script will attempt to restore the database to its original state.
====

.Procedure: Performing a Fast PostgreSQL Upgrade
. Perform a database backup.
Without a verified database backup, you must not initiate a fast upgrade.
For more information on backing up, see xref:administration:backup-restore.adoc[].
. Begin the upgrade:
+
----
/usr/lib/susemanager/bin/pg-migrate-96-to-10.sh fast
----
. When the upgrade has successfully completed, you can safely delete the old database directory and reclaim lost disk space.
The old directory is renamed to [path]``/var/lib/pgsql/data-pg96``.
