[[bp.sp.migration.version]]
= Migrating from Version 4 to 4.x

Migrating {productname} from version 4 to 4.x (when available) can be done using either the {yast} Online Migration tool, or with the Zypper command line tool.

// So on my desktop, YaST calls it "online upgrades". We should check this terminology. LKB 2019-08-21

[IMPORTANT]
====
Upgrades should be run from a text console, rather than a graphical interface like GNOME.
If you are logged into a GNOME session running on the machine you are going to update, you will need to switch to a text console.
This does not apply if you are logged in from a remote machine (unless you are running a VNC session with GNOME).
====


== Migrate Using {yast}

To perform the migration with {yast}, use the Online Migration tool.

.Procedure: Migrating with {yast}

. From the command prompt, as root, launch the {yast} online migration tool:
+
----
yast2 migration
----
{yast} will show the possible migration targets with detailed summaries.
// I've removed the graphical option, because we tell people to use a text console. LKB 2019-08-21
. Select the appropriate target, and follow the prompts to complete the migration.
. Ensure the spacewalk services are running:
+
----
spacewalk-service start
----

If the process fails, check these issues first:

* If {yast} does not have the online migration module available, install the [package]``yast2-migration`` package.
After installing, restart {yast} to ensure the module is available.
* If there are older updates available, {yast} will notify you and ask to install them first.
We strongly recommend you install all updates before performing the upgrade.

During the migration, {yast} will install all recommended packages.
This can significantly increase the installation size of the system.
To only install required packages, open the [path]``/etc/zypp/zypp.conf`` configuration file and set thes variables:
----
solver.onlyRequires = true
installRecommends = false
----

This changes the behavior of all future package operations.



== Migrate Using Zypper

To perform the migration with Zypper, use the migration tool.


.Procedure: Migrating with Zypper
. From the command prompt, as root, launch the Zypper migration tool:
+
----
zypper migration
----
Zypper will show the possible migration targets with detailed summaries.
. Select the appropriate target, and follow the prompts to complete the migration.
. Ensure the spacewalk services are running:
+
----
spacewalk-service start
----


If the process fails, check these issues first:

* If Zypper  does not have the migration tool available, install the [package]``zypper-migration-plugin`` package.
* If there are older updates available, Zypper will notify you and ask to install them first.
We strongly recommend you install all updates before performing the upgrade.
