[[update.suse.manager.proxy]]
= Update {productname} Proxy

{productname} Proxies are managed in the same way as clients.
Thus patches and package updates combined as maintenance updates (MU) are to be installed with {productname} as it is done with other {productname} clients.
When the update is installed, you must check whether a restart of the proxy service is required.

// a remote command (or a salt state) can perform the restart.
// Creating an Action Chain can help with this task.
// With an action chain you can update proxies on batches, or all at the same time:
// These are the basic steps to run:
////
1. Run a salt command: `spacewalk-proxy stop`
2. Update the packages
3. Run a salt command: `spacewalk-proxy start`
////



== Before You Begin

Before you perform any proxy upgrade, schedule a maintenance window.
The clients registered to {productname} via the proxy will not be able checking in with {productname} for that period of time.
For more information about maintenance windows, see xref:administration/maintenance-window.adoc[].




== Update the Proxy

.Procedure: Updating the {productname} Proxy

. From the {productname} Server, where the Proxy is registered as a client, send the [command]``spacewalk-proxy stop`` command.

. Select the packages to be updated on the Proxy.

. From the {productname} Server, where the Proxy is registered as a client, send the [command]``spacewalk-proxy start`` command.

It is recommended to create an action chain of this command sequence.
Then you can apply it to several proxies to update them in batches or all at the same time.
